### ISSUE TITLE
Allow the saving of custom settings.

### ISSUE THREAD

**Issue by RicardoEPRodrigues** [konkor/cpufreq#10]
As of kernel 4.10, [intel_pstate allows the creation of custom governors](https://kernelnewbies.org/Linux_4.10#head-a8eab5c1440898821e9c1b9147240816f35d4530).

It would be awesome to see this extension support it.

**Comment by terencode** [comment]
Interesting, I'll document myself about it.

**Comment by RicardoEPRodrigues** [comment]
I was thinking more of a simpler solution. One problem I face when using this extension is that when using powersaver, I want the maximum frequency threshold to be for example 50% and to have to turbo turned off, so I have to change it each time I log in.

Maybe this problem should be in another issue, but it would be nice to have more governors that store these type of changes, so that I don't have to be always changing things.

What do you think?

**Comment by terencode** [comment]
A custom profile system?

**Comment by RicardoEPRodrigues** [comment]
Yes.

With this extension it's possible to create a config file that stores those types of data. Maybe it would be an easier solution.

**Comment by terencode** [comment]
Yes I would agree. 
What do you think @konkor ?

**Comment by konkor** [comment]
OK, I'll try to figure out optional saving/restore last settings this days.

**Comment by RicardoEPRodrigues** [comment]
What do you think of something like this for the creation of custom settings?

![cpufreq-savedesign](https://cloud.githubusercontent.com/assets/7673578/23162848/d0613766-f827-11e6-9930-911a30659b63.png)

(It's only design, I have not implemented anything)

**Comment by terencode** [comment]
Not bad, but wouldn't it be better to directly show the threshold frequency instead of percentage? There should also be a *Load Profile* dropdown

**Comment by RicardoEPRodrigues** [comment]
I think the way the thresholds are implemented use only percentage, but one could always see the percentage on the top.

Instead of a dropdown, I'd put profiles bellow powersave and if there were a lot then just use a scroll. 😄 This saves one click and the animation time for the dropdown.

**Comment by terencode** [comment]
Ok but then there should be a separation bar and *Profile* as title on the top to not have the possibility to mistake it with a governor 😛.

**Comment by RicardoEPRodrigues** [comment]
I think there is no need for the title, but I do agree on the separation bar.

I've been thinking and if the profile saves also saves which governor it uses then we could have a new design, something like this.

![photo 21-02-17 12 13 02](https://cloud.githubusercontent.com/assets/7673578/23164550/8789a836-f82f-11e6-81dd-1f1f57c99f0c.jpg)

**Comment by terencode** [comment]
Cool I like it. 
In addition I would add a '-'  at the end of each profile to be able to remove it and a '+'  at the end  to be able to add a new entry you can name and taking current settings below as a new profile.

**Comment by konkor** [comment]
**terencode**, it's how look this extension on intel_pstate driver except last image.
**RicardoEPRodrigues**, if do u want custom profiles on intel_pstate driver, take a look at https://extensions.gnome.org/extension/945/cpu-power-manager/ This extension is especially for intel_pstate driver and has save/restore, profiles...

**Comment by terencode** [comment]
@konkor I don't have sliders like that and why would he show it as a new design then?

**Comment by RicardoEPRodrigues** [comment]
I didn't know this extension. It seems this is one that fits my needs. But for others that don't have intel_pstate we could have a similar behavior.

I really think this extension could be the one fits all, don't you think?

**Comment by terencode** [comment]
Would also like too!

**Comment by RicardoEPRodrigues** [comment]
Tell me something I might be missing. In the extension @konkor sent, it does not show a governor selection, why is that?

Does it mean that in this extension, the governors for the intel_pstate (powersaver and performance) only change the CPU thresholds and Turbo Boost?

**Comment by terencode** [comment]
@RicardoEPRodrigues I in fact tried to use this extension but it produces unwanted behaviors (don't remember what) and was not really what I was looking for. 
According to https://github.com/martin31821/cpupower/wiki/Features and https://github.com/martin31821/cpupower/blob/master/cpufreqctl, it indeed does not let you change the governor, only adjusting thresholds and changing turbo boost state.

**Comment by terencode** [comment]
I will also think of what could be missing in the UI.

**Comment by konkor** [comment]
**terencode** min/max frequency available in intel_pstate mode. So ur cpu doesnt support intel_pstate or disabled in kernel cmd.

**Comment by konkor** [comment]
**RicardoEPRodrigues** that extension uses profile names with different sets of min/max frequencies. Like u wanted isn't?

**Comment by konkor** [comment]
I made this extension for cpufreq driver at 1st. But supported AMD/Intel new old processors on all kernels and GNome versions from 3.14.
cpufreq driver can setup different governors or frequency for each logical CPUs.
intel_pstate can set up same only min/max frequencies for all CPUs

**Comment by RicardoEPRodrigues** [comment]
It's what I wanted yes.

So cpufreq is more generic correct?

What I'm saying is that it would be nice if this plug-in also had custom profiles while using cpufreq, making it a good solution independent of what hardware you use.

**Comment by konkor** [comment]
yes it's more generic now. And supporting all x86 CPUs and drivers and modes, and profiles are good for intel_pstate driver only.
My extension generate UI dynamically if u have Turbo Boost u have switch for TB mode, if u have cpufreq u have additional governors supported by ur CPU if u have intel_pstate u have sliders for min/max frequency.

**Comment by RicardoEPRodrigues** [comment]
That would mean that the profiles would save whatever the user could use.

If the user did not have intel_pstate, the profiles could still tell which governor to choose and if the turbo is on or off.

(I do understand that for certain users the profiles would be overkill)

**Comment by terencode** [comment]
Thanks @konkor for reminding me that. 
I'm using cpufreq as I have an AMD cpu and I noticed it was dynamicly showing new governors I would modprobe so yeah nice one and misunderstood solved. 
It would still be interesting to integrate a profile system, as long as it's not going to be overkill as @RicardoEPRodrigues said. 
Maybe a drop-down at the top displaying current profile (*defaut* if nothing else created)  and being able to switch and create new ones.

**Comment by konkor** [comment]
yes it's overkill for most users. But i am going to do save/restore option like in ur 1st mock up. But i am still thinking it's not very good idea. For example when user did shutdown laptop in performance mode and when he tune on pc/laptop cpu could drain battery or heat...

**Comment by RicardoEPRodrigues** [comment]
It's a shame that only intel_pstate allows for CPU frequency min/max.

The battery drain could be solved if we detected which "Profile" to use depending on the battery status (charging/discharging). That may be a completely different issue.

**Comment by terencode** [comment]
Ye I don't get neither why we can't set the min/max thresholds with cpufreq... 
Acpi modules could also be use to switch profiles according to different hardware events

**Comment by konkor** [comment]
**terencode** u are right sry. i mean we cant set min/max frequency in percentages like in intel_pstate... but we can set up min/max in scaling_available_frequencies. i tried this and this work.

**Comment by konkor** [comment]
OK, save/restore current user settings ready and pushed to master branch.
**RicardoEPRodrigues** test  the extension if u can on intel_pstate driver. I don't have an opportunity to test on intel_pstate now.

**Comment by terencode** [comment]
Nice @konkor and no problem. Can't test it until Sunday tho.

**Comment by RicardoEPRodrigues** [comment]
It gives me an error while installing from master in a zip.

    TypeError: this._get_min is not a function

I replaced all `_get_min` with `_get_min_pstate` (and max too) and it worked.

Some notes:

If they are preferences, can we move them to a preferences window? I know it's more work, but it would make the experience similar to other apps.

On the other hand, I don't want to save all the changes. I was thinking more of something like: only when I press save button does the app save the current min/max.

For example, I normally use my laptop in battery mode aka min: 22%/max: 40%, but when I want to use full power, I change to min: 50%/max: 100%. I would save the first settings, but not the last.

**Comment by konkor** [comment]
ty very much. i fixed too. I renamed this functions bcs going to make equal system for cpufreq driver, i have opened new issue for this feature. Maybe after i'll do profiles.
So i think i am almost done with this issue 'saving/restore settings after reboot'.

**Comment by RicardoEPRodrigues** [comment]
Yes it's almost done.

Are you going to make a save button or leave it has it is?

**Comment by konkor** [comment]
i think it's done. i don't wanted a save button. i wanted checkbox but for uniform i picked a switch.
Maybe should change the text from 'Save settings' to 'Remember settings'? And maybe later i'll made button/menuitem 'Save profile...'

**Comment by konkor** [comment]
This is already done.
