### ISSUE TITLE
journalctl: Frozen dialog, CPU at 100% (by journalctl) after upgrade 

### ISSUE THREAD

**Issue by langpavel** [konkor/cpufreq#101]
After upgrade when I try open dialog I can [also](https://extensions.gnome.org/extension/1082/cpufreq/) see 100% usage of one core
by `journalctl` spawned from `cpufreqctl`

I can see that this is caused by https://github.com/konkor/cpufreq/blob/a9fa59c7610db23d2483274f7587d5b2306ebfba/cpufreqctl#L310
When I removed that line, everything works.

![image](https://user-images.githubusercontent.com/142462/55676387-b7b64e80-58d4-11e9-8895-726d218e1a52.png)

**Comment by konkor** [comment]
Yeah, I see it now. That pipeline could cause issues if some of the parts will be stacked for some reason. Also pipeline's readbuffer is limited to 200-500kB.
