### ISSUE TITLE
cpufreq writes user config to $HOME/user

### ISSUE THREAD

**Issue by timoschwarzer** [konkor/cpufreq#103]
Thank you for this great extension, I really like it!
Just one thing I don't like is that it's saving the user config (or something else? It's binary...) to `$HOME/user`. I like to keep my home directory clean and I generally think that cpufreq should save the config to `$HOME/.config/cpufreq/user`.

**Comment by konkor** [comment]
@timoschwarzer Thanks for the report. I know about this issue It's happening on some new GJS versions. I will make a workaround to fix this gjs issue in the next release.
