### ISSUE TITLE
Info panel appears in wrong place on Wayland

### ISSUE THREAD

**Issue by unholyeyebrows** [konkor/cpufreq#104]
Hi

I'm testing Fedora 30 with Gnome 3.32.1 and am running the latest version of this extension.

When running Gnome with x.org the plugin works fine and when I click on the tool bar icon the info pane appears directly below. However when I switch to running Wayland the info panel now appears towards the left of the screen. Please see screen shot attached.

![Screenshot from 2019-04-16 16-09-15](https://user-images.githubusercontent.com/11313997/56221730-b61e2080-6062-11e9-8e2a-740a810c8e6d.png)

Is there an easy fix for this? The extension is still completely functional it seems, but this is just a bit annoying. Thanks in advance.

**Comment by konkor** [comment]
@unholyeyebrows Thanks for the report! Yeah, I found Wayland problematic too bcs it hasn't a way to manage window position at all.

I think to make it's running in full application mode on Wayland in the next version. It will make possible to resize and move the main window at least. eh.
