### ISSUE TITLE
@GaVenga Hm. What's it showing in the Swap's tooltip text 0 bytes?

### ISSUE THREAD

**Issue by GaVenga** [konkor/cpufreq#105]
@GaVenga Hm. What's it showing in the Swap's tooltip text 0 bytes?

_Originally posted by @konkor in https://github.com/konkor/cpufreq/issues/100#issuecomment-484034653_By
Translation by Aunt GOOGLE:
Was zeigt es im Tooltip-Text des Swap 0 Byte?   ------>  Verstehe ich nicht;

nach meiner Änderung ist das Feld leer, in dem vorher    "SWAP       0%"   stand.

Der Teil mit dem "wandernden Balken", der erscheint wenn ich:
       this._swap.levelbar.no_show_all = true;

change to:
      this._swap.levelbar.no_show_all = false;

ist normal nicht sichtbar (wegen "this._swap.levelbar.no_show_all = true;") 

(levelbar not visible but "Swap" and "0%" shown)

**Comment by konkor** [comment]
When you are pointing on some widgets they could show black boxes with text inside called tool-tips text like this one:

![Screenshot from 2019-04-17 16-35-52](https://user-images.githubusercontent.com/1944781/56292108-38741680-612f-11e9-9368-8b6851b90ab7.png)

**Comment by konkor** [comment]
![Screenshot from 2019-04-17 16-45-33](https://user-images.githubusercontent.com/1944781/56292748-66a62600-6130-11e9-8dad-84706b759aa1.png)

**Comment by konkor** [comment]
@GaVenga Sorry for misunderstanding. Do you want to always show Swap widget?

I think no sense to show always empty Swap. Sometimes there could be no swap space at all. So it's hidden if it's 0.

**Comment by konkor** [comment]
Maybe it's good idea just show memory/swap usage in bytes instead of percentages?!
