### ISSUE TITLE
Question. Only one Power event

### ISSUE THREAD

**Issue by tgc12** [konkor/cpufreq#109]
I was working with both power events, but in the OMG update I have only one.
Is it a bug? Or is it still in the works?
By the way amazing work.

**Comment by konkor** [comment]
Thank you @tgc12 It's not a bug I removed it to make it more simple. Actually, it's rare thing when people use this feature. It's not tested well and many people is trying to use it with other power management tools and have a lot issues. But I'm planning to enhance events and I will back this event like an extra option. But I don't know when yet...

**Comment by tgc12** [comment]
Great. Thanks.
