### ISSUE TITLE
unable to install on19.04 ubuntu after first install

### ISSUE THREAD

**Issue by krzemienski** [konkor/cpufreq#110]
```The settings of extension cpufreq@konkor had an error:
```
SyntaxError: JSON.parse: expected property name or '}' at line 1 column 3 of the JSON data
```

Stack trace:
```
_init@/home/nick/.local/share/gnome-shell/extensions/cpufreq@konkor/prefs.js:108:28
wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
_Base.prototype._construct@resource:///org/gnome/gjs/modules/_legacy.js:18:5
newClass@resource:///org/gnome/gjs/modules/_legacy.js:114:32
buildPrefsWidget@/home/nick/.local/share/gnome-shell/extensions/cpufreq@konkor/prefs.js:475:18
_selectExtension@resource:///org/gnome/shell/extensionPrefs/main.js:75:22
_onCommandLine@resource:///org/gnome/shell/extensionPrefs/main.js:320:17
main@resource:///org/gnome/shell/extensionPrefs/main.js:635:5
@<main>:1:43
```

**Comment by krzemienski** [comment]
ive used both chrome and firefoxes extensions install and then also tried from source off the releases, it was running for a good 2 or 3 days and then i did a clean build intsall and tried again and now no good. looks like something from a previous install and checking against my settings on gnome. `buildPrefsWidget@/home/nick/.local/share/gnome-shell/extensions/cpufreq@konkor/prefs.j`

**Comment by konkor** [comment]
Hi, @krzemienski Looks like JSONcan't parse events profiles. I added try catch blocks to avoid crashing. You could try to remove all GSettings values to restore defaults like that:
```sh
dconf reset -f "/org/gnome/shell/extensions/cpufreq/"
```
Can you try github master branch? So you can try to run Preferences from a terminal:

```sh
./cpufreq-preferences
```

BTW Thank you for the supporting! I'm really appreciate it. Do you want me to include your link in the related docs?

Regards.

**Comment by krzemienski** [comment]
So after running `dconf reset -f "/org/gnome/shell/extensions/cpufreq/" ` I used the master branch from github and was able to install no problem. So far all is working except now I have too many stats / widgets in my top bar :) Appreciate the help, and glad to contribute please keep up the excellent work. If you ever need some feedback or help I'd be happy to connect!
