### ISSUE TITLE
can not login with ubuntu18.04

### ISSUE THREAD

**Issue by xiongmaoshouzha** [konkor/cpufreq#111]
## when i lock screen and login again , the screen block

**GNOME 3.28 , Extention version 38**

**Comment by konkor** [comment]
@xiongmaoshouzha I have just tested it on 18.04 and can't reproduce it.
Have you tried to disable all extensions except this one? The issue still exist?

Also you can switch to other virtual console Ctrl+Alt+F1 login there and run journalctl -f before unlocking the user session to see what's errors there.
Regards.

**Comment by xiongmaoshouzha** [comment]
Thank you for your reply  , I don't know why It work again . 
It may be that the previous version encountered a situation where I can't log in, so I tried to disable cpufreq to see the situation and found that I can log in after being disabled.

也许是扩展之间的冲突造成,但是我现在也无法重现状况了
