### ISSUE TITLE
Weird image on my second screen "OSPOW..."

### ISSUE THREAD

**Issue by sevmek** [konkor/cpufreq#112]
When I click on the icon to get the panel, a wierd image appears on my second screen. See attachment.
![Capture d’écran de 2019-06-01 23-21-31](https://user-images.githubusercontent.com/51275028/58753821-5de19780-84c5-11e9-8b7d-e88b39f027f2.png)

**Comment by konkor** [comment]
@sevmek LoL. The weird image is a splash screen on selecting the Power Manager via clicking of the panel monitor indicator. I just needed some art for that and found an old vector graphics from a tutorial I have done for Inkscape.

![tutorial_spot](https://user-images.githubusercontent.com/1944781/58759632-d8e29680-8535-11e9-9baa-c7ebe67994ee.png)

I'm considering to re-brand it to OSPower so.

Thank you for the screenshot I will try to fix it for dual monitors setup today.

BTW You could help me with that weird image (https://github.com/konkor/cpufreq/blob/master/data/splash.svg) :)

**Comment by sferra** [comment]
Could you please provide an option to disable the splash screen?

**Comment by konkor** [comment]
@sferra @mastercoy I placed that image not because I like it. Some people have a big delay on app startup. So they asked me to create some respond on clicking indicator to understand that the application selected and loading.

**Comment by tristan-k** [comment]
I second the request to have an option for the splash-screen.
