### ISSUE TITLE
Advertising on start

### ISSUE THREAD

**Issue by jaredAU** [konkor/cpufreq#113]
I'm getting a bit screen advertising whenever opening cpu-freq (not just clicking the icon on the dock, full opening).

I have never experienced this in previous versions so a little worried I have a corrupted version.

Do you have any affiliation with "OSPower" (whoever they are?)

**Comment by konkor** [comment]
@jaredAU Hi. I just answered [there](https://github.com/konkor/cpufreq/issues/100#issuecomment-500186968) about it. Some people have a big delay on the starting. So they asked me to add some splash screen to help to understand that app is selected and loading. **OSPower** is a new package name at least what I'm considering to do.

There will be an option in the preferences window to disable it. Actually, I have pushed that update today and it will arrive very soon.

**Comment by jaredAU** [comment]
Thanks for getting back to me, good to know it's not a corrupted version.
