### ISSUE TITLE
[Feature Request] Option to disable splash screen

### ISSUE THREAD

**Issue by sannagy90** [konkor/cpufreq#115]
Since the latest update, there is a splash screen every time opening cpufreq. It causes a couple of seconds of delay. It would be nice to have an option to disable it.

**Comment by konkor** [comment]
It's already done and will be available in the next release soon. Cheers

**Comment by stuaxo** [comment]
Hi,
   Even enabled, having it come up every time breaks the flow.   I'm not sure, you ever expect a splash screen to pop up when you press something in the title bar.

Having this as the default is not ideal, I had to google about this option, find this ticket and then work out how to get to the options.

The screen should maybe come up when press something like "about".

S
