### ISSUE TITLE
Make custom profiles system?

### ISSUE THREAD

**Issue by konkor** [konkor/cpufreq#12]
Ability to create/save new profiles and apply them.

**Comment by konkor** [comment]
I can't see any rational reason to do this yet...

**Comment by RicardoEPRodrigues** [comment]
May I ask why not yet?

**Comment by konkor** [comment]
@RicardoEPRodrigues we have talked about it at #14. And nobody replayed to this issue.
So what do you wanted from profiles exactly?
PS: I have a few ideas for now with #19 maybe i'll do some profiles there and a daemon for it. So i have been testing a lot the extension without other extensions and what i'm missing is CPU temperature and i'm thinking about optional support for _coretemp_ module.

**Comment by konkor** [comment]
@RicardoEPRodrigues I want make this extension lighter as possible so.

**Comment by RicardoEPRodrigues** [comment]
Personally I would create 3 profiles and maybe it can go as an example.

* Performance Mode: Performance Governor, Turbo Boost On, 100% Minimum Freq and All cores
* Balanced Mode: Powersaver Governor, Turbo Boost Off, 0% Minimum Freq, 50% Maximum Freq and All cores
* Powersaver Mode: Powersaver Governor, Turbo Boost Off, 0% Minimum Freq, 10% Maximum Freq and 1 cores

It would be easier to switch from one to another with profiles, but for now I have to make all the changes manually.

I agree that the extension must be light.

**Comment by konkor** [comment]
Nice. I'll reopen this issue)
I'd not recommend to use 1 core even for _Powersave Mode_ modern OSs and kernel works better on 2 cores to avoid overheating and CPU thermal throttle.

**Comment by konkor** [comment]
I have added new branch _profiles_. It's not complete yet. Very 1st screenshot:
![screenshot from 2017-05-03 21 12 03](https://cloud.githubusercontent.com/assets/1944781/25675127/10dbe3c6-3046-11e7-9dc2-1aa400a74561.png)

**Comment by konkor** [comment]
OK we have this now:
![screenshot from 2017-05-04 11 31 56](https://cloud.githubusercontent.com/assets/1944781/25696067/6e564f14-30be-11e7-863e-9d6d3aba9dc3.png)

**Comment by RicardoEPRodrigues** [comment]
I can't add new profiles :cry: I write the name of the new profile then I hit enter nothing happens, try to click check mark and it turns back to `New...`.

I think that for now the `New...` should be at the bottom of the profile list.

* Default
* Profile 1
* Profile 2
* Profile 3
* _New..._

**Comment by konkor** [comment]
@RicardoEPRodrigues There is no keyboard handler yet. Press OK icon to add a profile. It's collecting settings and add menu entry but u can't save now. I want be sure in the format before savings... I'll write when it's completely ready for testings.

**Comment by RicardoEPRodrigues** [comment]
So for now I can't save profiles right? Just to be sure :smile: The `OK` icon is the check mark correct?

When I press the check mark, OK icon, it does not add a profile. It returns to `New...`. Is it the correct behavior?

**Comment by konkor** [comment]
@RicardoEPRodrigues ty again) U are n1!!! It's look like in new gtk versions this events masked.

**Comment by konkor** [comment]
@RicardoEPRodrigues It was a bug. Yesterday I reported this [bug](https://bugzilla.gnome.org/show_bug.cgi?id=782190). And today It is closed. TY for improving Gnome :)

**Comment by konkor** [comment]
OMG The Profiles makes about +50% of the master code. If someone test it I would be glad to see some comments [profiles.zip](https://github.com/konkor/cpufreq/archive/profiles.zip)

**Comment by RicardoEPRodrigues** [comment]
It works like a charm.

Yet I'm having trouble understanding when the profile is saved. Could you explain it a little bit?

How to create a profile 101.

**Comment by konkor** [comment]
@RicardoEPRodrigues when you select 'New...' and enter some name (My very own Profile :)) press Return or OK button... that it. To switch profile you have select profile. If you want remember profile for next boot u should switch ON Preferences->'Remember Settings' (if it's off) and select profile name. To rename profile select (properties). to delete press last icon.

**Comment by konkor** [comment]
@RicardoEPRodrigues So It's saving profile at same time u created some profile.

**Comment by konkor** [comment]
There is keyboard hotkeys in edit mode too. 'Esc' - cancel edit and 'Enter/Return' to save changes.

**Comment by RicardoEPRodrigues** [comment]
Is it possible that the UI allows saving changes to a profile? Maybe a button next to edit or something like that. Maybe another button may make the UI too crowded, but it would help the users make all changes with a mouse only.

**Comment by konkor** [comment]
No. I think It's too much for me. I like minimalism so and don't like to add extra code. So profile creating is not an everyday task. There is no difficulty to create some new profile even with same name and delete old. Just make once your settings and give it a name. I want to add more important functionality to extension so i want to keep it light like possible.

**Comment by konkor** [comment]
@RicardoEPRodrigues Don't blame me if my commends sound hard. I just want to discuss and make good for the project. I really appreciate all your comments and opinions!

**Comment by RicardoEPRodrigues** [comment]
@konkor I do like to have these conversations. What I'm thinking is that the `Edit mode` is almost optional.

I was thinking that if you can easily create a new profile, why not just remove the edit mode. Less confusion on when does it save.

Just an idea. :smile:

**Comment by konkor** [comment]
@RicardoEPRodrigues maybe you are right. Actually It's not edit mode just renaming mode. I can hide edit button for now... wasted time heh

**Comment by konkor** [comment]
@RicardoEPRodrigues Eh, here is full editing support now. You can set parameters before and while editing. Press `OK` or `Enter` to apply changes. Press outside text entry or `Esc` to cancel editing. Now is it OK? xD

**Comment by RicardoEPRodrigues** [comment]
It's OK :smile: 

I noticed I have an issue when changing profiles. I have the Default (Min 0%, Max 100%, Turbo Off), Performance(Min 100%, Max 100%, Turbo On) and Powersaver(Min 0%, Max 0%, Turbo Off, 4 Cores).

When I change from Default or Performance to Powersaver it seems that it doesn't disable the cores, but sets the Max 0% to the 4 active ones.

**Comment by konkor** [comment]
@RicardoEPRodrigues Are you still on `intel_pstate'? I'm testing now on intel pstate mode and can't reproduce ur issue. Can you recreate broken profile?
It seems like you created profile too fast. The changing of active cores needs 2 seconds to avoid kernel often calls from the core slider.

**Comment by konkor** [comment]
@RicardoEPRodrigues One more I would recommend you in the your Performance Profile **set Min at least 80%** in the **intel pstate mode** especially for laptops! Because in the **intel pstate mode** 100% equal to nominal frequency + turbo boost frequency (about 120%)!!!!! That can easy overheat your CPU because laptops cooling system is very weak even on Dell or Mac.

**Comment by RicardoEPRodrigues** [comment]
I recreated the profiles and opened up System Monitor. It says I have 4 active CPUs. Yet the indicator still says the frequency is about 3.4GHz when it should be 800 MHz.

I think it may be counting inactive cores...

**Comment by konkor** [comment]
No, it doesn't count inactive core threads. Are you still on Ubuntu Gnome 17.04? I'm going to test it bcs it looks like other bug :(
Usually It can show high frequency when applying  some profile bcs the extension stops all events but in few seconds you should see updating on the frequency indicator...

**Comment by RicardoEPRodrigues** [comment]
When I switch between Performance and my Default it works fine after a couple of seconds, but in Powersaver, when I disable cores, it doesn't change.

**Comment by konkor** [comment]
@RicardoEPRodrigues can you show me output of
```
ls /sys/devices/system/cpu/cpu7/topology
```
for cpu 7,6,5,4 when you have 4 active CPU...

**Comment by RicardoEPRodrigues** [comment]
When they are active I see this:

    core_id        core_siblings_list   thread_siblings core_siblings  physical_package_id  thread_siblings_list

When they are offline I see this:

    ls: cannot access '/sys/devices/system/cpu/cpu7/topology': No such file or directory

I think it disables the cores but doesn't force the Min/Max frequency or disables the Turbo Boost. It's a weird behavior.

**Comment by konkor** [comment]
> I have the Default (Min 0%, Max 100%, Turbo Off), Performance(Min 100%, Max 100%, Turbo On) and Powersaver(Min 0%, Max 0%, Turbo Off, 4 Cores).

@RicardoEPRodrigues What governors do you have in your profiles? I have noticed when I switch from powersave governor to performance intel driver tunes Turbo Boost automatically on... Maybe here something related I dunno

**Comment by RicardoEPRodrigues** [comment]
On Performance I have performance governor, on the others I have powersave. When switching from Performance to Default it works fine, maybe because I don't mess with the cores. IDK.

**Comment by konkor** [comment]
@RicardoEPRodrigues I think there can be a delay when kernel releases some core. I made additional call to reinit IO streams. Can you update to latest and test it again. TY very much.
If It is not help. I would like you to make 2 additional steps to be sure:
1. Turn off `Remember Settings` if it is.
2. Reload Extension by pressing `Preferences -> Reload`
If after reloading frequency indicator works well. It is the delay for sure...

**Comment by RicardoEPRodrigues** [comment]
The problem persists, it seems like the turbo is still turned on in the offline cores or something.

I created a second powersaver profile where I keep all the cores active and it works perfect.

If I do `Performance -> Powersaver 4 cores` it gets weird. If I do `Performance -> Powersaver 8 cores -> Powersaver 4 cores` it works well.

**Comment by konkor** [comment]
So freq indicator is still sticking to Max frequency after manual Preferences -Reload??? But you have 4 cores in the system monitor? And governor shows powersave? And turbo boost off? Right?

**Comment by RicardoEPRodrigues** [comment]
> So freq indicator is still sticking to Max frequency after manual Preferences -Reload???

Yes

> But you have 4 cores in the system monitor?

Yes

> And governor shows powersave?

Yes

> And turbo boost off?

Yes

Thank you for your time!

**Comment by konkor** [comment]
@RicardoEPRodrigues nice. so show the output when it's sticked for cpu (0,1,2,3):
```
cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_cur_freq
```
Thank you too)

PS: I don't have near intel_pstate machine now, only remote, and can't test Ubuntu on it so. You are very helpful.

**Comment by RicardoEPRodrigues** [comment]
It seems the frequency is not set to a lower frequency.

    cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_cur_freq
    3201599

They all have a high frequency.

**Comment by konkor** [comment]
@RicardoEPRodrigues It's really weird but the newest kernels just ignore requests to change frequencies if not all core/cpu threads online and selected `powersave` governor. I'm going to ask/report this issue at kernel.org... So it seems like affected both acpi and pstate kernel modes. I want you to test 2 things without profiles.
**1st thing**
0. Turn off **Remember Settings**
1. Turn on all cores, select **powersave** governor min 100% max 100%, Turbo on.
2. Turn off a half cores (i guess it is 4 for u).
3. Reduce Frequencies to 0% for example.
4. Close the extension popup menu and reopen it.
5. Tell me what happens with frequencies?

**2nd thing**
-//- do the same steps but for **performance** governor!

Thank you.

**Comment by konkor** [comment]
@RicardoEPRodrigues wait... i can't reproduce it manually. It looks like delay bug in the kernel when it changing everything to quickly. I want to understand when and why exactly this happening. If u have any thoughts let me know.

**Comment by RicardoEPRodrigues** [comment]
I think the work you put yourself in trying to fix this bug is too big. I think for now we should make a bug report and a notice on the experimental feature readme.

**Comment by konkor** [comment]
@RicardoEPRodrigues I made some changes in the sequence of profile loading. You can try.
So I have tested 2 machines (2000x/3000x) with _intel_pstate_ driver and different kernels and OS (including Ubuntu Gnome 17.04)... I can't reproduce ur issue yet :( But last patch can help if not I could increase/add extra pauses in the profile loading sequence for testing purposes especially for you...
So I found some other features/abilities/bugs in the intel_pstate behavior:
1. When all cores enabled You can't set 0% min/max frequencies in the `powersave` mode. But when you have `performance` or disabled cores It's working well.

@RicardoEPRodrigues Disable `Remember Setting` option for tests pls because You can't tell for sure where is an error.

**Comment by RicardoEPRodrigues** [comment]
It didn't fix the issue, but I seem to be isolated incident.

You can't reproduce the issue and I found a workaround for my problem (first setting all to 0% then disabling cores), so don't worry about this problem.

I think it might be related with my 17.04 been upgraded from 16.10.

**Comment by konkor** [comment]
@RicardoEPRodrigues TY for quick response. Theoretically, the core's turning on/off can take some time. Especially when the cores is busy in that time it's why i do 2 second timeouts in the main menu. So when i test on the clean system without any files and background processes like gnome-tracker, tacker-extract, databases, servers, darktable and etc it's working well.
I'm going to make a timeout in 1 second after setting cores for starter. Or maybe just 2 seconds to see difference for sure... I let you know...

**Comment by konkor** [comment]
@RicardoEPRodrigues Yeah it's good idea. I could change to (--- GHz) to example.
I made patch so you are ready to test it.

**Comment by konkor** [comment]
@RicardoEPRodrigues Do you still want to become the contributor? Add this string

```
this.title = "WRITE WHAT YOU WANT BUT NOT SO LONG LOL \u3393";
```
after the debuging string `print ('Loading profile...', JSON.stringify (prf));` in the **_load_profile: function (prf)**
And make pull request you could do this on github online.

**Comment by RicardoEPRodrigues** [comment]
Simple enough, thank you! :smile: #29

**Comment by konkor** [comment]
@RicardoEPRodrigues so what do u say 2 seconds working for you?

**Comment by RicardoEPRodrigues** [comment]
After 2 seconds the changes are applied.

**Comment by konkor** [comment]
@RicardoEPRodrigues OMG nice... but now try reduce to 1 second, if it's working push changes to :)

```
core_event = GLib.timeout_add_seconds (0, 2, Lang.bind (this, function () {
```
to
```
core_event = GLib.timeout_add_seconds (0, 1, Lang.bind (this, function () {
```

**Comment by konkor** [comment]
@RicardoEPRodrigues i can't imagine how can ur system affect the kernel except for loading. Here is other step changing of governors is changing frequencies too. So we have to test it too.
Yeah I know it's hard work)

**Comment by konkor** [comment]
Test it now... for cores

**Comment by RicardoEPRodrigues** [comment]
I know that `performance` governor sets Min/Max to 100% and activates Turbo Boost.

--- 

Your solution did nothing...

**Comment by konkor** [comment]
@RicardoEPRodrigues OK negative result is result too.
To be clear You have to test the extension from live dvd or flash drive. Download Fedora 25 or/and Fedora 26. Write to DVD (Brasero) or USB flash drive (memory card works too) with gnome-disks app (Select ur flash drive and choose Restore Image... select iso...) or dd command

```
sudo dd if=./fedora.iso of=/dev/sdX bs=1M
```
where sdX - your USB flash drive. Go to [extensions.gnome.org](https://extensions.gnome.org/extension/1082/cpufreq/) install it and update from [profiles.zip](https://github.com/konkor/cpufreq/archive/profiles.zip) Make profiles and test it... After that we'll push it to master and on gnome to get more reports lol :)

**Comment by RicardoEPRodrigues** [comment]
I'll get to that this weekend :smile:

**Comment by konkor** [comment]
https://i.imgur.com/v0i6EcV.png

**Comment by terencode** [comment]
@konkor  daaaaamn looks soooo good!

**Comment by konkor** [comment]
@terencode ty very much. It's very 1st step yet. I'm working on the Info Panel. So I'm going to publish this brunch and make issue to talk about the info in this widget. For now I'm want to show CPU model, Linux/kernel version, system loading, temperature, thermal throttle, governors per CPU if they are Mixed, and WARN MESSAGE PLACE to say 'Your System OK', 'Hey, something wrong (to loaded, to hot, have throttling, low memory....)

**Comment by terencode** [comment]
@konkor so much things to do, good luck!

**Comment by RicardoEPRodrigues** [comment]
@konkor I've tested the extension of Fedora 22 Live Boot and the problem persists when I switch from a Performance profile to a Powersaver one (switching the number of active cores).

Additionally the problem with the Network bugging out also exists in Fedora. I think it might be related to specific WiFi drivers...

**Comment by konkor** [comment]
@RicardoEPRodrigues I made a some crazy full delayed (like JavaScript can) profile loading with 2 seconds (2000 msec) delay for each stage. So this version will load a profile about 10 secs. Run in the terminal `sudo journalctl -f` to see what's going on...
```
_delayed_load: function () {
        let delay = 1000;
        if (core_event != 0) {
            Mainloop.source_remove (core_event);
            core_event = 0;
        }
        this._load_stage (this.prf);
        this.stage++;
        switch (this.stage) {
            case 1: // reset min/max frequencies
                delay = 2000;
                break;
            case 2: // setting governors
                delay = 2000;
                break;
            case 3: // setting boost
                delay = 2000;
                break;
            case 4: // setting min frequency
                delay = 2000;
                break;
            case 5: // setting max frequency
                delay = 2000;
                break;
            default:
                return;
        }
        print ("load delay", delay);
        core_event = Mainloop.timeout_add (delay, Lang.bind (this, this._delayed_load));
    },
```
You have to play with this timeouts. You have to increase all this from timeouts 2000 ms to 5000-10000 until ur profiles isn't loaded. Then decrease 1 by 1 to 1000/500/100/50 ms delays to find optimal ranges and find weak places.

So I am pretty sure ur problem in the 'intel_pstate' driver. So test it without intel_pstate once at least...
I'm waiting for ur replay...

**Comment by RicardoEPRodrigues** [comment]
Ok this bug was tricky, but I found the solution.

It has nothing to do with the delays. It's weird, but what happens is if a CPU has the performance governor (even if it is disabled) it forces the Turbo Boost ON, because of that even if I have cores on powersave they are always on 100%... it must be `intel_pstate` doing...

I'm making a pull request that basically sets all cores to the selected governor in `intel_pstate`.

**Comment by konkor** [comment]
But you still can do it manually... So there is a question... If you are going to ur Performance profile (switch Remember setting OFF to be sure) and after that:
1. Turn off 4 cores;
2. Set governor to `powersave`;
3. Set turbo off;
4. Set minimum frequency to 0%;
5. Set maximum frequency to 0%...
Is the issue exist or all OK?

**Comment by konkor** [comment]
@RicardoEPRodrigues now we have sequence:
1. Cores count;
2. Reset min/max (it must have for acpi mode)
3. Governors per core
4. Turbo
5. Min freq
6. Max freq

So if you want change all governors 1st you have to add
0. Turn on all cores;
for the switching from less cores to less (2 to 4, 4 to 6....)

You could play with _load_stage function too...

**Comment by RicardoEPRodrigues** [comment]
I made a pull request #32. Could you see if it is a good solution? All the profiles define all the cores even if they are disabled.

**Comment by konkor** [comment]
OMG Is it working for you?

**Comment by konkor** [comment]
So https://github.com/konkor/cpufreq/issues/12#issuecomment-303065211 dont work?

**Comment by konkor** [comment]
So i'm waiting for answer https://github.com/konkor/cpufreq/issues/12#issuecomment-303097916 too...

**Comment by RicardoEPRodrigues** [comment]
When I do those steps I get the same bug. For some reason if I have any core on Performance, they all behave has if they are on performance... It's truly weird...

**Comment by RicardoEPRodrigues** [comment]
My pull request fixes the issue for `intel_pstate`.

**Comment by konkor** [comment]
Finally, I get an answer. So can you reduce delays from 2000 ms to 50 ms and tell me how it works? If you think it only sequence issue.
So what gonna happen if you switching from (2 cores performance 6 offline) to ur 4 cores powersave? So it couldn't work on older (stable) kernels without cpufreq profiles links...

**Comment by RicardoEPRodrigues** [comment]
Damn... We do have to turn on all cores before making changes...

> So what gonna happen if you switching from (2 cores performance 6 offline) to ur 4 cores powersave?

Because not all cores are active, setting the governor for all fails.
I'll update the pull request! :smile: 

Reducing the delays worked well.

**Comment by konkor** [comment]
Cool. So is it working in all your cases now?

**Comment by RicardoEPRodrigues** [comment]
Yes :smile:

**Comment by konkor** [comment]
Wow finally... we can moving on, after my finally test and so. I'll merge profiles to master... Congrats

**Comment by RicardoEPRodrigues** [comment]
When testing could you check on mixed profiles. That is something that I didn't tested a lot.

**Comment by konkor** [comment]
OK I think it's time to close this issue. Profiles branch merged to master and gnome...

**Latest version has a changes in the profiles! There is a new property type of driver (acpi:boolean).
Please remove or update your testing profiles!!! `Don't forget to load/activate them first!`**

I'll do checking for the types later because profiles in pstate can't work properly in acpi and so... I'm going merge profiles/master to info branch for next development.

Thank you all!

**Comment by konkor** [comment]
PS: Someone maintained the extension on Arch Linux https://aur.archlinux.org/packages/gnome-shell-extension-cpufreq-git/

**Comment by konkor** [comment]
Gnome moderator is in shock of changes.

**Comment by RicardoEPRodrigues** [comment]
Good shock or bad shock?

**Comment by konkor** [comment]
How is know? Maybe because we are going to oversize Gnome-shell... Or just a lot changes like +50%...
But anyway he activated it.

**Comment by konkor** [comment]
@RicardoEPRodrigues he asked `Just don't do big code-reorderings while including new features.`

**Comment by RicardoEPRodrigues** [comment]
Then my pull request should be 2 separate things: Code reordering, Profiles on Top. Separate.
