### ISSUE TITLE
Turbo Boost setting is often disabled after standby

### ISSUE THREAD

**Issue by Donnerbart** [konkor/cpufreq#123]
The Turbo Boost setting on my machine is often disabled after standby. I have to manually enable it in the settings, then it works fine.

Any idea if this can be an issue of the extension or how to debug this?

**Comment by konkor** [comment]
HI, @Donnerbart ! Do you have the _Remember settings_ option enabled? Maybe there is some other power daemon on your system installed?!

**Comment by mmrezaie** [comment]
I do and this is happening to me too. Quite often actually. I have a notebook, and I am on latest ubuntu (19.10).

**Comment by fractalvision** [comment]
Same here, i5-2430M / 18.04.4 LTS.
