### ISSUE TITLE
Would you rename the Turbo Boost to Turbo Boost / PBO

### ISSUE THREAD

**Issue by laichiaheng** [konkor/cpufreq#124]
Turbo Boost in the intel technology, AMD uses PBO, so we should rename it to `Turbo Boost / PBO`

**Comment by RicardoEPRodrigues** [comment]
Hello,

Maybe we could use a single generic name, like "Turbo", and add a tooltip that describes what it does on different CPUs. What do you think?

**Comment by konkor** [comment]
Kernel's generic name for all such technologies is just Boost. Actually, I'm hearing PBO first time.

We could add some explanation in the tooltip text.

**Comment by laichiaheng** [comment]
@RicardoEPRodrigues Perfect idea!

**Comment by konkor** [comment]
What about **Frequency Boost**? I think It would be more general and self-explaining name for this feature?
