### ISSUE TITLE
Turbo boost setting always reactivate itself on startup

### ISSUE THREAD

**Issue by midjean** [konkor/cpufreq#125]
Hello,
my lenovo legion y540 is not throttling as soon as I keep the turbo boost feature off.
So basically when I start my laptop, cpufreq says turbo boost is not active and my system is ok.
But then about 10 minutes later turbo boost activate itself automatically and my laptop start to throttle.
I have tried to play with all the different settings but the issue appears anyway at each startup.
What can I do to disable turbo boost permanently  or solve the reactivation ? Note that tlp is also installed.
Thank you
Jean

**Comment by konkor** [comment]
Hi, @midjean ! I think Turbo Boost is reactivating by something else like TLP or some other power daemon.

**Comment by midjean** [comment]
Hello konkor,

Yes it seems that TLP and cpufreq are conflicting each other.
My main problem is that my cpu is only throttling when turbo boost is activated, so when I power on my computer the cpu is throttling until I login, then cpufreq or/and TLP is deactivating turbo boost.
I don't have any option in the BIOS to deactivate turbo boost.
So question is there a way to prevent turbo boost before I login to my session ?

**Comment by midjean** [comment]
Sorry forget to mentioned that I already tried without TLP but with only Cpufreq managing my governor

**Comment by konkor** [comment]
@midjean I'm working on the new version. It will have SystemD service which could load user profile on stage 3. But you should create custom BASH script with setting TB off and SystemD unit to call it on startup meanwhile. That will help you even more bcs it could apply setting early.

_Ex. disable_boost.sh_

```sh
#!/usr/bin/env bash

## for acpi driver
/usr/bin/cpufreqctl --boost --set=0

## for intel_pstate
/usr/bin/cpufreqctl --no-turbo --set=1
```

_Ex. noboost.service_

```sh
[Unit]
Description=Disable Turbo Boost

[Service]
Type=simple
ExecStart=/usr/bin/disable_boost.sh

[Install]
WantedBy=default.target
```

**Comment by midjean** [comment]
@konkor I just created this script and called it with systemd and it's better now !
When I login into my session the cpu frequency is not above 2.60ghz as requested and turbo boost is disabled.
I still get cpu throttled : 36 which is much less than the usual 500 at startup
I guess turbo boost is still running under bios and grub before systemd start the script ?

**Comment by konkor** [comment]
@midjean Yes, in the grub menu and at begging of system/kernel loading it has enabled turbo-boost.

BTW, Please make cleaning of your cooling system. It could need a thermal paste replacement and service or replacement of fans.

**Comment by midjean** [comment]
My system is 4 months old now it might need a small clean for sure but I certainly remember that the cpu was throttling since the very first day, not sure what can I do about it...
Should I close this post ?

**Comment by konkor** [comment]
@midjean It's very often new laptops has defects from factory. I had Dell laptop which has a defect in the cooling radiator - I placed extra copper pod to fix it. Unfortunately, it was too late... There are a lot examples of bad conditions directly from manufacturer.
Good luck!

**Comment by midjean** [comment]
@konkor I have opened my laptop few days ago to clean fans and repast with liquid thermal paste.
My cpu is not throttling anymore even in full performance with turbo boost, and it also considerably improved my temps.
Thanks for your work !

**Comment by konkor** [comment]
@midjean I'mm glad to hear you fixed it ;)
