### ISSUE TITLE
frequency indicator text alignment is off by 1px

### ISSUE THREAD

**Issue by dantob** [konkor/cpufreq#128]
![1](https://user-images.githubusercontent.com/12003874/66007379-8621e700-e4f5-11e9-95a2-a70f3b4397e8.jpg)
![2](https://user-images.githubusercontent.com/12003874/66007377-84582380-e4f5-11e9-894e-b443e4cba586.jpg)

its really obvious if you have a lot of text based indicators

**Comment by konkor** [comment]
@dantob Hi. I think I fixed it. It will be available in the next release. 
Thanks for report.
