### ISSUE TITLE
Dynamically loaded governors not showing up anymore

### ISSUE THREAD

**Issue by terencode** [konkor/cpufreq#13]
After executing `# modprobe cpufreq_powersave `, the new available govenor is not showing up anymore until manually reloading the extension.

**Comment by konkor** [comment]
Do u think It's good idea to check user installation each time u open extension menu not only on startup? Checking required pakages and governors, rebuild menu... I think about this.

**Comment by terencode** [comment]
I would say yes.

**Comment by konkor** [comment]
@terencode So i merged gio to master and made a little workaround for ur problem. Now it should show correct current governor.
Did you know what each CPU can has own governor and this extension sets same governor for all available CPUs and getting current from CPU0 only?

**Comment by terencode** [comment]
Yes I knew that.
