### ISSUE TITLE
"user" file in home directory

### ISSUE THREAD

**Issue by kareliot** [konkor/cpufreq#132]
I have a strange file in my homedirectory that is just called "user".
A "tail ~/user" gives me lot of incomprehensible stuff but also this:
"s::RunScript^�/home/philipp/.local/share/gnome-shell/extensions/cpufreq@konkor/cpufreq-application:2_�main (/home/philipp/.local/share/gnome-shell/extensions/cpufreq@konkor/cpufreq-application:47)@"

is this file related to or created by cpufreq?
What does it do and why is it siting in my home directory (and not in a hidden folder or so)?
This is totally unexpected behaviour of a extension, I would say, especially because it took me a while to trace it to cpufreq

**Comment by konkor** [comment]
@kareliot Just remove it. It was created with an old version of the application on GJS with enabled profiling option. Newer versions shouldn't create this dump file for a profiling.

**Comment by kareliot** [comment]
Okay, thanks for the quick response! I deleted the file.
