### ISSUE TITLE
How do I disable Intel P-state driver on a device not using grub (systemd)

### ISSUE THREAD

**Issue by saikat0511** [konkor/cpufreq#133]
I am using Pop OS which uses systemd instead of grub so I can't perform the steps mentioned in the FAQ.

**Comment by konkor** [comment]
There is [arch wiki](https://wiki.archlinux.org/index.php/systemd-boot). So looks like you should edit your kernel boot **options** section in `esp/loader/loader.conf`and update bootloader after it with _sudo bootctl update_.

**Comment by saikat0511** [comment]
thanks it worked

**Comment by saikat0511** [comment]
you should add this info in the faq btw, might help other people...

**Comment by Tup0lev** [comment]
> There is [arch wiki](https://wiki.archlinux.org/index.php/systemd-boot). So looks like you should edit your kernel boot **options** section in `esp/loader/loader.conf`and update bootloader after it with _sudo bootctl update_.

Sorry for the dumb question but could you elaborate a little bit more on how to do it? Like what exactly to put into the loader.conf file? should I just append 'GRUB_CMDLINE_LINUX_DEFAULT="quiet splash intel_pstate=disable' onto the file? It doesn't look like so because it has GRUB in it...

**Comment by saikat0511** [comment]
@Tup0lev edit the boot entry .conf file located in _esp_/loader/entries folder and add `intel_pstate=disable` in the end of options line.

**Comment by Tup0lev** [comment]
thanks
