### ISSUE TITLE
It takes a couple of seconds to open the cpufreq window after pressing the icon

### ISSUE THREAD

**Issue by stuaxo** [konkor/cpufreq#149]
I guess some part of this app is blocking, that could be async / in the background.

It would be good if the window could open instantly on pressing it.

Tested on Ryzen 2500u with NVME SSD, so this shouldn't be the hardware causing the delay.

**Comment by Rushmore75** [comment]
Also having this issue, when I click the extension icon it takes a good 25 seconds to load the ui

**Comment by konkor** [comment]
I can't confirm it. I think, it could be possible sometimes on unstable systems and/or huge CPUs. But anyway it's better to wait some time then keep huge UI in the background. Btw I can use the extension without opening of UI for weeks... Thanks

**Comment by stuaxo** [comment]
The Ryzen 2500u is no where near a huge CPU, while it had decent core count + speed - it's was definitely in a midrange laptop at the time I was testing.

Still, IO is good NVME + the test system had been upgraded to 32gb.

**Comment by konkor** [comment]
@stuaxo you should try some different distro on live session. It could be missing firmware or bugs in your current system libraries etc. I had an AMD system with broken synchronisation between cores and system was unusable until I installed a new firmware to fix it.

**Comment by stuaxo** [comment]
I'm happy to close this.  I have a different laptop with a similar chip, I don't have this installed any more.

If I install it again and have the same issue I'll reopen this.
