### ISSUE TITLE
Gio version of the CPU frequency monitoring ready for testing

### ISSUE THREAD

**Issue by konkor** [konkor/cpufreq#15]
Gio version of the CPU frequency monitoring is working faster in 26 to 200 times on my machine.
So there is no GLib.Processing for cpufreqctl, no bash, no cat, no grep each 2 seconds anymore.

**Comment by konkor** [comment]
New branch available here:
https://github.com/konkor/cpufreq/tree/gio
Archive for downloads:
https://github.com/konkor/cpufreq/archive/gio.zip

**Comment by terencode** [comment]
Would you like me to benchmark it against my machine?

**Comment by konkor** [comment]
Ohh hi) Ofc i'd like it!

**Comment by terencode** [comment]
heeey :) alright going to test that!

**Comment by konkor** [comment]
To benchmark u can just run 'benchmark.js' from archive folder... Did you have a lags before async calls?

**Comment by terencode** [comment]
I was actually going to do that thanks.
Yes, remember, I was the one opening the issue about it.

**Comment by konkor** [comment]
Nice. So you can test it for this issue a few days.
I think it's the best method. It's read directly from the kernel MemoryStream at `/sys/devices/system/cpu/cpuX/cpufreq/scaling_cur_freq` and doesn't call external Linux commands and tools like bash, cat, grep. So this method is saving memory, file headers and less code in the extension. Thank you again!

**Comment by terencode** [comment]
![image](https://cloud.githubusercontent.com/assets/12665563/24082929/fc724c22-0ccd-11e7-873c-a3c3d195e127.png)
13 times faster for me!

**Comment by terencode** [comment]
That's nice maybe wait some days for more testing but definitely go for Gio!

**Comment by konkor** [comment]
For my system (Core i7-920 8 CPU Threads) it's:
```
Gio start...
Gio test end. 94 milliseconds.
GLib processing start...
GLib processing end. 2382 milliseconds.
```
and for 1 core thread simulating it's:
```
Gio start...
Gio test end. 13 milliseconds.
GLib processing start...
GLib processing end. 2340 milliseconds.
```

**Comment by terencode** [comment]
I have an AMD FX9370 8 CPU threads

Performance governor (4.4Ghz 8 cores):
```
Gio start...
Gio test end. 454 milliseconds.
GLib processing start...
GLib processing end. 7035 milliseconds.
```

Powersave governor (1.4Ghz 8 cores):
```
Gio start...
Gio test end. 492 milliseconds.
GLib processing start...
GLib processing end. 7030 milliseconds.
```

Performance governor (4.4Ghz single core):

```
Gio start...
Gio test end. 21 milliseconds.
GLib processing start...
GLib processing end. 1936 milliseconds.
```
Powersave governor (1.4Ghz single core):

```
Gio start...
Gio test end. 285 milliseconds.
GLib processing start...
GLib processing end. 17896 milliseconds.
```

**Comment by konkor** [comment]
Thank you. I'll push this version to master branch in few days if you or someone other don't report some issues.

**Comment by konkor** [comment]
So about ur tests. 17896 ms is too much!!! About 18 seconds!!! I think ur HDD has issues.

**Comment by konkor** [comment]
Here is my test for example
powersafe (1.6GHz)
```
Gio start...
Gio test end. 150 milliseconds.
GLib processing start...
GLib processing end. 2419 milliseconds.
```
performance (2.67GHz)
```
Gio start...
Gio test end. 94 milliseconds.
GLib processing start...
GLib processing end. 1758 milliseconds.
```

**Comment by terencode** [comment]
Why would this relate to HDD? The whole system was laggy and I guess it's what you expect from a 1.4Ghz single core cpu running a high demanding desktop environment.

**Comment by konkor** [comment]
terencode maybe u are right. i'm just talking about checking HDD's smartdata.

**Comment by konkor** [comment]
OMG now benchmark's results looks like:
(100 cycles)
```
Gio start...
Gio test end in 0 milliseconds.
GLib processing start...
GLib processing end in 2150 milliseconds.
```
for NUMBER_OF_TEST_CYCLESx10 (1000 cycles)
```
Gio start...
Gio test end in 4 milliseconds.
GLib processing start...
GLib processing end in 21777 milliseconds.
```
It's like nothing now! 5500x FASTER then old GLib.method!

**Comment by terencode** [comment]
Thanks for caring for my HDD health but it's doing alright (S.M.A.R.T  ok). ;)

**Comment by konkor** [comment]
I can't see any problems to merge this version to master...

**Comment by terencode** [comment]
@konkor you can close this now :)

**Comment by konkor** [comment]
OK, GIO version (v9) is in extensions.gnome.org and merged to master. So it's look like closed.
