### ISSUE TITLE
Extension mode doesn't work in Wayland.

### ISSUE THREAD

**Issue by laichiaheng** [konkor/cpufreq#151]
It becomes window mode.

**Comment by konkor** [comment]
Yeah, it's disabled for Wayland. Wayland doesn't support window positioning, so it's impossible to open the app at a mouse pointer. I don't think it's a big deal...

**Comment by konkor** [comment]
@laichiaheng Do you mean the extension doesn't work on 3.38 except for the application?

**Comment by laichiaheng** [comment]
@konkor No, I haven't tried 3.38 yet.

**Comment by malomehi** [comment]
I can confirm the extension stopped working on 3.38 on Debian testing.

**Comment by jens-st** [comment]
> I can confirm the extension stopped working on 3.38 on Debian testing.

Me too, I'm using Debian Sid.
GNOME Shell 3.38.0

**Comment by konkor** [comment]
Please try github master branch, it should work on the GNOME Shell 3.38. I'll push it on extensions repo when I get enough testing results. Thanks.

**Comment by malomehi** [comment]
It works from the master branch. Thanks.
