### ISSUE TITLE
OSPower critical state

### ISSUE THREAD

**Issue by AliDeym** [konkor/cpufreq#153]
Whenever my OS boots, I receive an OSPower critical state notification, with a button saying "More Info". When I click on the button, gjs-console crashes. The app works perfectly fine. However, there is one big issue with the CPU Frequency on the task bar that is being displayed RED. When I open the extension though, inside the extension the health/status is yellow and not red.
```
OS: Ubuntu 20.04 LTS
Kernel: 5.4.0-48-generic
Driver: Intel PState
CPU: i5-9300H
```

**Comment by konkor** [comment]
@AliDeym Looks like your cooling needs cleaning... You can take a look at #50

**Comment by ngoquang2708** [comment]
I have this too. How to turn off notifications? I intent to throttle my laptop before but there is no notification until recent update.

**Comment by alperyilmaz** [comment]
I started getting this notification yesterday after I reboot and icon stayed red no matter I did. 

And today there were many packages upgraded after which cpufreq is stuck at "3.77GHz" as speed and does not change whatever I change in settings. Probably it's not related to extension itself, some change in system caused the problem, but I don't know where to start.
```
OS: Pop OS 20.04 LTS
Kernel: 5.4.0-7642-generic
CPU: i7-9750H
```

**Comment by ClawZilla** [comment]
I've been recently getting spammed with "System Overload" notifications :
![Screenshot from 2020-10-13 13-42-38](https://user-images.githubusercontent.com/35773324/95862016-30178e80-0d5a-11eb-8731-519f17649dd3.png)

**Comment by Pioxis** [comment]
I have the same issue. I have a new device. Clean everywhere and it's not problem with my device. Something is wrong with that extension after some updates.

**Comment by battata** [comment]
Same issue.
My desktop is running folding@home si the overload is intended.
I need a way to turn the notifications off.
Thanks.

**Comment by tom--pollard** [comment]
+1 there needs to be a way to stop the spamming

**Comment by AliDeym** [comment]
Either it is caused by a recent package update from Gnome/Gnome shell extensions, or by the latest update of CPUFREQ. Is there any way we can capture the logs of the extension? My gjs-console crashes every time I try to open the notification.

**Comment by wonx** [comment]
I am still experiencing this issue, even after updating cpufreq to the last version. Any ideas?

**Comment by alperyilmaz** [comment]
I updated the extension and still having a problem. I don't receive spam notifications anymore, instead the status bar icon is always red as if there's throttling but there's no overload in the system..

![Screenshot_2020-11-22_22-03-51](https://user-images.githubusercontent.com/410615/99914522-049ba280-2d0f-11eb-8abd-a9858871eae5.png)

**Comment by Pioxis** [comment]
@konkor I still have the same problem like both guys above me after upgrade to version from master branch.

**Comment by konkor** [comment]
I thought GLib notifications is only issue. It's nice to see when your system under heavy load.

BTW you can disable colors for the gnome extension in the preferences or you can change the colors so.

**Comment by Pioxis** [comment]
> I thought GLib notifications is only issue. It's nice to see when your system under heavy load.
> 
> BTW you can disable colors for the gnome extension in the preferences or you can change the colors so.

But I have that notification when my computer is standing on my desk and doing nothing 😄 
It's problem because that notification is not true about overload or something. Something is wrong but I don't know what.
![Zrzut ekranu z 2020-11-23 11-44-21](https://user-images.githubusercontent.com/12051229/99953399-7c0a1a00-2d81-11eb-870f-ecaec432cdfe.png)
Here is my specs of my PC. 
And here is information from your extension: 
![Zrzut ekranu z 2020-11-23 11-46-59](https://user-images.githubusercontent.com/12051229/99953557-b2e03000-2d81-11eb-9c1f-6d27cfa5e928.png)

**Comment by Pioxis** [comment]
Colour of that is not a problem. Problem is in the not true information.

**Comment by konkor** [comment]
@Pioxis You have notifications bcs you have thermal throttling. Can you tell what info is not correct also?

**Comment by Pioxis** [comment]
> @Pioxis You have notifications bcs you have thermal throttling. Can you tell what info is not correct also?

Before update I never get that notification and never get thermal throttling. On my second OS (windows) I don't have any issues of that. My PC on Ubuntu is working fine with normal temperatures. Not going down with performance. I have only notification without changes about performance or temperature.

I think this information is incorrect.

**Comment by konkor** [comment]
@Pioxis Unfortunally, the most OSs don't display information about TT at all. Usually, you could notice it from some system lag to a significant drop of performance while affected cores cooling. But it could be real HW issues after not long time. So it should be fixed via cleaning of the cooling system, or/and replacing thermal paste or even fans.

BTW, The information about TT is provided by Linux kernel itself.

Regards

**Comment by DoiChris** [comment]
Closed? But what is the solution. I get this on both installed PC's.

**Comment by aravindev** [comment]
Go to settings (top right button):
![image](https://user-images.githubusercontent.com/2952182/209973824-596a7395-109d-40c8-a933-3e622fac9f3a.png)

and, disable `notifications` in the preferences dialog box:

![image](https://user-images.githubusercontent.com/2952182/209973931-3c34b6fc-7a89-40dd-b193-e3ef57d1e186.png)

**Comment by nulf** [comment]
Thanks @aravindev ! I have a few month old system76 laptop and it doesn't really run hot, so the notifications was my biggest problem :+1:
