### ISSUE TITLE
The extension simply doesn't work. Pop OS 20.04

### ISSUE THREAD

**Issue by Cervoxx** [konkor/cpufreq#154]
System Specs: https://i.imgur.com/wyiWLR3.png

Journalctl logs from running `sudo journalctl |grep cpufreq`: https://paste.ubuntu.com/p/7B4cGScngT/

Trying to run the install command manually outputs this: https://paste.ubuntu.com/p/pdsbCc93Ry/

On first install of the extension, I'm able to see [this window](https://extensions.gnome.org/extension-data/screenshots/screenshot_1082_8G7gjUt.png), but upon a reboot it just doesn't show up anymore. No matter how many times I press the extension button. Going into `/home/cervox/.local/share/gnome-shell/extensions/cpufreq@konkor` and doing `./cpufreq-application` yields no window or output either. 

The preferences window works, but no value i change in there makes any difference. 

I've installed through the gnome extensions website.

(I hope I wrote this well, if there is anything else I need to expose feel free to ask.)

**Comment by konkor** [comment]
@Cervoxx Actually, i don't know why it's so. But I know Pop!OS has own power-management service and extension for it. I don't think it would be good idea to use them together with this app at least now. I'm sorry.
