### ISSUE TITLE
Sometimes the indicator doesn't display the value.

### ISSUE THREAD

**Issue by laichiaheng** [konkor/cpufreq#155]
Gnome 3.38.1
Kernel: 5.9.1-3-MANJARO

![2020-10-28 08-18-21 的螢幕擷圖](https://user-images.githubusercontent.com/9532105/97375655-53b00c80-18f6-11eb-8029-fd0fc9b6f87a.png)

**Comment by debian-user-france1** [comment]
sometimes (me on newest update, today a new update, I didn't updated this version - sometimes is the power indicator freezing, but still normaly running, only the value isn't updating

**Comment by konkor** [comment]
Yeah, it's possible to don't update values when system is busy by other tasks. It's how it'd designed.

Also you need to restart a computer after update sometimes. I didn't want to put extra code for checking such updates on each extension activating...

**Comment by debian-user-france1** [comment]
Yes... Ok... But sometimes it freeze - no updates...
But... It is ok... I only sayd it

**Comment by debian-user-france1** [comment]
We can close that, because he don't give enough info and my question is now ... Don't know how to say...
