### ISSUE TITLE
Please let us disable "OSPower critical state" desktop notification

### ISSUE THREAD

**Issue by Saroumane** [konkor/cpufreq#156]
Please let us disable "OSPower critical state" desktop notification.

**Comment by ckjoris** [comment]
I agree - it should be possible to disable it.
In my case, with a low powered laptop, system overload happens just too often, but it doesnt matter to me.

**Comment by Saroumane** [comment]
Hello ckjoris,
If you don't mind compiling from source (I never tried for this repo) I think you can just edit cpufreq-service
https://github.com/konkor/cpufreq/blob/37f9bc6dd8c83a74a2e2ca9a47b44863094390c5/cpufreq-service
and comment out everything between lines 156-176.

**Comment by goosenphil** [comment]
> Hello ckjoris,
> If you don't mind compiling from source (I never tried for this repo) I think you can just edit cpufreq-service
> [`37f9bc6`/cpufreq-service](https://github.com/konkor/cpufreq/blob/37f9bc6dd8c83a74a2e2ca9a47b44863094390c5/cpufreq-service)
> and comment out everything between lines 156-171.


@Saroumane I can confirm that this fix works, you don't have to compile from source since it is written in javascript. In my case the extension was installed to ```~/.local/share/gnome-shell/extensions/cpufreq@konkor``` where you can find this exact file and perform modification you suggested. After modifying and reloading the extension, I can confirm that I no longer see this notification being spammed.

**Comment by Trapez** [comment]
Please remove this functionality. It is both meaningless and annoying.

**Comment by konkor** [comment]
I removed the System Overload from critical state notifications some time ago. Today I pushed new version to GNOME also. It will be available soon.
