### ISSUE TITLE
cpufreq?

### ISSUE THREAD

**Issue by debian-user-france1** [konkor/cpufreq#158]
cpufreq is managing cores, why is the extension not saying system ok?
![tmp-screenshot](https://user-images.githubusercontent.com/72965843/99178529-3e1f4d00-2714-11eb-972c-e13d432f45e2.png)

**Comment by PiotrDabrowskey** [comment]
There's an explanation in FAQ, section "IRQBALANCE DETECTED". There is also a link to the original discussion on GitHub.

Link: https://konkor.github.io/cpufreq/faq/

**Comment by debian-user-france1** [comment]
Thanks much, good FAQ:)
So I close... Thank you. I saw already the faq but I was not in the correct page...
