### ISSUE TITLE
Ryzen 2500U governor

### ISSUE THREAD

**Issue by koroki** [konkor/cpufreq#159]
Since I change my laptop, I cannot change de governor with this extension. It is quite rare. The governor is changed when I set any of the power profile in its menu, but It is not changed when I set any option in the Governor menu. 

In fact, only two options appears in the governor menu, performance or schedutil. But setting any of them doesn't affect the cpus. I also checked the kernel options ( /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor ) and it is not changed. Only changes with the power profile menu ( Balanced = ondemand, powesaving = schedutil).

**Comment by konkor** [comment]
Some CPU governors could be not installed or not supported by your HW or kernel. You can try load kernel modules for CPU governing by:

```sh
sudo modprobe -v cpufreq_powersave
### or/and
sudo modprobe -v cpufreq_conservative
```
etc

Also check your system messages while you are changing settings by

```sh
sudo journalctl -f
### press Ctrl-c to stop monitoring
```
Good luck!
