### ISSUE TITLE
[Gio] Not properly closing file after reading the frequency

### ISSUE THREAD

**Issue by terencode** [konkor/cpufreq#16]
It seems it's not properly closing file after reading the frequency thus producing after running a while a complete crash of gnome-shell.

*Note: I translated some parts as it was written in french.*

```
Error:  Erreur lors de l'ouverture du fichier /sys/devices/system/cpu/cpu7/cpufreq/scaling_cur_freq Too much files opened
```

```
glibtop(c=1778): [ERROR] open (/proc/loadavg): Too much files opened
```

**Comment by konkor** [comment]
ty. it's fixed. Now other problem i have a memory leak. I made a benchmark_gio.sh with 100 000 cycles and i can see very big memory leaking. I'm going to irc channel to find out.
https://github.com/konkor/cpufreq/blob/gio/benchmark_gio.js

**Comment by RicardoEPRodrigues** [comment]
When the memory leak is fixed I can test it.

**Comment by konkor** [comment]
It seems like an gjs bug. gjs has a lot memory leaks :( 
But i found a workaround to this by using global file descriptors and Co for each CPU. I'm working on this.

**Comment by konkor** [comment]
OMG now benchmark's results looks like:
(100 cycles)
```
Gio start...
Gio test end in 0 milliseconds.
GLib processing start...
GLib processing end in 2150 milliseconds.
```
for NUMBER_OF_TEST_CYCLESx10 (1000 cycles)
```
Gio start...
Gio test end in 4 milliseconds.
GLib processing start...
GLib processing end in 21777 milliseconds.
```
It's like nothing now! 5500x FASTER then old GLib.Processing method!

**Comment by konkor** [comment]
RicardoEPRodrigues: U can test now ;)

**Comment by RicardoEPRodrigues** [comment]
How can I test the extension using the benchmarks?

**Comment by konkor** [comment]
Just run benchmark.js from terminal in extension dir 
from the gio branch archive https://github.com/konkor/cpufreq/archive/gio.zip
https://github.com/konkor/cpufreq/blob/gio/benchmark.js

**Comment by RicardoEPRodrigues** [comment]
Nice. These are the results.

I have a `Intel Core i7-6700HQ CPU @ 2.60GHz × 8`

## 100 cycles:

**Powersave**

    Gio start...
    Gio test end in 0 milliseconds.
    GLib processing start...
    GLib processing end in 1899 milliseconds.

**Performance + Turbo Boost**

    Gio start...
    Gio test end in 0 milliseconds.
    GLib processing start...
    GLib processing end in 1352 milliseconds.

## 1000 cycles:

**Powersave**

    Gio start...
    Gio test end in 2 milliseconds.
    GLib processing start...
    GLib processing end in 19149 milliseconds.

**Performance + Turbo Boost**

    Gio start...
    Gio test end in 2 milliseconds.
    GLib processing start...
    GLib processing end in 13791 milliseconds.

**Comment by konkor** [comment]
Looks amazing)

**Comment by konkor** [comment]
RicardoEPRodrigues So u can just replace the whole extension from gio branch. Here is not only benchmarks :)
I have got nice replays and help from irc.gnome.org #javascript (thanks to ptomato[m] and luke_nukem). They explained difference extensions and scripts without mainloop and much more...

**Comment by terencode** [comment]
Sounds good!

**Comment by RicardoEPRodrigues** [comment]
I'm using the gio branch now. 😃 

Regarding the GNOME. I think they should improve a lot on their documentation, it's really poor!

**Comment by konkor** [comment]
RicardoEPRodrigues Here is u're right... Tutorials for gjs (extensions, glib, gio, gtk, gnome-shell) are old and too small. I'm looking info everywhere to improve something...

**Comment by konkor** [comment]
Guys, if you'll find some problems with this version make me to know in few days before i'll merge this branch. Thank for ur helps!

**Comment by RicardoEPRodrigues** [comment]
I tried to follow tutorials to see if I could make an extension that added a button to the context menu of the dash board. The only way I could do it was to read the code from other extensions (that are not documented). I eventually gave up, I had more important things to do!

But is sad that many developers that try to create something in GNOME fail for lack of documentation.

Up until now I had no problem. I'll be using the extension everyday so if something happens I'll let you know.

**Comment by konkor** [comment]
I can't see any problems to merge this version to master... I think it's time to close this issue no huge open file handlers, no memory leaks...

**Comment by terencode** [comment]
@konkor I've been using the Gio branch for a week and I did not have any critical problems except sometimes, the active governor is different from the one selected... I think it could be solved with #13 .

**Comment by konkor** [comment]
@terencode Are you loading manually some governors modules every session? I can tell you the extension has never been added new governors dynamically it did can show current new governor without handling it. It's not bcs I’m lazy or something. It's hard to implement dynamic menu in JS for gnome-extension. When you are removing some items from the extension menu they are still present for some time until garbage collector destroy them. I can easy back the showing the current governor so by reloading all available on a click... Maybe I should move them to some custom widget or gtk listbox for example but i don't know how it'd look like at all and on different themes and versions of the gnome shell.

**Comment by terencode** [comment]
@konkor I was loading the powersave governor manually *by laziness* to add a rule to automatically enabling it at boot but I guess I should do it...
I did not know it was hard so because there is no real need to do that, I would suggest to not mind about it as you can just use [gnome-shell extension reloader](https://extensions.gnome.org/extension/1137/gnome-shell-extension-reloader/) or even simply restart gnome-shell if still on Xorg.
