### ISSUE TITLE
Frequency Boost not changing when selecting a custom active profile

### ISSUE THREAD

**Issue by PiotrDabrowskey** [konkor/cpufreq#160]
Frequency Boost does not change when I change the active profile to a custom one. I've created a custom profile, basically selected "Balanced", turned on the Frequency Boost and saved the profile as "Balanced + turbo". When I select "Balanced" and then "Balanced + turbo", Frequency Boost doesn't change to enabled.

When I select the same profile once again (second time), it works as expected, enabling the boost - so this works for me as a workaround.

See the gif below presenting the issue. Base frequency of my CPU is 2.20 GHz and you can notice that when I change the active profile for the first time, the frequency jumps for a moment to a higher level, indicating that the turbo frequency is enabled for a second or so, but then it goes back to the base frequency. I'm not sure if it's part of the bug or it's just an expected behavior of this extension while changing the profile.

I use:
cpufreq@konkor - Version: 44
Ubuntu 20.04.1 LTS
GNOME Shell 3.36.4

![Peek 2020-11-18 12-19](https://user-images.githubusercontent.com/9080823/99524751-302e2e00-2999-11eb-80be-0e7950e97785.gif)

**Comment by konkor** [comment]
Luck of information. Unable to reproduce. Sorry
