### ISSUE TITLE
Monitoring intervall setting ignored

### ISSUE THREAD

**Issue by emmertf** [konkor/cpufreq#161]
Dear devs,

I found, that the monitoring intervall setting gets ignored in the current version (unless it's 0, that still deactivates monitoring completely).
Since I don't need to see my frequency every second I wanted to change it to 5000ms to prevent unnecessary UI updates (and thus battery usage). This was working in older versions.

**Workaround:**
Changing the [hardcoded default value of monitor_timeout in cpufreq-service](https://github.com/konkor/cpufreq/blob/f7cfe8f0d82e709e041b4877281b793f7d6fadaf/cpufreq-service#L33) to the desired value.

Thanks in advance for fixing this.

**Comment by konkor** [comment]
@konkor Thank you for this report! It was removed by accident after merging some developing branch... heh
