### ISSUE TITLE
[Theme] Change GNOME Extension theme to light/dark acc to system theme?

### ISSUE THREAD

**Issue by shanmukhateja** [konkor/cpufreq#162]
The extension should toggle between light and dark themes acc. to system theme. In my case, my laptop is configured to turn on dark theme at 7PM and revert back to light theme at 7AM so all GNOME apps switch themes accordingly.

This isn't a must-have feature but it would be an QoL improvement for people. I'm willing to send a PR once I wrap my head around the source code.

Thoughts?

**Comment by konkor** [comment]
@shanmukhateja I will take a look at that feature in other GNOME/Gtk apps. Thanks!

**Comment by konkor** [comment]
@shanmukhateja Are you using some sort of extension for this feature? Or you just want to implement such feature directly in this app?

**Comment by shanmukhateja** [comment]
Hi, I use the following extension for the feature:

(https://gitlab.com/rmnvgr/nightthemeswitcher-gnome-shell-extension/)[https://gitlab.com/rmnvgr/nightthemeswitcher-gnome-shell-extension/]

It changes GNOME Shell theme at time intervals.

**Comment by konkor** [comment]
@shanmukhateja All works. Just turn off **Dark Theme** forcing in the Preferences.

**Comment by shanmukhateja** [comment]
@konkor that does it. Thanks :)
