### ISSUE TITLE
Usage of object.actor is deprecated for Cpufreq

### ISSUE THREAD

**Issue by shanmukhateja** [konkor/cpufreq#163]
I see this stack trace on my journalctl output from time-to-time. After some digging, I realised it was this plugin causing this to appear. 

Here's the full stack trace I receive:

```
Usage of object.actor is deprecated for Cpufreq
        get@resource:///org/gnome/shell/ui/environment.js:316:29
        _init@/home/suryateja/.local/share/gnome-shell/extensions/cpufreq@konkor/extension.js:129:5
        wrapper@resource:///org/gnome/gjs/modules/script/_legacy.js:82:27
        enable@/home/suryateja/.local/share/gnome-shell/extensions/cpufreq@konkor/extension.js:483:13
        _callExtensionEnable@resource:///org/gnome/shell/ui/extensionSystem.js:167:32
        loadExtension@resource:///org/gnome/shell/ui/extensionSystem.js:348:26
        _loadExtensions/<@resource:///org/gnome/shell/ui/extensionSystem.js:586:18
        collectFromDatadirs@resource:///org/gnome/shell/misc/fileUtils.js:27:28
        _loadExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:565:19
        _enableAllExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:595:18
        _sessionUpdated@resource:///org/gnome/shell/ui/extensionSystem.js:626:18
        init@resource:///org/gnome/shell/ui/extensionSystem.js:56:14
        _initializeUI@resource:///org/gnome/shell/ui/main.js:269:22
        start@resource:///org/gnome/shell/ui/main.js:159:5
        @<main>:1:47

```

**Environment:**

**OS:** Manjaro Linux

**GNOME version:** 3.38.2

**Window System:** Wayland

**Comment by konkor** [comment]
@shanmukhateja I don't know how to fix this warning yet. The new versions of GNOME Shell made `this.actor` like main class but the extensions need that property at least like a reference to the main Actor Class for older versions of GShell.

BTW, I think they should remove this warning because it's pretty dump it's just looking for actor property without checking definition of it...

**Comment by shanmukhateja** [comment]
@konkor thanks for letting me know. I didn't understand what you said. I see this stack trace on journalctl often and I thought of letting upstream know about it.

**Comment by shanmukhateja** [comment]
@konkor I found this tidbit regarding `actor`. Could this help?

[link](https://gitlab.gnome.org/GNOME/gnome-shell/-/blob/master/HACKING.md#actor-deprecated-and-_delegate)

**Comment by shanmukhateja** [comment]
Hi, I also found this git commit that shows a fix.

[https://github.com/RaphaelRochet/arch-update/commit/69201d5c59efe058610d52e6e671e1236f6de014](https://github.com/RaphaelRochet/arch-update/commit/69201d5c59efe058610d52e6e671e1236f6de014)

All calls to `this.actor.function_name(args)` is replaced by `this.function_name(args)`.

Maybe we could update code to check if GNOME version >= 3.34, then not use it?

**Comment by konkor** [comment]
@shanmukhateja Thank you for your efforts! But the message in system logs is coming directly from the GNOME Shell's **actor** property https://gitlab.gnome.org/GNOME/gnome-shell/-/blob/master/js/ui/environment.js#L313 

It's not critical error it's just an annoying warning for developers. But I should keep that property for older versions of GNOME Shell and it could be fixed when GNOME Shell developers remove it.

Maybe I will try to override that property after checking GNOME Shell versions. Just ignore it for now.
