### ISSUE TITLE
IRQLFREQ disable or not?

### ISSUE THREAD

**Issue by MarceloMachadoxD** [konkor/cpufreq#165]
the extension shows an advice about the irqlfreq is active by default at ubuntu 20.10, why i should to disable it?

------------------------------------------------------------------------------------------------------------------
a tip who wants disable from https://linuxmusicians.com/viewtopic.php?t=19750

Check the status of the irqbalance daemon.
~]# systemctl status irqbalance
irqbalance.service - irqbalance daemon
Loaded: loaded (/usr/lib/systemd/system/irqbalance.service; enabled)
Active: active (running) …

If the irqbalance daemon is running, stop it.
~]# systemctl stop irqbalance
Ensure that irqbalance does not restart on boot.
~]# systemctl disable irqbalance

---------
or just apt-get remove irqlbalance

**Comment by konkor** [comment]
@MarceloMachadoxD There is a discussion about it #48 You can disable or remove irqbalance for desktop usage. New Linux kernels do balancing itself if there is need.
