### ISSUE TITLE
[Gnome] Add menu for top bar

### ISSUE THREAD

**Issue by thelazy6** [konkor/cpufreq#166]
Suggestion: For the gnome-shell extension, transform the frequency indicator into a little menu to perform basic tasks without starting the main window. Would also increase usability on tablets/convertibles (as touch-hitting the indicator currently does nothing).
Suggested menu items (correspond with controls in main menu):
- Power profile (as configured in main window)
- CPU governor (optional, as in main window)
- Frequency boost switch
- Open main window

**Comment by konkor** [comment]
@thelazy6 It's like it was about 2 years ago. We decided to port main app/menu to Gtk bcs it solves a lot issues like a possibility to use the app on other desktops, less dependencies from GNOME Shell constant changes, less bags, less resources etc.
