### ISSUE TITLE
Install Freezes for Additional User(s)

### ISSUE THREAD

**Issue by Francewhoa** [konkor/cpufreq#17]
Hi there :) 

I love cpufreq :) It is easy to use. Lots of features. Lightweight. It remembers your settings. More secure because its code is publicly available for review on github. Yay :)

This ticket is for reporting a bug when the user tries to install cpufreq for additional Debian user(s). When doing so the Gnome session freezes and cpufreq is unusable for those additional Debian user(s).

### Steps to reproduce
1. Using Debian 8 Jessie, using GNOME 3.14.1, run the following command to install "cpufrequtils" package
      `sudo apt-get install cpufrequtils`
1. Double check that that Debian user has full "Administrator" access. Also known as "Root". "Desktop user" access only would not work. In this example, let us call that user the "FIRST Debian User".
1. Using Firefox 45.8 go to https://extensions.gnome.org/extension/1082/cpufreq/ 
1. Click on the "OFF/ON" toggle button to turn ON "cpufreq" extension. By the way, on April 16, 2017 we searched which version of "cpufreq" is on extensions.gnome.org but found no result.
1. When prompted by extensions.gnome.org allow all permissions
1. The cpufreq trail icon will show into the top toolbar. Left click on it. Select "Install...". 
1. When prompted by cpufreq Install allow all permissions. This will automatically [fix those executing bit](https://github.com/konkor/cpufreq/blob/master/README.md#you-need-fix-executing-bit-after-installation-to-able-to-change-governors), 
1. In the "cpufreq" tray menu, the "Install..." option is now replace by "Preferences". The settings are remembered when changing the CPU speed. So far so good. It works for the "FIRST Debian User".
1. Now log-out that "FIRST Debian User"
1. Log-in the "SECOND Debian User". Redo all the same steps as above.
1. When the "SECOND Debian User" go to https://extensions.gnome.org/extension/1082/cpufreq/ then click on the "OFF/ON" toggle button to turn ON "cpufreq" extension. The Gnome session freeze. The mouse is still working but everything else is frozen. This is the issue.
1. To fix this
   1. Delete the "konkor.cpufreq.policy" file. Which is located at
`/usr/share/polkit-1/actions/konkor.cpufreq.policy`

   1. Delete the "cpufreq@konkor" folder for the "SECOND Debian User". Which is located at
`~/.local/share/gnome-shell/extensions/cpufreq@konkor`

1. Now the user is able to log-in the "SECOND Debian User" but the "cpufreq" extension is no longer available. To change the CPU speed the user needs to log-in the "FIRST Debian User".

### Expected result 
The user would be able to use https://extensions.gnome.org/extension/1082/cpufreq/ to install "cpufreq" extension for both the "FIRST Debian User" and the "SECOND Debian User". And the user would be able to change the CPU speed with either the "FIRST Debian User" and the "SECOND Debian User".

### Potential cause of that issue
* Somehow that issue seems to be related to the file located at `/usr/share/polkit-1/actions/konkor.cpufreq.policy`. Within that `konkor.cpufreq.policy` file the path seems to be hard coded to target the "FIRST Debian User". Could that be related to that issue? I mean this line that starts with: `<annotate key="org.freedesktop.policykit.exe.path">/home/[FIRST-DEBIAN-USER]/.local/`
Where [FIRST-DEBIAN-USER] is the "FIRST Debian User"
* Maybe the "cpufreq" files hosted on extensions.gnome.org are outdated compare to the files hosted on github?

Cheers,

Francewhoa

**Comment by konkor** [comment]
Ohh, ty for ur report. It sounds like I have to move 'cpufreqctl' to /usr/local/bin and to change that path in police file. I'll try to fix this today.

**Comment by Francewhoa** [comment]
Thanks konkor :) After you are done, I will be happy to contribute testing and documentation if needed.

**Comment by Francewhoa** [comment]
konkor :) As you know after I tried to install cpufreq for the "SECOND Debian User" the Gnome session froze. So I forced rebooting using the computer hardware button. After the reboot, when I tried to log-in back into Gnome it always freezes. So in other words I locked myself out of Gnome. D'Oh :( It didn't broke Gnome or Linux. It just that that Gnome session always freezes. In the unlikely event that that challenge happens to you too, the following command allowed me to manually log-out the frozen Gnome session. 
1. Press CTRL+ALT+F2 to enter the command line prompt
1. Run the following command to manually kill that frozen Gnome session
`sudo pkill -KILL -u [SECOND-DEBIAN-USERNAME]`
Where "[SECOND-DEBIAN-USERNAME]" is obviously the Debian username.
If the command above is not working the following might work
`sudo pkill -u [SECOND-DEBIAN-USERNAME]`
1. After that I was able to use the fix described in [my first post above](https://github.com/konkor/cpufreq/issues/17#issue-222059822)

**Comment by konkor** [comment]
@Francewhoa: Heh, It's working now for all users. But the extension needs a version control system for the global `cpufreqctl` now.
PS: You are the 1st user with several shell's users with this extension installed) LoL

**Comment by Francewhoa** [comment]
Giant thank you konkor :) I'll try to test it sometime this week. I'll post the result here.

**Comment by Francewhoa** [comment]
@konkor :) My testing is in progress. I posted a suggestion for your review and consideration at  https://github.com/konkor/cpufreq/commit/3856fb48f50b8ddebe58ef66fb4d86d6f19bff5c#commitcomment-21812031

About the version number

**Comment by Francewhoa** [comment]
@konkor :) I'm done. Here are the test results.

### Steps to reproduce
1. Go to https://extensions.gnome.org/local/
     1. Log-in
     1. Click the toggle button to turn OFF [that already installed cpufreq version 9 from April 16, 2017](https://github.com/konkor/cpufreq/issues/17#issue-222059822)
     1. Click the red uninstall button to remove that extension
     1. Somehow `konkor.cpufreq.policy` file was not remove. Maybe that's normal? Anyway I manually deleted it. I'm referring to the file that was located at `/usr/share/polkit-1/actions/konkor.cpufreq.policy`

1. Reboot computer. That's not really needed. But that's for extra fresh start to rule out funny stuff with caches and memory.

1. Using "Tweak Tool", navigate to "Extension > Install Shell Extension".
     1. Manually install [that cpufreq version from April 17, 2017](https://github.com/konkor/cpufreq/issues/17#issuecomment-294524836) zip file downloaded from GitHub.
1. Reboot computer. "Tweak Tool" requires only a log-out. But I rebooted to reduce risk of funny stuff again.
1. The good news is the extension files seems to be install correctly under this folder `~/.local/share/gnome-shell/extensions/cpufreq@konkor/`

1. Using "Tweak Tool" again, click on the toggle button to turn ON Cpufreq extension.
     1. Notice that the configuration button is not showing. Expected result is that it should. Find [that screenshot](https://cloud.githubusercontent.com/assets/119942/25162960/78012bd2-247b-11e7-80e3-f287b8c7e6de.png) to clarify the issue location. 
     1. Also notice that the Cpufreq icon and drop down menu are not showing in the system tray. I mean the Debian top toolbar. So the user can't use Cpufreq. The user can't access the Cpufreq Install menu option either. Expected result is both the Cpufreq icon and drop down menu should be display in the system tray.
     1. No file was automatically install at `/usr/bin/cpufreqctl/` is that normal?

1. Close "Tweak Tool" window
1. Wait roughly 5 minutes. Open "Tweak Tool" again. Notice that the Cpufreq extension was somehow automatically turn OFF. Also Cpufreq row returns this error message: `Error loading extension` Find [that screenshot to clarify.](https://cloud.githubusercontent.com/assets/119942/25162967/86b6c52e-247b-11e7-984c-fbb142a3a2cf.png)
1. Go to https://extensions.gnome.org/local/ it also return an message: `ERROR` Find [that screenshot to clarify](https://cloud.githubusercontent.com/assets/119942/25162979/97188cea-247b-11e7-821c-558ce861c3c0.png). Expected result is those error messages should not be return.
1. Log-out the GNOME session. Wait 2 minutes. Try to log-in again. GNOME freezes. The user is locked out of GNOME. The freezes seems to be random. And seems to be related to heavier CPU use when the freezes occurs. Deleting all Cpufreq files resolve that issue. 

The good news is during the extension initial automated installation, all the extensions files seems to be installed properly. The permissions seems ok too. The bad news is there is no celebration yet as it's not yet working.

Using Cpufreq 9 from April 17, 2017, Debian 8 Jessie, GNOME 3.14.1


### Things I tried
* Manually change the permissions on all the extension files to 775. Just for testing. In case it was a permission error. But no joy.
* Manually copy the file to `/usr/bin/cpufreqctl/` But no joy either.

### Screenshots
![screenshot_001](https://cloud.githubusercontent.com/assets/119942/25162960/78012bd2-247b-11e7-80e3-f287b8c7e6de.png)
![screenshot_002](https://cloud.githubusercontent.com/assets/119942/25162967/86b6c52e-247b-11e7-984c-fbb142a3a2cf.png)
![screenshot_003](https://cloud.githubusercontent.com/assets/119942/25162979/97188cea-247b-11e7-821c-558ce861c3c0.png)

**Comment by konkor** [comment]
Heh. '9. Go to https://extensions.gnome.org/local/ it also return an message: ERROR Find that screenshot to clarify. Expected result is those error messages should not be return.'
Select broken extension and press 'Report Bug'. You'll see this Error so. And send this Error message through the extension server.
It's weird. I have tested on 2 machines and all fine. But I just copy Extension files through Nautilus and has only one issue with second user and metadata.json file bcs it doesn't have read access for other users. So I extracted this file again.
I'll try to reproduce ur steps through the tweak tool.
TY for ur afforts and time.

**Comment by konkor** [comment]
`Somehow konkor.cpufreq.policy file was not remove. Maybe that's normal? Anyway I manually deleted it. I'm referring to the file that was located at /usr/share/polkit-1/actions/konkor.cpufreq.policy`
Yes it's OK bcs It's a hack. You don't need to remove this file manually but it's not a problem. So you wanted `fresh` install.

**Comment by konkor** [comment]
I did complete uninstall and removed installed by extension files through terminal:
```
# rm /usr/share/polkit-1/actions/konkor.cpufreq.policy 
# rm /usr/bin/cpufreqctl 
```
Now I'm going to 2nd step. REBOOTING )) See u later

**Comment by konkor** [comment]
OK I downloaded latest archive from https://github.com/konkor/cpufreq/archive/master.zip.
And I have this error too after installing through the gnome-tweak-tool:
```
Automatically detected errors:

  GLib.SpawnError: Failed to execute child process &quot;&#x2F;home&#x2F;kapa&#x2F;.local&#x2F;share&#x2F;gnome-shell&#x2F;extensions&#x2F;cpufreq@konkor&#x2F;cpufreqctl&quot; (Permission denied)
```
So 'gnome-tweak-tool' is removing all executions bits. To fix this i fixed this in the terminal:
```
$ chmod +x ~/.local/share/gnome-shell/extensions/cpufreq@konkor/cpufreqctl
```
And restarted gnome-shell by pressing Alt-F2 and entering 'r' command. So extension loaded correctly.
Now i have to select `Install...` options in the extension's popup menu. Enter password and it's done.

So if you are installing through the 'gnome-tweak-tool' you have to fix execution bit for `~/.local/share/gnome-shell/extensions/cpufreq@konkor/cpufreqctl` script!!!

**Comment by konkor** [comment]
Now I'm going to fix README file.

**Comment by konkor** [comment]
@Francewhoa: I'm doing updates through gui without any uninstalling if the extension was already installed/enabled. i will try to reproduce my steps:
1. Download a new archive https://github.com/konkor/cpufreq/archive/master.zip
2. Right click in Nautilus on the archive `cpufreq-master.zip` and select 'Extract Here'
3. Go to extracted folder `cpufreq-master`, select all and copy to the ~/.local/share/gnome-shell/extensions/cpufreq@konkor/ folder.
4. Restart gnome-shell by pressing `Alt-F2 + r`
5. Done.

PS: You don't need to fix execution bit if you are installing manually or from extensions.gnome.org

**Comment by Francewhoa** [comment]
Thanks @Konkor for the updated extension :) Indeed most users will install Cpufreq using extensions.gnome.org But it's wise that you added a note into the extension README file about if they install using `gnome-tweak-tool`/"Tweak Tool" that they need to manually fix the executions bits in cpufreqctl.

I learned something new about `gnome-tweak-tool`. It's able to run in debugging mode `--debug`. I'll use that for future bug report. It's useful and faster to narrow down the source of error with that information.

I tried the updated instructions in that [README](https://github.com/konkor/cpufreq/blob/master/README.md#from-source-zip-archive) file. But GNOME freezes at the step **highlighted in bold below** when the user enter 'r' command in 'Alt-F2' prompt. GNOME also freeze if the user log-out GNOME session then try to log-in back into GNOME.  Deleting all Cpufreq file resolved that bug.

### Steps to reproduce

> Download zip archive from github page. Run _gnome-tweak-tool_ go to extensions tab, click _Install Shell Extension_ from drive and select _master.zip_. Restart Gnome shell by pressing Alt-F2 and entering 'r'. **<=== Gnome freezes at this steps.**
> 
> ```
> $wget https://github.com/konkor/cpufreq/archive/master.zip
> $gnome-tweak-tool # Select 'Install Shell Extension' button on the Extensions Tab.
> $chmod +x ~/.local/share/gnome-shell/extensions/cpufreq@konkor/cpufreqctl
> ```
> Now close gnome-tweak-tool and restart gnome-shell Log out or just enter 'r' command in 'Alt-F2' promt.
> 
> ```
> $gnome-tweak-tool # Turn on the extension.
> cpufreq extension => ⚠ Install...
> ```

**Comment by Francewhoa** [comment]
I also tried [that other installation method](https://github.com/konkor/cpufreq/issues/17#issuecomment-295134059) using `gnome-tweak-tool`. But it returned the same error message below. So the user is not able to click that toggle to ON to activate Cpufreq: 
![screenshot_002](https://cloud.githubusercontent.com/assets/119942/25162967/86b6c52e-247b-11e7-984c-fbb142a3a2cf.png)

**Comment by Francewhoa** [comment]
@konkor :) About that other install method [From git source](https://github.com/konkor/cpufreq/blob/master/README.md#from-git-source). When user run step 3 it return an error message.

### Steps to reproduce
1. `git clone https://github.com/konkor/cpufreq`
1. `cd cpufreq`
1. `unzip cpufreq-master.zip`
     At step 3 above Terminal returns this error message:

     > unzip:  cannot find or open cpufreq-master.zip, cpufreq-master.zip.zip or cpufreq-master.zip.ZIP.

It seems that `git clone https://github.com/konkor/cpufreq` creates a cpufreq directory will all files already extracted in it. As follow:
```
~/cpufreq
~/cpufreq/benchmark.js
~/cpufreq/benchmark_gio.js
~/cpufreq/convenience.js
~/cpufreq/cpufreqctl
~/cpufreq/data
~/cpufreq/extension.js
~/cpufreq/konkor.cpufreq.policy
~/cpufreq/metadata.json
~/cpufreq/README.md
~/cpufreq/schemas
~/cpufreq/.git
~/cpufreq/.gitignore
```

So there is no `cpufreq-master.zip` archive for unzip to extract

**Comment by Francewhoa** [comment]
@konkor :) Good news. The following worked for both one GNOME user and multiple GNOME users. Awesome :) :) :100:  :+1:  :1st_place_medal: 

 It's inspired from your instructions method with [From git source](https://github.com/konkor/cpufreq/blob/master/README.md#from-git-source). Except I skipped two commands. Here are the instructions that worked for me:

### From git source
```
git clone https://github.com/konkor/cpufreq
cd cpufreq

mkdir -p ~/.local/share/gnome-shell/extensions/cpufreq@konkor
cp -r * ~/.local/share/gnome-shell/extensions/cpufreq@konkor/
chmod 0755 ~/.local/share/gnome-shell/extensions/cpufreq@konkor/cpufreqctl

sudo ~/.local/share/gnome-shell/extensions/cpufreq@konkor/cpufreqctl install
```

Notice that in the updated instructions above the following two lines were remove:
~~unzip cpufreq-master.zip~~
~~cd cpufreq-master/~~

It seems that running the extension `Install` script via git source and Terminal works. But the extension `Install` script via `gnome-tweak-tool` does not work. Maybe somehow a previously already ran `Install` script from an older version of Cpufreq was interfering? Maybe it was cached or something spooky like that.

**Comment by Francewhoa** [comment]
Closing per [that comment](https://github.com/konkor/cpufreq/issues/17#issuecomment-295501891). Thanks @konkor :)
