### ISSUE TITLE
Add a way to disable 'SYSTEM OVERLOAD' notification

### ISSUE THREAD

**Issue by smaug----** [konkor/cpufreq#175]
'SYSTEM OVERLOAD' isn't particularly useful. One gets that always when building some larger project.

**Comment by konkor** [comment]
@smaug---- There is an option `Notifications` in the preferences you can turn off/on as you like.

**Comment by smaug----** [comment]
Can't see such.  There are General, Monitor and Power Events tabs in preferences, and none of those have anything about notifications. Perhaps https://extensions.gnome.org/ is offering me some older version.

**Comment by konkor** [comment]
@smaug---- it's on the General -> System -> Notifications

![Screenshot from 2021-05-16 23-51-58](https://user-images.githubusercontent.com/1944781/118412396-57dd2500-b6a2-11eb-8996-6442cec7f492.png)

**Comment by smaug----** [comment]
Nope. I have only "Remember settings". Trying to find up-to-date extension for Gnome.
Thanks.

**Comment by smaug----** [comment]
...and the version in https://extensions.gnome.org/extension/1082/cpufreq/ isn't compatible with fc33 :/

**Comment by konkor** [comment]
@smaug---- Looks like you have a global installed previous version. You can try restart PC after update if it doesn't help just uninstall it before installing the new version. Also you could install it globally as previous version. Sorry for inconvenience.

**Comment by smaug----** [comment]
Perfect, thanks. Now it works and so far no notifications.

**Comment by konkor** [comment]
I'm glad it works for you! Good luck!

**Comment by konkor** [comment]
Heh. Looks like there is a bug with this option saving (#177) I'm fixing it right now.
