### ISSUE TITLE
autogen is stuck

### ISSUE THREAD

**Issue by mh-cbon** [konkor/cpufreq#176]
hi,

not sure what is going on, but autogen is stuck checking how to print strings :/

```sh
[mh-cbon@localhost cpufreq] $ sh ./autogen.sh && make && make zip-file
/usr/bin/gnome-autogen.sh
***Warning*** PKG_NAME is deprecated, you may remove it from autogen.sh
checking for automake >= 1.11.2...
  testing automake... found 1.16.2
checking for autoreconf >= 2.53...
  testing autoreconf... found 2.69
**Warning**: I am going to run `configure' with no arguments.
If you wish to pass any to it, please specify them on the
`./autogen.sh' command line.

Processing ./configure.ac
Running autoreconf...
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force --warnings=no-portability 
autoreconf: configure.ac: tracing
autoreconf: running: libtoolize --copy --force
libtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, '.'.
libtoolize: copying file './ltmain.sh'
libtoolize: Consider adding 'AC_CONFIG_MACRO_DIRS([m4])' to configure.ac,
libtoolize: and rerunning libtoolize and aclocal.
libtoolize: Consider adding '-I m4' to ACLOCAL_AMFLAGS in Makefile.am.
autoreconf: running: /usr/bin/autoconf --force --warnings=no-portability
autoreconf: running: /usr/bin/autoheader --force --warnings=no-portability
autoreconf: running: automake --add-missing --copy --force-missing --warnings=no-portability
configure.ac:13: installing './compile'
configure.ac:9: installing './missing'
autoreconf: Leaving directory `.'
Running ./configure ...
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether UID '1000' is supported by ustar format... yes
checking whether GID '1000' is supported by ustar format... yes
checking how to create a ustar tar archive... gnutar
checking whether make supports nested variables... (cached) yes
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking how to print strings... ^C
[mh-cbon@localhost cpufreq] $ lsb_release -a
LSB Version:	:core-4.1-amd64:core-4.1-noarch
Distributor ID:	Fedora
Description:	Fedora release 34 (Thirty Four)
Release:	34
Codename:	ThirtyFour
```

**Comment by mh-cbon** [comment]
would this work to build the archive using a docker@ubuntu ? then using it to install on fedora ?

**Comment by mh-cbon** [comment]
it has been 2 hours now, busy checking how to print strings. :x

**Comment by mh-cbon** [comment]
kind of worked, the docker stuff etc, though, upon reboot of the gnome interface it started to ask for root permssions to do some stuff and never let it go, it resulted in a complete blockage of my gnome setup, i could not escape it = )

**Comment by mh-cbon** [comment]
Ok, so i have followed this https://github.com/konkor/cpufreq/blob/gtk/INSTALL.md#from-git-source

ended up with the same issue, restarted with a terminal, tried `~/.local/share/gnome/.../cpufreqcl --install`, got a message about a missing file at `/sys/devices/system/cpu/cpu0/cprufreq/scaling_available_frequencies`

**Comment by konkor** [comment]
Hi, @mh-cbon just compiled it on Fedora 34. I have installed a few extra packages to do that:
```sh
dnf install glib2-devel
dnf install gnome-common
```
Also I installed Anjuta IDE to pull some basic dependencies but by itself it didn't help a lot.

BTW, the new version is already available on extensions.gnome.org with GNOME 40 supporting.

Thanks for your report!

**Comment by konkor** [comment]
You can always use [install_extension.sh](https://github.com/konkor/cpufreq/raw/master/install_extension.sh) script if you want to install the git version so.

**Comment by mh-cbon** [comment]
ah thank you! I had drop this after the missing file, i had no constructive idea about what to do further, i have little doubts i did it wrong somewhere. I will keep watching for its arrival in the website https://extensions.gnome.org/# I really miss this extension. I will definitely give a shot to the insall script, at least to let share the results.

**Comment by mh-cbon** [comment]
the script worked perfectly! yeay = ) thank you so very much.
