### ISSUE TITLE
Notifications preference is not being saved

### ISSUE THREAD

**Issue by PiotrDabrowskey** [konkor/cpufreq#177]
After the latest update from the GNOME Shell Extensions, the extension does not save the "Notifications" preference. I do have "Remember setting" enabled, though I think it does something different (remembers the settings in the main app screen?).

I use:
- cpufreq - not sure about exact version of the extension I'm using (I'm dumb or it is not stated anywhere?).
- GNOME Shell 3.36.7
- Ubuntu 20.04.2 LTS

Quick demo of the problem:
![Peek 2021-05-17 22-17](https://user-images.githubusercontent.com/9080823/118551031-b9ae9500-b75d-11eb-87d4-4a748fb74e9b.gif)

**Comment by jpstierlin** [comment]
Quick fix: Remove the wrong line 179 in prefs,js:
            save = this.cb_notify.active;

**Comment by konkor** [comment]
Thank you for the report. 
@jpstierlin Sure, it should be:
system_notifications = this.cb_notify.active;

I will fix it now.

**Comment by konkor** [comment]
Commit https://github.com/konkor/cpufreq/commit/2cd6d68902fc7c82bf54edb8bb92bf7187d2f9bb closes this issue

**Comment by PiotrDabrowskey** [comment]
Thanks! That's super quick response :)
