### ISSUE TITLE
GLib.Error g-unix-error-quark: Too many open files

### ISSUE THREAD

**Issue by belegdol** [konkor/cpufreq#178]
Since upgrading to Fedora 34 & Gnome 40, journal gets spammed with the entries lie:
```
Mai 19 12:12:38 snowball3 gnome-shell[2031]: [Wed May 19 2021 12:12:38.718](EE) [cpufreq][cpu helper] GLib.Error g-unix-error-quark: Zu viele offene Dateien
```
Can this be avoided? Thanks.

**Comment by konkor** [comment]
@belegdol Maybe you are using too small time interval for monitoring. Try 500/1000+ ms etc

**Comment by SytheZN** [comment]
I'm seeing the same thing. Leaving it alone eventually leads to general system instability and gnome-shell crash as at 
https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/4302

My settings are default(ish):
![image](https://user-images.githubusercontent.com/7147264/118991842-60747a80-b984-11eb-8015-de8a57797845.png)

I first see this for a while:
```
May 20 15:47:15 sythezn-desktop pkexec[19247]: pam_unix(polkit-1:session): session opened for user root(uid=0) by (uid=1000)
May 20 15:47:15 sythezn-desktop audit[19247]: USER_START pid=19247 uid=1000 auid=1000 ses=3 subj=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 msg='op=PAM:session_open grantors=pam_keyinit,pam_limits,pam_systemd,pam_unix acct="root" exe="/usr/bin/pkexec" hostname=? addr=? terminal=? res=success'
May 20 15:47:15 sythezn-desktop pkexec[19247]: sythezn: Executing command [USER=root] [TTY=unknown] [CWD=/] [COMMAND=/usr/bin/cpufreqctl --throttle-events]
May 20 15:47:17 sythezn-desktop pkexec[19270]: pam_unix(polkit-1:session): session opened for user root(uid=0) by (uid=1000)
May 20 15:47:17 sythezn-desktop audit[19270]: USER_START pid=19270 uid=1000 auid=1000 ses=3 subj=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 msg='op=PAM:session_open grantors=pam_keyinit,pam_limits,pam_systemd,pam_unix acct="root" exe="/usr/bin/pkexec" hostname=? addr=? terminal=? res=success'
May 20 15:47:17 sythezn-desktop pkexec[19270]: sythezn: Executing command [USER=root] [TTY=unknown] [CWD=/] [COMMAND=/usr/bin/cpufreqctl --throttle-events]
May 20 15:47:19 sythezn-desktop pkexec[19293]: pam_unix(polkit-1:session): session opened for user root(uid=0) by (uid=1000)
May 20 15:47:19 sythezn-desktop audit[19293]: USER_START pid=19293 uid=1000 auid=1000 ses=3 subj=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 msg='op=PAM:session_open grantors=pam_keyinit,pam_limits,pam_systemd,pam_unix acct="root" exe="/usr/bin/pkexec" hostname=? addr=? terminal=? res=success'
May 20 15:47:19 sythezn-desktop pkexec[19293]: sythezn: Executing command [USER=root] [TTY=unknown] [CWD=/] [COMMAND=/usr/bin/cpufreqctl --throttle-events]
May 20 15:47:21 sythezn-desktop pkexec[19315]: pam_unix(polkit-1:session): session opened for user root(uid=0) by (uid=1000)
May 20 15:47:21 sythezn-desktop audit[19315]: USER_START pid=19315 uid=1000 auid=1000 ses=3 subj=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 msg='op=PAM:session_open grantors=pam_keyinit,pam_limits,pam_systemd,pam_unix acct="root" exe="/usr/bin/pkexec" hostname=? addr=? terminal=? res=success'
May 20 15:47:21 sythezn-desktop pkexec[19315]: sythezn: Executing command [USER=root] [TTY=unknown] [CWD=/] [COMMAND=/usr/bin/cpufreqctl --throttle-events]
May 20 15:47:23 sythezn-desktop pkexec[19338]: pam_unix(polkit-1:session): session opened for user root(uid=0) by (uid=1000)
May 20 15:47:23 sythezn-desktop audit[19338]: USER_START pid=19338 uid=1000 auid=1000 ses=3 subj=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 msg='op=PAM:session_open grantors=pam_keyinit,pam_limits,pam_systemd,pam_unix acct="root" exe="/usr/bin/pkexec" hostname=? addr=? terminal=? res=success'
May 20 15:47:23 sythezn-desktop pkexec[19338]: sythezn: Executing command [USER=root] [TTY=unknown] [CWD=/] [COMMAND=/usr/bin/cpufreqctl --throttle-events]
```

Followed by this:
```
May 20 15:47:35 sythezn-desktop gnome-shell[3335]: [Thu May 20 2021 15:47:35.313](EE) [cpufreq][cpu helper] GLib.Error g-unix-error-quark: Too many open files
May 20 15:47:37 sythezn-desktop gnome-shell[3335]: [Thu May 20 2021 15:47:37.315](EE) [cpufreq][cpu helper] GLib.Error g-unix-error-quark: Too many open files
May 20 15:47:39 sythezn-desktop gnome-shell[3335]: [Thu May 20 2021 15:47:39.317](EE) [cpufreq][cpu helper] GLib.Error g-unix-error-quark: Too many open files
May 20 15:47:41 sythezn-desktop gnome-shell[3335]: [Thu May 20 2021 15:47:41.319](EE) [cpufreq][cpu helper] GLib.Error g-unix-error-quark: Too many open files
May 20 15:47:43 sythezn-desktop gnome-shell[3335]: [Thu May 20 2021 15:47:43.321](EE) [cpufreq][cpu helper] GLib.Error g-unix-error-quark: Too many open files
```

**Comment by konkor** [comment]
I can't reproduce it yet. Thanks to @SytheZN I see where is could be the issue. Looks like the issue with intel_pstate mode...

**Comment by SytheZN** [comment]
Hmmm, may well be AMD related; this system is a Threadripper 3960X on an Asrock TRX40 Taichi.

I continue to see the GLib errors until I kill cpufreq-service.

Are there any logs/dumps I could collect to make things clearer?

**Comment by SytheZN** [comment]
After a bit more digging I'm not sure that the root cause is cpufreq, rather I believe something in the environment hosting extensions has changed and is causing pipes to hang around after the source terminates. 

Here's the descriptors I see on cpufreq-service after less than 30s of starting the extension: 
[cpufreq-service_fd_1min.txt](https://github.com/konkor/cpufreq/files/6521126/cpufreq-service_fd_1min.txt)

This is the same 10 minutes later: 
[cpufreq-service_fd_10min.txt](https://github.com/konkor/cpufreq/files/6521132/cpufreq-service_fd_10min.txt)

Suspiciously similar to what I'm seeing with the Freon extension, except in that case the host process for the pipes is gnome-shell, so the descriptors pile up and eventually crash it.

**Comment by goldyfruit** [comment]
Facing the same behavior on Pop!_OS 20.10 & Gnome 3.38.3 with AMD processor. As @belegdol mentioned, reducing the interval to 5000ms helped but didn't "solve" the issue.

**Comment by konkor** [comment]
There is some progress. I can reproduce it on Fedora 34 and I'm working on it.

**Comment by konkor** [comment]
Thank you all for this report! I have limited HW now. If you report me how it works now I will really appreciate that!

You can use https://github.com/konkor/cpufreq/raw/master/install_extension.sh as ordinary user to quick update to github branch.

**Comment by belegdol** [comment]
It is either not working or the script is not installing it properly. The last thing shown is wget download, is this expected?

**Comment by konkor** [comment]
@belegdol it's okay that version is the same. You should restart GNOME Shell to apply changes and user services like cpufreq-service

**Comment by belegdol** [comment]
In that case the issue is still there:
```
maj 21 21:45:31 napoleon2 gnome-shell[2227]: [Fri May 21 2021 21:45:31.419](EE) [cpufreq][cpu helper] GLib.Error g-unix-error-quark: Za dużo otwartych plików
maj 21 21:45:32 napoleon2 gnome-shell[2227]: [Fri May 21 2021 21:45:32.420](EE) [cpufreq][cpu helper] GLib.Error g-unix-error-quark: Za dużo otwartych plików
maj 21 21:45:33 napoleon2 gnome-shell[2227]: [Fri May 21 2021 21:45:33.421](EE) [cpufreq][cpu helper] GLib.Error g-unix-error-quark: Za dużo otwartych plików
maj 21 21:45:34 napoleon2 gnome-shell[2227]: [Fri May 21 2021 21:45:34.422](EE) [cpufreq][cpu helper] GLib.Error g-unix-error-quark: Za dużo otwartych plików
maj 21 21:45:35 napoleon2 gnome-shell[2227]: [Fri May 21 2021 21:45:35.423](EE) [cpufreq][cpu helper] GLib.Error g-unix-error-quark: Za dużo otwartych plików
maj 21 21:45:36 napoleon2 gnome-shell[2227]: [Fri May 21 2021 21:45:36.424](EE) [cpufreq][cpu helper] GLib.Error g-unix-error-quark: Za dużo otwartych plików
maj 21 21:45:37 napoleon2 gnome-shell[2227]: [Fri May 21 2021 21:45:37.425](EE) [cpufreq][cpu helper] GLib.Error g-unix-error-quark: Za dużo otwartych plików
maj 21 21:45:38 napoleon2 gnome-shell[2227]: [Fri May 21 2021 21:45:38.426](EE) [cpufreq][cpu helper] GLib.Error g-unix-error-quark: Za dużo otwartych plików
```

**Comment by SytheZN** [comment]
Mine did the same, metadata version has not been updated but modified date on files was updated:
![image](https://user-images.githubusercontent.com/7147264/119190484-b6791900-ba7d-11eb-9133-e87e762d86e5.png)
Running wayland so shell restart is not possible, but rebooted instead.

Update seems to be working :smile: 

After 10 min, fd seems normal: 
[cpufreq-service_fd_10min_updated.txt](https://github.com/konkor/cpufreq/files/6524784/cpufreq-service_fd_10min_updated.txt)

**Comment by konkor** [comment]
@belegdol try to reboot PC. There is the new version of the extension if you need it. Also you can wait a bit for update
[cpufreq@konkor.zip](https://github.com/konkor/cpufreq/files/6524809/cpufreq%40konkor.zip)

**Comment by konkor** [comment]
@SytheZN You can check for open file descriptors in the process context menu in gnome-system-monitor so ;)

**Comment by SytheZN** [comment]
> @SytheZN You can check for open file descriptors in the process context menu in gnome-system-monitor so ;)

Yep, figured that out just now, too :rofl: Still handy to know about the proc folders since I can hit that from SSH.

**Comment by goldyfruit** [comment]
@konkor thanks for the fix! :+1:

**Comment by belegdol** [comment]
Looks to be fixed for me too. Thanks!
