### ISSUE TITLE
[Testing Request] Droping dependency from external packages cpufrequtils/cpupower

### ISSUE THREAD

**Issue by konkor** [konkor/cpufreq#18]
Actually I don't use this packages long time ago. And It should work without this dependency on any supported architecture by kernel (x86, amd, arm, msm, tegra...).
So I want to test master's version on your favorite distribution and hardware before i'll push new version to extensions.gnome.org. So you can:
1. Uninstall _cpufrequtils/cpupower_ and test how it works;
1. Run your favorite Linux Live CD/DVD/Flash and install the cpufreq extension from GitHub.

Thank you very much!

**Comment by TheElectronWill** [comment]
Tested on MSI GS60-Ghost, Fedora 25 64bits.
It works perfectly without cpufrequtils!

**Comment by konkor** [comment]
@TheElectronWill nice. Thank you.

**Comment by konkor** [comment]
This feature is already in the stable release...
