### ISSUE TITLE
Not able to upgrade extension on Ubuntu 20.04

### ISSUE THREAD

**Issue by vadi2** [konkor/cpufreq#181]
It just gives this unfortunately:

![image](https://user-images.githubusercontent.com/110988/119252132-cc382c80-bbaa-11eb-8bbb-ea246f6c3a1e.png)

Error message in logs:

```
[00;31m[Sun May 23 2021 09:39:27.219](EE) [cpufreq][cpu helper][0m GLib.Error g-unix-error-quark: Too many open files
```

According to `ps $(lsof | awk '{print $2}' | uniq -c | sort -rn | head -n5 | awk '{print $2}')`, the extension is at the top -

```
    PID TTY      STAT   TIME COMMAND
   3078 ?        Sl     0:11 /usr/bin/gjs /home/vadi/.local/share/gnome-shell/extensions/cpufreq@konkor/cpufreq-service
   4319 ?        Sl     1:37 /usr/lib/insync/insync start
  13878 ?        Sl     1:16 /usr/lib/firefox/firefox -new-window
  13946 ?        Sl     0:18 /usr/lib/firefox/firefox -contentproc -childID 1 -isForBrowser -prefsLen 1 -prefMapSize 248692 -parentBuildID 20210504152106 -appdir 
  14000 ?        Sl     0:07 /usr/lib/firefox/firefox -contentproc -childID 2 -isForBrowser -prefsLen 96 -prefMapSize 248692 -parentBuildID 20210504152106 -appdir
```

**Comment by konkor** [comment]
@vadi2 Just restart/relogging user session and update the page and all be fine. Sometimes it happens after updates.

BTW: If you press on that error icon what it gives you?

**Comment by vadi2** [comment]
Pressing the error icon doesn't give much.

**Comment by konkor** [comment]
So restarting of the user session didn't help you to install it?

**Comment by vadi2** [comment]
That worked!
