### ISSUE TITLE
Gnome extension is broken now with latest browsers

### ISSUE THREAD

**Issue by KeithMyers** [konkor/cpufreq#182]
Got notified that the Gnome cpufreq extension needed updating.  So allowed that to happen but then the extension turned into an error.
Tried the same thing with Firefox and was greeted with the same error.

Tried uninstalling and then reinstalling and was met with same red error button.

Can't figure out how to revert to earlier version.

**Comment by konkor** [comment]
@KeithMyers Looks like it's a duplicate #181 You need just ignore the error and restart GNOME Shell session. I think it's extensions website issue and not the browsers. I can't figure out how to avoid this issue yet.

**Comment by lauchokyip** [comment]
confirm restarting GNOME shell session will fix the issue. If anyone wondering how to restart GNOME session, press `ALT + F2` and insert `r`

**Comment by KeithMyers** [comment]
Tried all that. Still stuck with no extension in the top bar and the error button.
Removed everything and rebooted.  Re-added the extension and now is working again.
It got confused or something.  Fixed now.

**Comment by konkor** [comment]
This is GNOME Shell issue and it's still open. They can't decide what to do with it. Newer version of JS engine caching extensions and couldn't be unloaded without restarting whole Shell Session...

**Comment by KeithMyers** [comment]
Thanks for the comment.  Knew something weird happened with the new browsers. Was afraid to touch the other hosts that also have the update notification pending for cpufreq.

Thanks for the info that real problem is with GNOME Shell and not the extension itself.

**Comment by konkor** [comment]
@KeithMyers New versions of GNOME Shell is updating extensions automatically now. They are using **gnome-extensions-app** on startup to check and load updates and apply changes on the next log-in. Updating extensions from the site is just for older versions of GNOME. Anyway they should handle it different on the extensions.gnome.org site to not confuse users with that error button.
