### ISSUE TITLE
Logs are spammed out

### ISSUE THREAD

**Issue by vadi2** [konkor/cpufreq#183]
The extension seems to be spamming the logs with hundreds of messages - is this normal?

![image](https://user-images.githubusercontent.com/110988/119773483-fcd8d880-bec0-11eb-9408-395d13ebdd96.png)

**Comment by konkor** [comment]
Hi, it's how works pkexec. But you're right there is no need to check thermal throttle events on CPUs without TT counters so often. Also modern disros have included default users to journal users. I will try to fix this issue.
Thank you for the report!
