### ISSUE TITLE
Can't reduce Maximum frequency

### ISSUE THREAD

**Issue by RicardoEPRodrigues** [konkor/cpufreq#20]
I downloaded the latest version and now I can't change the Maximum frequency.

![Maximum Disabled](https://cloud.githubusercontent.com/assets/7673578/25332923/307ebe00-28e0-11e7-9b8c-6a1c1b8eafe1.png)

It appears disabled even if I select Powersaver.

**Comment by konkor** [comment]
Heh you are right, it was fix for issue #14... i completely forget about this behavior on intel pstate driver...

**Comment by konkor** [comment]
@RicardoEPRodrigues done...

**Comment by RicardoEPRodrigues** [comment]
Yup, it's done! Closed it :smile:
