### ISSUE TITLE
Setting frequency via CLI doesn't work

### ISSUE THREAD

**Issue by Fushko** [konkor/cpufreq#200]
Screenshot should be clear. What am I doing wrong? Setting the frequency step to 2.8 Ghz works on the GUI.
![immagine](https://user-images.githubusercontent.com/22770482/148518164-e6710e7c-92b4-489b-ad93-268234d19e58.png)

I've also tried passing --frequency instead of --frequency-max, to no avail.

**Comment by konkor** [comment]
You missed `=` sign in --set option

```sh
cpufreqctl --frequency-max --set=2000000
```
