### ISSUE TITLE
compatibility with Auto-CPUFreq

### ISSUE THREAD

**Issue by liznevada** [konkor/cpufreq#208]
Hi. the AUR PKGBUILD (https://aur.archlinux.org/packages/auto-cpufreq-git)  for Auto-CPUFreq (https://github.com/AdnanHodzic/auto-cpufreq) for some reason list this extension as a optional dependency, but my question is, is the extension cpufreq compatible with auto-cpufreq?

because i assume two tools designed to control the CPU frequency would conflict with each other.

**Comment by konkor** [comment]
Yes, they could conflict with each other if you will try to control CPU power in both apps. But you can use autocpufreq for control and this extension for monitoring.

**Comment by liznevada** [comment]
so if i wanted to use yours for both control and monitoring, its fine to remove auto-cpufreq?

 not only this has an useful gui. i had to make a script to switch auto-cpufreq to balanced at boot as to make it stop forcing the laptop into powersaving all the time. (it ignored its own config file for some bizarre reason).

also glad to see you safe.

**Comment by konkor** [comment]
Yes, you're completely fine to use just this extension...

Thanks, I'm still between nowhere. But I bought a laptop and I'm safe for now. I'm still in military reserve. Nobody knows what it will be next. Today we have Independency Day and we have air raid alerts/sirens all the day long.

**Comment by liznevada** [comment]
Thank you. will remove auto-cpufreq then.

keep strong friend, being in a war certainly sucks, hope this get over soon.
