### ISSUE TITLE
Move preferences to Tweak Tool

### ISSUE THREAD

**Issue by RicardoEPRodrigues** [konkor/cpufreq#21]
I think the preferences (although only one option currently) should be accessed through the tweak tool.

`ShellTile` has a simple example of that:

![2017-04-24-13h56-673x66](https://cloud.githubusercontent.com/assets/7673578/25338060/ddd9d28c-28f5-11e7-8f7c-1fddaa407b64.png)

![2017-04-24-13h56-606x459](https://cloud.githubusercontent.com/assets/7673578/25338070/e855e4bc-28f5-11e7-9b3d-382fa6050107.png)

**Comment by konkor** [comment]
I told you I always wanted keep the extension light and clear. It's not only window it's full gtk3 stack...
But any way sooner or later we'll come to this too...

**Comment by RicardoEPRodrigues** [comment]
I don't know the impact of creating the preferences window and how it can make the extension more or less complex.

I do think that this extension is essential for my workflow (and for that I thank you so much) and should adhere to the extensions conventions.

---
*SIDENOTE: Is there any good sources to learn GTK+ and extensions?*

**Comment by konkor** [comment]
@RicardoEPRodrigues It's not very big deal to create any GTK widget so preferences window it's a standard element...
About GTK and extensions:
1. Gnome extensions using Clutter library to make own Gnome shell widgets. Here is all they widgets https://github.com/GNOME/gnome-shell/tree/master/js/ui.
1. But Gnome JavaScript (gjs) is using standard GTK widgets for GUI apps like Maps, Music, Polary...
1. You have to clearly understand this difference. But both gnome extensions and apps using same Mozilla JavaScript Engine and API https://developer.mozilla.org/en-US/docs/Web/JavaScript
1. I don't know current state of JS docs on gnome but when i started it was a mess. But I have read 1st there. I wrote this my 1st JS extension in 24 hours but it was like really 24/24. Example was old fashioned or for old Gnome at all. I started to read my installed extensions to understand how it works and should be like. Then i found some blog how-to made simple extension i cant find it exactly now. But you'd google it like `gnome extension blog`https://www.abidibo.net/blog/2016/03/02/how-i-developed-my-first-gnome-shell-extension/ or http://mathematicalcoffee.blogspot.com.au/2012/09/gnome-shell-javascript-source.html 1. So when you make some 1st working prototype with icon/label/popupmenu the best knowledge source is search in GitHub and StackOverflow :)
1. So you can try a luck on JavaScript IRC channel irc.gimp.org #javascript and ask help from gjs devs ;) or some other

**Comment by konkor** [comment]
@RicardoEPRodrigues https://developer.gnome.org/ is creat resource too not for extensions but about all with examples with C, C++, Vala, Python and JavaScript... https://developer.gnome.org/platform-overview/unstable/tour.html.en

**Comment by RicardoEPRodrigues** [comment]
Thank you!

**Comment by konkor** [comment]
@RicardoEPRodrigues We'll do preferences window when we have to. To example when we need some space for profile editing or too many options. For now i want to close this issue. I can't clearly think when opened so many issues. LoL.
So I'll refer this to #12 now.
