### ISSUE TITLE
Please update to Gnome 43

### ISSUE THREAD

**Issue by thekswenson** [konkor/cpufreq#210]
I know that @konkor is probably not able to work on this project at the moment, but I'm making this issue, along with a note.
Best of luck for your transition @konkor, we are hoping for a resolution to this invasion.

The app seems to be working fine for me in GNOME 43.
All I had to do was add "43" to the `shell-version` list in `~/.local/share/gnome-shell/extensions/cpufreq@konkor/metadata.json` file.

I'm not sure if other changes _should_ be done.

**Comment by nietzschescodes** [comment]
Is it really working on Gnome 43 the trick that @thekswenson gave?

**Comment by nietzschescodes** [comment]
well,. I have upgraded to Gnome 43 and @thekswenson 's trick doesn't work at all....

**Comment by thekswenson** [comment]
Don't know what to say... it works for me.

![image](https://user-images.githubusercontent.com/9959942/199432117-b7e05bc5-c28f-42c8-b9db-925588f7cb41.png)

**Comment by nietzschescodes** [comment]
Wow! Bizarre. I added as you said "43" and nothing happened. Did you change version 52 into version 53? If not, what Am I missing?
![Screenshot from 2022-11-02 10-27-10](https://user-images.githubusercontent.com/116679962/199454174-f3e36773-c6f7-4cb9-b7dd-d7075050702a.png)

**Comment by thekswenson** [comment]
I only made that single change, I think. I'm sorry, I don't know enough about this thing to help. I consider myself lucky to have it working still, as I love to save power when my machine is unplugged.

**Comment by neclimdul** [comment]
noticed there was an update today and after applying it things seem to work on 43.1. 

Thanks! Slava Ukraine!

**Comment by petar-v** [comment]
Hi! @thekswenson it indeed works for gnome 43, please consider closing this issue. Thanks!
