### ISSUE TITLE
Add support for GNOME 44

### ISSUE THREAD

**Issue by gtirloni** [konkor/cpufreq#218]
https://release.gnome.org/44/

https://fedoramagazine.org/announcing-fedora-38/

**Comment by RafalSkolasinski** [comment]
what could be ETA for this landing at https://extensions.gnome.org/extension/1082/cpufreq ?

**Comment by TuxyKey** [comment]
Hope the developer has time to do this for us all.. Thanks and appreciation to  developer for his work on cpufreq ..
