### ISSUE TITLE
Make separate testing branch

### ISSUE THREAD

**Issue by terencode** [konkor/cpufreq#22]
As development keeps going, I see experimental features being pushed so even if it is not yet present on extensions.gnome.org, it would be a good idea to consider master branch as stable/tested and create a separate branch to add, test and give feedback on new features.

**Comment by konkor** [comment]
@terencode You are right but I don't have to much testers here. Even after publishing on G+ i have 6 unique clones for last few days only and 16 for past 2 weeks. So sometimes I'm pushing to gnome just to get more testers :( bcs i can wait here for month and don't get any replays.
And I mostly have newcomers with some hardware issues. They're looking for some solution with overheating, power consuming or performance issues...

**Comment by RicardoEPRodrigues** [comment]
I would propose something a bit different. Let master be the testing ground and make a Release branch for when a solution is stable.

That way if something in master goes terribly wrong you can always revert to the last Release.

I also noticed we already have version tags that do that, so maybe I don't know if a new branch is needed. It would always be good in terms of code maintenance I think. Epic Games uses a master/Release branch system in Unreal Engine, but that is a bit more complex.

**Comment by konkor** [comment]
OK. I understand your worries thank you guys for that. But I was thinking all this issues and i have  a bit stacking about all this issues. I decided to push this to gnome after a few cosmetic updates. I want to do next before i'll push this to gnome:
1. Replace CPU Power switches with Slider like for frequencies from 2 to N-1;
2. Group min/max frequencies to a sub-menu. The extension needs more space especially on low-resolution displays. Later i want to do on the top of main menu some status menu item for the next features like cpu thermal throttling, core temp warnings, cpu usage... I don't know exactly now what and how but it must be clear useful critical info on the main menu?!
3. Update/review the documentations.
Next I'll make testing branch if this critical for some reasons ofc. Now we have like Scrum development cycle based on the features. But if we'll make time based releases we have to make stable branches with only critical fixes for releases...

**Comment by RicardoEPRodrigues** [comment]
@konkor when you said: `Replace CPU Power switches with Slider like for frequencies from 2 to N-1;` I think you meant `N` and not `N-1`.

I have 8 Cores so the slider would go from 2 to 8. Right? :smile:

**Comment by konkor** [comment]
I'm still thinking about it :) You are right. I'll remove single core too. It should be from 1 to 8. Right?

**Comment by RicardoEPRodrigues** [comment]
You said that overheating could be a problem, so maybe restricting to 2 would be best.

Maybe only allow single core on dual-core CPUs?

**Comment by konkor** [comment]
Yes it's why I wanted to protect users from mistakes. So I guess you have 4 cores and 8 core threads it's no sense to leave for work a half CPU core.
Here is a few ways to do same thing: I can warn users about using only 1 core. So we can move some option to preferences like Allow Single Core Mode :)

**Comment by RicardoEPRodrigues** [comment]
I agree, let users decide, but warn them.

**Comment by konkor** [comment]
I like this idea too but it's not easy to implement. Pop-up menu can't handle large explanation, notify messages not really useful. But here few ways too :)
We could make a link on warning button/label to readme with some explanation. Or/and show warn message on all screen like in extension template with some fade in out FX...

**Comment by RicardoEPRodrigues** [comment]
Is it possible to have a hidden message with that button/label and only show it when the user selects 1 core?

**Comment by konkor** [comment]
@RicardoEPRodrigues here is no standard ways to do this. I think about something like this _⚠ Single Core Not Recommended_ and link to readme file.

**Comment by RicardoEPRodrigues** [comment]
Yes to that warning, but it would be better if it only showed when only 1 core was selected.

**Comment by konkor** [comment]
@RicardoEPRodrigues yes ofc. Let's do this :)

**Comment by konkor** [comment]
@RicardoEPRodrigues done in master. if u'll see something let me know.

**Comment by RicardoEPRodrigues** [comment]
I approve! Very nice!

**Comment by konkor** [comment]
@RicardoEPRodrigues I updated the menu layout and wanted to ask you to test on intel pstate. What do you think if we'll make same submenu for intel pstate module? I think about MHz/GHz in the frequencies submenu? So this word _Scaling_ not to much for average users maybe _Speed_, _Frequencies_ or _Limits_? What do you think?
![screenshot from 2017-04-28 14 37 01](https://cloud.githubusercontent.com/assets/1944781/25527437/749b79ae-2c21-11e7-8775-9d5b695d9b8c.png)
![screenshot from 2017-04-28 14 37 07](https://cloud.githubusercontent.com/assets/1944781/25527448/7c059bc0-2c21-11e7-8b23-c50a8073c098.png)

**Comment by RicardoEPRodrigues** [comment]
The menu works well, maybe _Speed_ or _Frequency_ are the best naming.

I was thinking that I liked the frequencies to always be showing, maybe later that could be in the preferences. _Always Show Frequencies: ON/OFF_

**Comment by konkor** [comment]
@RicardoEPRodrigues TY very much) I like to hear it from someone else. It's too empty and frequencies is part of the extension name. I'll move it to new branch at least now.
One more question maybe it's better move _8 Cores Online_ inside this submenu (_Power_). It's looking empty too now after removing all this switchers?

**Comment by RicardoEPRodrigues** [comment]
I like the way it is, but if you want to try it out I'll see how it feels.

I think it's important that people always see how many cores they have on. Otherwise they might forget to re-enable them.

**Comment by konkor** [comment]
So Is It OK?
![screenshot from 2017-04-28 17 58 27](https://cloud.githubusercontent.com/assets/1944781/25534624/fec06f02-2c3c-11e7-9034-759e7a043a61.png)

**Comment by RicardoEPRodrigues** [comment]
I really like it, simple and sends all the messages. Have you pushed it to any branch?

**Comment by konkor** [comment]
This is in the latest Master branch.

**Comment by RicardoEPRodrigues** [comment]
Can we try one thing? (Maybe it was what you were saying)

Instead of having a `8 Cores Online` submenu with a slider inside, have just `8 Cores Online` and a slider bellow, like the maximum and minimum.

**Comment by konkor** [comment]
@RicardoEPRodrigues You're right. There is no sense in 1 row submenu like i told too empty. We'll try it for sure.
I'm editing description and readme now... What do you think about this description:
https://extensions.gnome.org/extension/1082/cpufreq/

**Comment by konkor** [comment]
I changed shot description from _CPU frequency monitor and governor manager_ to _CPU Frequency Monitor, Governor And Power Manager._ ... But I'm thinking about _CPU Control Center_ :) Here is a lot features even now and more detailed description repeats all words from base... So I edited detailed description too and going to edit readme...

**Comment by RicardoEPRodrigues** [comment]
I like _CPU Control Center_ or maybe just _CPU Manager_.

Instead of _CPU Power On/Off_ maybe put something like _Support for powering off CPU cores_, it's more explicative and easy to understand.

**Comment by konkor** [comment]
We'll think about short description. So it can be _CPU Power Manager_ or _Gnome Power Manager_ or _Gnome CPU Manager_ or _Gnome CPU Manager_ or _Gnome CPU Power Manager_ ... OMG LoL
Here some screenshots without CPU Power submenu:
![screenshot from 2017-04-29 11 21 55](https://cloud.githubusercontent.com/assets/1944781/25554257/6e60fce8-2cd1-11e7-9f09-6bebfbccbdeb.png)
![screenshot from 2017-04-29 11 31 15](https://cloud.githubusercontent.com/assets/1944781/25554260/7658e956-2cd1-11e7-8446-7972e61a9144.png)

**Comment by konkor** [comment]
So here screenshot with separator:
![screenshot from 2017-04-29 12 46 55](https://cloud.githubusercontent.com/assets/1944781/25554618/3ab708ca-2cda-11e7-97b6-c4cd43ca83ca.png)
PS: I feel like it's ready for global testing :)

**Comment by RicardoEPRodrigues** [comment]
I prefer it without the separator.

Awesome layout.

I've been having issues with the wifi, yet I think it's not related with this extension, but with Ubuntu 17.04...

**Comment by konkor** [comment]
I'm testing on Fedora 26 it's still alpha. The new kernel 4.11 has a lot changes...

**Comment by RicardoEPRodrigues** [comment]
I'm using kernel `4.10`, I don't know if it helps :smile:

**Comment by konkor** [comment]
Here's a strange behavior the kernel is hiding online status for active cores and shows 0 for inactive cores only... I don't like it. And more strange things.

**Comment by RicardoEPRodrigues** [comment]
I feel that this behavior of switching off cores is not well though for PC/Laptops.

Since it is well tested in Android, High and Low power cores.

How can I help you test this?

**Comment by konkor** [comment]
@RicardoEPRodrigues You can test battery live with a half cores and all cores enabled to example. But here a few options too on idle or average or high loading... I think the kernel is not a problem here but some software can be issue if they don't have dynamic balancing (if they don't watching about how many active cores but heavy using them like on the start...)...
But I don't want remove this kernel feature... People have to start asking devs) So I have much more headache with this feature too.
I found a way to fix 4.11 issue so. And have another related question Here is possibility to have _MIXED_ governors for cores to example:
0. U have 4 cores in powersave mode.
1. U have switched off 3 cores.
2. U have changed mode to performance.
3. U have power on 3 cores.
4. So U can get 1 core in performance and 3 in powersave mode...
How should I display active mode? mixed? or...
or
Just init powered on cores with current active mode (here is performance in example)

**Comment by terencode** [comment]
I feel like adding this feature will make profiles a real thing.... You should be able to access a menu to set what governor each core should use.

**Comment by terencode** [comment]
Oups

**Comment by konkor** [comment]
@terencode it's already in the code. It's just not showing this correctly...

**Comment by terencode** [comment]
I know there is this remember settings thing but it's not really what I would call a profile system.

**Comment by konkor** [comment]
@terencode i talked about _mixed mode_ not profiles. I think we could do Profiles when almost features will done to have some standard. I don't really know...

**Comment by terencode** [comment]
@konkor when we will have per-core governor and all things related to it, we'll need to consider making a complete one I think?

**Comment by konkor** [comment]
@terencode _per-core governors_ I thought about it from the beginning and dropped this idea. There is a few reasons why:

1. Very complicated UI especially for average user.
2. Gnome shell popupmenu has 2 levels only.
3. Is it so useful? Question...

I'm thinking about profiles #12 like something light:
**Profiles ▼**
↳    New ...
↳    My Profile Name 1 ☒
↳    My Profile Name N ☒
Without an editor... So You could Save current settings like a Profile and remove a profile by clicking ☒ ... I think the profile editor not needs bcs you could load some profile, make changes and save it like new one.

**Comment by konkor** [comment]
New Screenshot. I think wider image would look better.
![](https://github.com/konkor/cpufreq/raw/master/data/screenshots.png?raw=true)
So It's coming the 1st extension's anniversary (7 May)...

**Comment by RicardoEPRodrigues** [comment]
Regarding the `per-core governors`, I think for now this is the correct layout and when changing the active cores the extension should change their governors to the current one. Picking up on @konkor example:

1. U have 4 cores in powersave mode.
2. U have switched off 3 cores.
3. U have changed mode to performance.
4. U have powered on 3 cores.
 * When switching on the cores, the extension sets the governor to performance.
5. U have 4 cores in performance mode. (consistency)

---

On another note, I think in the future we could have a preference option like `Advanced Mode`.

In this mode we'd no longer have a slider for the active cores, but instead have the list as before and allow it to select if the core is ON/OFF and it's governor.

**Comment by konkor** [comment]
I pushed/released the current state (v11) to/on gnome.org ...
@RicardoEPRodrigues Now the extension shows _mixed mode_ to warn users only. I think It's OK.
So I want decide what is next more important for you guys:
1. _Advanced Mode_ per-core sub-menus with governors and frequencies.
2. _Thermal Throttle_ monitoring option. I think It's more important then _Temperature monitoring_.
3. _Temperature monitoring_ through 'coretemp' module.
4. _CPU Loading_ stats, maybe monitoring or top 10 power hungry processes...
5. _Profiles_
6. Any ideas???

**Comment by RicardoEPRodrigues** [comment]
I would leave the Advanced Mode for a future release.

For now, maybe Profiles and CPU Load.
Can we create some `Feature Requests` for the list you made? One item per issue?

**Comment by konkor** [comment]
@RicardoEPRodrigues Feel free to make this requests... Thanks.
PS: I'd prefer _Thermal Throttle_ :) I had a issue with cooling system not so far and only CPU throttling has pointed me to this.

**Comment by RicardoEPRodrigues** [comment]
Created!

When can I become a Contributor? :smile:

**Comment by konkor** [comment]
@RicardoEPRodrigues I'd like to see any contributions. Make clone change something docs/code and make request...

**Comment by terencode** [comment]
@konkor *1.Advanced Mode per-core sub-menus with governors and frequencies*
but maybe temperature monitoring is outside the scope of cpufreq?

**Comment by konkor** [comment]
@terencode ty for your thoughts. My answer is yes and no. CPU throttling is directly related to the CPU. But what is this _CPU Thermal Throttle_ it's dropping cpu cycles to lower its temperature. So if I'll show some notification about throttling people will ask What is this, why?! I don't want to do full sensors monitoring tool but it's good to know if something going wrong with your system.
_Temperature monitoring_ is directly related to _CPU Thermal Throttle_. So I want make _CPU Thermal Throttle_ monitoring very light like checking once per minute for example. And check additionally temperature to show why is throttle if there is detected _CPU Thermal Throttle_.
Another way of the usage it's show temperatures in main menu on button click only. #24 #25

**Comment by konkor** [comment]
OK. We have:
1.5 points to _Advanced Mode_
1 point to _Profiles_ and _CPU Load_
and my 1 point to Thermal/Temperature monitoring
I'm going to do 1, 5, 2/3 and 4 ...
PS: So current Master brunch on extensions.gnome.org It's like the fastest release ever (<9 hours after pushing new version).
