### ISSUE TITLE
CPU Power Advanced Mode

### ISSUE THREAD

**Issue by RicardoEPRodrigues** [konkor/cpufreq#23]
This mode would replace the current active core slider with sub-menus with governors and frequencies for each core.

**Comment by konkor** [comment]
Prototype 1:
![advanced](https://cloud.githubusercontent.com/assets/1944781/25594870/28dae8fe-2ecb-11e7-8be3-ba43198b9871.png)

**Comment by RicardoEPRodrigues** [comment]
Could you explain what is happening?

Core 2 in ON and in Powersave, Core 3 is OFF, but the slider still says it has 8 cores online.

**Comment by konkor** [comment]
Lol it's GIMP... It's faster write code.

**Comment by terencode** [comment]
That's how I would expect it to be, nice! 
But where are the other core menu? 
I also have an other  idea consisting on not showing those options by default but instead dynamically adding them with a button like a '+' asking for which core to change and then adding it as drop in menu as we see on your mockup.

**Comment by konkor** [comment]
I thought about it a lot. I don't want to do this at least now. There is reasons:
1. It's making UI huge. Here is other solution make core selector (all, 0, ... N). But this wants a lot additional code anyway.
2. In fact the extension has already advanced mode now. U can setup each core by own governors and frequencies like i told above but through decreasing 1 by 1 cores.
3. To help _Advanced Users_ I could do a support of mixed modes in Profiles. So you could save Mixed mode to custom profiles.
4. Do you see a big point in this mode?
I understand It's not informative now but clicking by 8 submenus not the best way to get info too.
I decided to wait with this feature. If I missed something please commend.

**Comment by RicardoEPRodrigues** [comment]
I do understand your point. I think that this feature is not that relevant right now. Maybe if more features require an advanced mode, then we'll go deeper on this subject.

**Comment by konkor** [comment]
All features which you wanted is ready:
* You can setup each core or group of core threads by own governors (`and frequencies acpi only`). To do that you must:

1. Turn off **Remember Settings** option if it's on.
2. Set the governor and frequencies for 1st last group of CPU.
3. Turn off a few or one core threads.
4. Repeat 2nd and 3d steps if you want get few groups (max count is equal to core thread number).
5. Turn on all wanted cores.
6. Optionally, you can save current settings to a Profile.
7. Optionally, if you want turn on **Remember Settings**.

So if you have to example 4 cores you can make some Profiles like
* 2 ondemad, 2 powersave...
* 1 performance, 1 powersave, 2 offline...

**WARNING** If you have Hyper Threading enabled you should use paired groups to effective processor power management.

**Comment by konkor** [comment]
I think It's time to make Wiki or small standalone Help the static HTML pages with home, FAQ, Troubleshot and How-to pages... to collect all this things...
