### ISSUE TITLE
CPU Loading statistics

### ISSUE THREAD

**Issue by RicardoEPRodrigues** [konkor/cpufreq#26]
This feature would allow for the top 10 power hungry processes or some monitoring activities. So it could show some additional info at the panel's status area or/and in the main menu...

**Comment by terencode** [comment]
This little extension is going to transform into a hole in one cpu maintenance/monitoring tool aahahah

**Comment by RicardoEPRodrigues** [comment]
I almost feel these features could be their own extensions. Maybe the Konkor bundle!

**Comment by konkor** [comment]
@RicardoEPRodrigues @terencode You are both right. I think It must be very last feature... I don't pretend to replace dozens existing system monitors. But what I really want is a some short brief info widget about CPU. It should be a nice not very big custom widget on top of the main menu. It could include:
1. CPU logo;
2. CPU name;
3. CPU temperature;
4. Other the extension related info.
I thought about _bundle_ ( @RicardoEPRodrigues LOL) maybe other time It would be an external gnome JS/python application but all this a bit out scope of the extension.
PS: I have just started Profiles...
