### ISSUE TITLE
How can I use it on a mac?

### ISSUE THREAD

**Issue by niks551** [konkor/cpufreq#28]
Hi Team,

How can I use this on a mac and underclock my CPU.
Following is my configuration
<img width="586" alt="screen shot 2017-05-13 at 9 06 54 am" src="https://cloud.githubusercontent.com/assets/2838410/26027027/93fd04f2-37bb-11e7-8b7b-6d37df44dc11.png">

Regards,
Nikhil

**Comment by konkor** [comment]
@niks551 It's an interesting question. I didn't research macOS kernel power abilities at all even for BSD kernel. So it's an applet (Gnome extension) for Linux kernel only. Well You could try any Linux Distro with Gnome Desktop Environment. But if seriously You have to google for `How to change processor governors on mac os` and etc...
Regards

**Comment by RicardoEPRodrigues** [comment]
Maybe the App Store has some apps that can do the trick, otherwise you'll be stuck with using CLI or scripts to change the CPU frequency and governors.

I think we can close this issue.

**Comment by niks551** [comment]
Sorry guys for the late reply.
Thanks for all the suggestions.
Mac doesn't support or I tried looking at all the questions in Apple community.

Please feel free to let me know if you come across this again.
