### ISSUE TITLE
[Improvement] CSS theming?

### ISSUE THREAD

**Issue by altan-me** [konkor/cpufreq#3]
First of awesome extension :)

Was just hoping you could add in CSS theming as depending on the theme used the text position is of center.
I would add it in myself but I lack js knowledge.

![screenshot from 2016-06-02 20-53-30](https://cloud.githubusercontent.com/assets/12891722/15739500/69032888-2904-11e6-8883-891498355cd5.png)

Regards,
A

**Comment by konkor** [comment]
This is fixed on github.
Official version is pending for a review... u can use the version https://github.com/konkor/cpufreq/archive/master.zip
ty for report and comments)

**Comment by konkor** [comment]
https://github.com/konkor/cpufreq/raw/master/data/screenshots.png?raw=true
