### ISSUE TITLE
Profile changing on Battery or on Power

### ISSUE THREAD

**Issue by RicardoEPRodrigues** [konkor/cpufreq#33]
Allow user to define a default profile for when the laptop is using the Battery and another for when it is using the Power supply.

I googled a bit and found that it seems easy to find out if the laptop is on battery.

    grep POWER_SUPPLY_ONLINE /sys/class/power_supply/ADP1/uevent

Return 1 when in Power, 0 when in battery. (It's not that linear, because there may be more power adaptors)

What do you think?

**Comment by konkor** [comment]
It's good idea. We have to think it over.

**Comment by konkor** [comment]
Power Profile Changing on the charging/discharging is ready for testing in the master branch.
The profiles can be assigned in the Preferences -> Power Tab

**Comment by RicardoEPRodrigues** [comment]
I'll test it out when I can.

I now have an Intel laptop, if you want me to test something else just tell me.

**Comment by konkor** [comment]
@RicardoEPRodrigues it would be nice! Did you see my message on Hangouts? :)

**Comment by alexeymuranov** [comment]
Thanks for this feature, but the UI is confusing: what does it mean "when battery level 75%", for example?  Is the selected profile still activated when battery level is 74% or 76%, or only when it is 75%?

I tried it and saw some unexpected behaviour (the profile for battery charging was not activated when I expected it to), but I was not sure I understood the settings correctly...

**Comment by konkor** [comment]
Nice. I'm glad to hear that. :)
