### ISSUE TITLE
Can't update from version 9 to 10 (https://extensions.gnome.org/errors/view/3857)

### ISSUE THREAD

**Issue by konkor** [konkor/cpufreq#35]
@Angel_Garcia sent
Debian 8.8 up to date
```
uname -a
Linux 3.16.0-4-amd64 #1 SMP Debian 3.16.43-2 (2017-04-30) x86_64 GNU/Linux
```
CPU: Intel® Core™ i7-4770K
PState disabled on kernel boot with: `intel_pstate=disable`
this give me more control over CPU speed
The problem showed up after upgrading from previous to new

The extension doesn't load at all, and the sliders thing is what gnome reported.

I've tested every version starting from 12 to 9
And 9 is the first one that works fine
from 10 to 12 they don't load at all

So i cloned the git repo right into the extension folder
I wanted to try the changes in every commit to see which one break loading
so y hard reset the branch to every commit form tag 9.0

it breaks in: 686e0f81b0062da066e510a3577ad23901fc23df
https://github.com/konkor/cpufreq/commit/0b59bcda60463fd458163c43f2a9f3df344d2139

I reloaded the entire gnome shell every time y changed the git state.
Also i disabled any other extension I was using, to check if one of them was causing my problems, but no, problem still there
Gnome report without changes: "TypeError: The slider value must be a number"

**Comment by DarkminecrafterHD** [comment]
I have installed Debian 9 and everything seems to work just fine

It may be related to GnomeShell 3.16

In wich version of GnomeShell do you test it?

**Comment by konkor** [comment]
Actually, It works from 3.14 - latest...

**Comment by DarkminecrafterHD** [comment]
It might be My FrankenDebian, maybe?

**Comment by DarkminecrafterHD** [comment]
I alsto tried last version on a KaliRolling on a ladtop that i have lying arround and it worked flwlessly

**Comment by konkor** [comment]
@DarkminecrafterHD maybe... I think It could be some special policy/permission settings or buggy gjs package...

**Comment by konkor** [comment]
Gnome Developers don't support well middle versions of gnome/gtk/gjs. Only versions in big distros like Red Hat, Debian supported well :(

**Comment by konkor** [comment]
The extension has like millions users but most of them are Archlinux, Debian, Ubuntu, Fedora users... Maybe latest versions of the extension is not tested well on some old and not popular worldwide Gnome's versions like 3.16, 3.18. I'll try to test again on Fedora with 3.16 gnome-shell...

**Comment by thetuber** [comment]
I ran into this problem, and in my case, the saved max freq was bogus. So my "fix" was:

```
$ diff -u extension.js.orig extension.js
--- extension.js.orig   2017-05-23 17:21:48.000000000 +0800
+++ extension.js        2017-06-28 12:05:02.417265284 +0800
@@ -1099,7 +1099,10 @@
         freqInfo = null;
         if (this.util_present) {
             if (save) {
-                return this._set_min (parseInt (this._settings.get_string (MIN_FREQ_KEY)));
+               let tmp = parseInt (this._settings.get_string (MIN_FREQ_KEY));
+               if (!isNaN (tmp)) {
+                    return this._set_min (tmp);
+               }
             }
             cpufreq_output = GLib.spawn_command_line_sync (this.cpufreqctl_path + " minf");
             if (cpufreq_output[0]) freqInfo = cpufreq_output[1].toString().split("\n")[0];
@@ -1130,7 +1133,10 @@
         freqInfo = null;
         if (this.util_present) {
             if (save) {
-                return this._set_max (parseInt (this._settings.get_string (MAX_FREQ_KEY)));
+               let tmp = parseInt (this._settings.get_string (MAX_FREQ_KEY));
+               if (!isNaN (tmp)) {
+                    return this._set_max (tmp);
+               }
             }
             cpufreq_output = GLib.spawn_command_line_sync (this.cpufreqctl_path + " maxf");
             if (cpufreq_output[0]) freqInfo = cpufreq_output[1].toString().split("\n")[0];
```

**Comment by konkor** [comment]
@thetuber Thanks a lot. So it's comming from GSettings. Can you open **dconf-editor** and take a look at `/org/gnome/shell/extensions/cpufreq` values while you are changing parameters in the extension. Share please this values. You could make a screenshot and save some profile to see what storing in the `profiles` value.
I found here one more logic bug...
Thank you again for your nice job!

**Comment by konkor** [comment]
@thetuber So i wanted to reproduce NaN in the GSettings but no luck yet. Maybe it was some early version without properly checking of installation or any other related stuff... heh
I think I should add some section to readme how to completely uninstall extension like:
```
dconf reset -f "/org/gnome/shell/extensions/cpufreq/"
sudo rm /usr/share/polkit-1/actions/konkor.cpufreq.policy
sudo rm /usr/bin/cpufreqctl
```

**Comment by konkor** [comment]
I have an idea to check setting values once at startup?!

**Comment by thetuber** [comment]
Attached are two screenshots, one with a valid setting, and one with an invalid setting. Turns out that if I slide the slider all the way to the right, I get NaN.

**Comment by konkor** [comment]
OK it's coming from
```
_get_freq: function (num) {
        let n = this.frequences.length;
        let step = Math.round ((100 - (100 % n)) / n);
        let i = Math.round (num / step);
        if (i == n) i--;
        return parseInt (this.frequences[i]);
    },
```
can u show me output of
```
$ cpufreqctl freq
```

**Comment by konkor** [comment]
@thetuber can you test latest master branch? You could use `install.sh` script. Just run
```
./install.sh
```
It will download, extract and install latest master branch from GitHub.
Thanks a lot for your time and help!!!

**Comment by thetuber** [comment]
No problem. And thanks for your help and the extension.

Here's what I see:

$ ./cpufreqctl freq
2667000 2666000 2533000 2399000 2266000 2133000 1999000 1866000 1733000 1599000 1466000 1333000 1199000

The main problem is now fixed in the master branch. However, the max freq slider can still show NaN.

![cpufreq-master](https://user-images.githubusercontent.com/29744475/27665503-26008d02-5ca0-11e7-9175-d4194e01cadc.png)

This can be fixed by

```
$ diff -u cpufreq-master/extension.js ~/.local/share/gnome-shell/extensions/cpufreq\@konkor/extension.js
--- cpufreq-master/extension.js 2017-06-28 23:45:29.000000000 +0800
+++ extensions/cpufreq@konkor/extension.js 2017-06-29 07:57:02.527930511 +0800
@@ -848,9 +848,9 @@
 
     _get_freq: function (num) {
         let n = this.frequences.length;
-        let step = Math.round ((100 - (100 % n)) / n);
+        let step = Math.round (100 / n);
         let i = Math.round (num / step);
-        if (i == n) i--;
+        if (i >= n) i = n - 1;
         return parseInt (this.frequences[i]);
     },
```

The math for step and i need to be consistent. The second change is a catch-all just in case there's another bug.

**Comment by konkor** [comment]
OK less code is better. Do you want to make commit?
Can I ask you all this NaNs related to bug about updating from 9 to 10 version? :)

**Comment by thetuber** [comment]
Sure, I can make the commit, as long as the code looks fine to you. Work just got busy, so I may be a bit slow. I don't understand your second question, could you please clarify?

**Comment by konkor** [comment]
This issue is about broken updates to version 10 and higher on some machines...
You have reported about NaN in the gsettings...
Is your bug related to the title of this issue?
PS: I have already pushed this 2 lines. I made another one to 'master' too.
Thank you and maybe next time you will push commits directly to avoid this delays. (

**Comment by thetuber** [comment]
Sounds like the upgrades to version 10 are breaking because of the NaN problem. Hopefully fixing it should also resolve the upgrade issue. The OP can give the new code a shot. No worries about the commit. I'm new to GitHub and Javascript, so wasn't sure who can make commits, whether my code was right, etc.

**Comment by konkor** [comment]
@thetuber I'll push fixing release at extensions.gnome.org I'm new to Gnome JavaScript too. Commits can make only owners of repo. But you can clone any repo on GitHub make own commits to your fork repo and make pull request from you clone.
Thanks for your help.
