### ISSUE TITLE
Doesnt work on kernel 4.12

### ISSUE THREAD

**Issue by mrsinham** [konkor/cpufreq#37]
Hello, first of all this extension is great ;) It helped me a lot to get the max of my laptop.

I just tried the kernel 4.12 and it seems that the extension doesnt have the power to interact with governors anymore.

Config :
XPS 13 9360

Thanks !

**Comment by RicardoEPRodrigues** [comment]
It doesn't seem to affect `intel_pstate`. I also running 4.12 and governors work fine. Have you disabled `intel_pstate`?

**Comment by konkor** [comment]
@mrsinham Thanks for report!
What's a distro are you using? Can you share your `/boot/config-4.12...-amd64` config? Maybe you have some disabled default modules?

**Comment by RicardoEPRodrigues** [comment]
I'm using Ubuntu GNOME 17.04 and I'm using `intel_pstate`, haven't tried disabling it.

[config.txt](https://github.com/konkor/cpufreq/files/1133977/config.txt)

**Comment by konkor** [comment]
Thank you @RicardoEPRodrigues. I missed you;)

**Comment by konkor** [comment]
@RicardoEPRodrigues your config is fine with any driver. You have more loaded driver then me:

```
#
# CPU frequency scaling drivers
#
CONFIG_X86_INTEL_PSTATE=y
CONFIG_X86_PCC_CPUFREQ=y
CONFIG_X86_ACPI_CPUFREQ=y
CONFIG_X86_ACPI_CPUFREQ_CPB=y
CONFIG_X86_POWERNOW_K8=y
CONFIG_X86_AMD_FREQ_SENSITIVITY=m
CONFIG_X86_SPEEDSTEP_CENTRINO=y
CONFIG_X86_P4_CLOCKMOD=m
```

**Comment by mrsinham** [comment]
Hello, here is the config.

Thanks for the quick return ! pstate is not disabled, as you can see
[config-4.12.0-041200-generic.txt](https://github.com/konkor/cpufreq/files/1134003/config-4.12.0-041200-generic.txt)

**Comment by RicardoEPRodrigues** [comment]
I suppose `intel-microcode` isn't related as it is a graphics driver, correct?

Using Ubuntu I found it best not to install the intel driver tool, only if completely needed. Sooner or later the driver will be updated in the repos and better tested.

On other note, [Hyper-threading is giving problems in GNOME](http://news.softpedia.com/news/debian-devs-urge-intel-skylake-and-kaby-lake-users-to-disable-hyperthreading-516654.shtml). (I keep my Hyper-threading on, but it can create weird behaviors)

Maybe Wayland is the culprit, I have to test it out.

**Comment by mrsinham** [comment]
Yes, intel-microcode is separated of the graphical driver. With the intel driver tool I observed better performance on battery side and consumption. Perhaps about wayland, dont know... For the moment I rollbacked to the kernel 4.11.8 and everything is ok (from the ubuntu mainline, too)

**Comment by konkor** [comment]
Just wait a few days for 4.12 kernel it's very fresh yet and not tested well

**Comment by mrsinham** [comment]
I agree, I will wait for it ;) Thx !

Julien LEFEVRE,
Web developer @Twenga
http://about.me/julien.lefevre

2017-07-10 21:24 GMT+02:00 konkor <notifications@github.com>:

**Comment by RicardoEPRodrigues** [comment]
I tested it on Wayland with Intel Mesa drivers and it works just fine. Guess your computer is as crazy as mine!

**Comment by mrsinham** [comment]
haha and the root cause can be anywhere, that's the magic !

**Comment by konkor** [comment]
@RicardoEPRodrigues sorry for off-topic but... Did you see https://github.com/konkor/obmin/tree/devel ? I'd like to see your opinion )

**Comment by terencode** [comment]
@konkor ohhh that's from you? very great extension! :+1:

**Comment by konkor** [comment]
@terencode thanks a lot :) Actually, It's great idea but not the extension yet. I don't know exactly why i made it. Maybe I tired from 100500 OS-es, devises and protocols. And I don't wanted install LAMP + other PHP, PYTHON apps... LOL

**Comment by RicardoEPRodrigues** [comment]
Hi,  sorry for not replying. I'll see the extension when I can. I'm currently on vacations. :)

**Comment by konkor** [comment]
Ah, awesome! I'm really glad for you. Have fun! And good rest from all of this things :)

**Comment by mrsinham** [comment]
I have more info on my issue : 
`$ cpufreq-info -o
         Fréquence CPU minimale - Fréquence CPU maximale  - régulateur
CPU  0       400000 kHz ( 10 %)  -    1752000 kHz ( 46 %)  -  powersave
CPU  1       400000 kHz ( 10 %)  -    2400000 kHz ( 63 %)  -  powersave
CPU  2       400000 kHz ( 10 %)  -    2400000 kHz ( 63 %)  -  powersave
CPU  3       400000 kHz ( 10 %)  -    2400000 kHz ( 63 %)  -  powersave
`
(well it is en french, sorry, but it should be understandable)

It seems that cpu0 is at the good speed limitation but not the other

**Comment by konkor** [comment]
@mrsinham Do you have all core threads enabled? Do you apply new setting through the settings widgets or from some saved profile?
So if you are applying through the profile it can be because it's an extension's feature to remember per core configuration (mixed mode) and if you want same settings on all cores replace your profile or make new one. To do that: load `default` profile, enable all cores if necessary, set desired governor, turbo boost and frequencies and save it to `New profile...`... You could check the values via `cpufreq-info -o` on any step to be sure...

**Comment by mrsinham** [comment]
@konkor all core threads are enabled. I have done every step you mentionned (custom and full profile), and every time it is the same (checked witch cpufreq-info -o). I have tried to change governor, nb core enabled (4 to 2), everything is working correctly but the cpu speed on core 2, 3 and 4

**Comment by konkor** [comment]
@mrsinham OK I'll test the extension. Only Frequency Sliders don't work for you on the kernel 4.12?

**Comment by mrsinham** [comment]
Yep, they work correctly on kernel 4.11.* . The rest is ok on 4.12 : 

Governor :

$ cpufreq-info -o
         Fréquence CPU minimale - Fréquence CPU maximale  - régulateur
CPU  0       400000 kHz ( 10 %)  -    1752000 kHz ( 46 %)  -  performance
CPU  1       400000 kHz ( 10 %)  -    2400000 kHz ( 63 %)  -  performance
CPU  2       400000 kHz ( 10 %)  -    2400000 kHz ( 63 %)  -  performance
CPU  3       400000 kHz ( 10 %)  -    2400000 kHz ( 63 %)  -  performance

or CPU nb :

$ cpufreq-info -o
         Fréquence CPU minimale - Fréquence CPU maximale  - régulateur
CPU  0       400000 kHz ( 10 %)  -    1752000 kHz ( 46 %)  -  powersave
CPU  1       400000 kHz ( 10 %)  -    2400000 kHz ( 63 %)  -  powersave

**Comment by konkor** [comment]
I'm writing right now daily ISO of Ubuntu 17.10 perhaps it has the Linux kernel 4.12 and it's working... heh

**Comment by konkor** [comment]
@mrsinham Can I ask you? What isn't working to you on 4.11 kernel?
I'm an IT Engineer for 20 years and I'm happy with oldest kernels because new kernels have a lot not necessary things for newest even not released hardware yet or improvements for MS Asure servers lol MS is the Diamond Sponsor for Linux now. And every new release has like 1 000 000 new lines of code... Are you sure you need all that staff for you? So more code is more resources for it RAM, CPU time...
I'll check the extension for sure when 4.12 kernel become public. If I would test it from source it's not represent behaviour of future releases with own tools, modules, configs etc.

**Comment by mrsinham** [comment]
Well @konkor  it is a good remark :) I'm using kernel 4.12 because I have a XPS 13 9360 on kabylake. As you perhaps know it, the support for this new generation was catastrophic in term of performances, battery life and driver handling. The first version to support correctly kabylake was 4.10 and it was a primilary port. 4.11 had the patch for my nvme disk power management.  Every minor version things keep getting better. I will soon have a dell WD15 to extend my laptop to two monitors and I need every fix on my architecture. In the futur, I will stay on major version but now I'm forced to follow

**Comment by konkor** [comment]
Hmm @mrsinham I think You know what are you doing. I don't know exactly problems of your hardware but if it has standard architecture it must have to work on any Linux without special compilation. I know many fresh hardware have a lot issues through the unstable firmware first. So you have to look to firmware updates. AND ASK YOUR VENDOR (DELL) FOR SUPPORT IF IT'S NOT LATE YET!!! IF THEY WON`T HELP YOU TELL ABOUT THIS `BRAND` EVERYWHERE! HEH SORRY

**Comment by mrsinham** [comment]
I totally agree :) Many complaints are on it but the main complain to do is for intel as the brand is unable to ship proper documentation of a fondamental item (cpu motherboard) to kernel maintainers ! that's a shame !

**Comment by mrsinham** [comment]
It seems that I must specify each cpu and each are viewed by the system as independant cores : 

```
~ ⌚ 17:12:03
$ cpufreq-info -o
         Fréquence CPU minimale - Fréquence CPU maximale  - régulateur
CPU  0       400000 kHz ( 10 %)  -    1752000 kHz ( 46 %)  -  powersave
CPU  1       400000 kHz ( 10 %)  -    1752000 kHz ( 46 %)  -  powersave
CPU  2       400000 kHz ( 10 %)  -    1752000 kHz ( 46 %)  -  powersave
CPU  3       400000 kHz ( 10 %)  -    1752000 kHz ( 46 %)  -  powersave

~ ⌚ 17:12:17
$ cpufreq-set -u 2552000

~ ⌚ 17:12:52
$ cpufreq-info -o              
         Fréquence CPU minimale - Fréquence CPU maximale  - régulateur
CPU  0       400000 kHz ( 10 %)  -    2552000 kHz ( 67 %)  -  powersave
CPU  1       400000 kHz ( 10 %)  -    1752000 kHz ( 46 %)  -  powersave
CPU  2       400000 kHz ( 10 %)  -    1752000 kHz ( 46 %)  -  powersave
CPU  3       400000 kHz ( 10 %)  -    1752000 kHz ( 46 %)  -  powersave

~ ⌚ 17:12:56
$ 


~ ⌚ 17:14:05
$ sudo cpufreq-set -r -u 2552000 

~ ⌚ 17:14:23
$ cpufreq-info -o                
         Fréquence CPU minimale - Fréquence CPU maximale  - régulateur
CPU  0       400000 kHz ( 10 %)  -    2552000 kHz ( 67 %)  -  powersave
CPU  1       400000 kHz ( 10 %)  -    1752000 kHz ( 46 %)  -  powersave
CPU  2       400000 kHz ( 10 %)  -    1752000 kHz ( 46 %)  -  powersave
CPU  3       400000 kHz ( 10 %)  -    1752000 kHz ( 46 %)  -  powersave

~ ⌚ 17:14:25
$ sudo cpufreq-set -c 2 -u 2552000 

~ ⌚ 17:16:01
$ cpufreq-info -o                  
         Fréquence CPU minimale - Fréquence CPU maximale  - régulateur
CPU  0       400000 kHz ( 10 %)  -    2552000 kHz ( 67 %)  -  powersave
CPU  1       400000 kHz ( 10 %)  -    1752000 kHz ( 46 %)  -  powersave
CPU  2       400000 kHz ( 10 %)  -    2552000 kHz ( 67 %)  -  powersave
CPU  3       400000 kHz ( 10 %)  -    1752000 kHz ( 46 %)  -  powersave

~ ⌚ 17:16:02
$ 
                                                            

```

**Comment by konkor** [comment]
OK If you want we could find a solution remotely...
Give me output of
```
cpufreq-info -d

ls -l /sys/devices/system/cpu
ls -l /sys/devices/system/cpu/cpu0
```

**Comment by mrsinham** [comment]
I used a systemd service for the moment, thx for your help :

```
~ ⌚ 18:30:59
$ cpufreq-info -d

intel_pstate

$ ls -l /sys/devices/system/cpu
total 0
drwxr-xr-x 9 root root    0 juil. 30 18:30 cpu0
drwxr-xr-x 9 root root    0 juil. 30 18:30 cpu1
drwxr-xr-x 9 root root    0 juil. 30 18:30 cpu2
drwxr-xr-x 9 root root    0 juil. 30 18:30 cpu3
drwxr-xr-x 6 root root    0 juil. 30 18:30 cpufreq
drwxr-xr-x 2 root root    0 juil. 30 18:30 cpuidle
drwxr-xr-x 2 root root    0 juil. 30 18:30 hotplug
drwxr-xr-x 2 root root    0 juil. 30 18:30 intel_pstate
-r--r--r-- 1 root root 4096 juil. 30 18:30 isolated
-r--r--r-- 1 root root 4096 juil. 30 18:30 kernel_max
drwxr-xr-x 2 root root    0 juil. 30 18:30 microcode
-r--r--r-- 1 root root 4096 juil. 30 18:30 modalias
-r--r--r-- 1 root root 4096 juil. 30 18:30 offline
-r--r--r-- 1 root root 4096 juil. 30 18:30 online
-r--r--r-- 1 root root 4096 juil. 30 18:30 possible
drwxr-xr-x 2 root root    0 juil. 30 18:30 power
-r--r--r-- 1 root root 4096 juil. 30 18:30 present
-rw-r--r-- 1 root root 4096 juil. 30 18:30 uevent

~ ⌚ 18:31:52
$ ls -l /sys/devices/system/cpu/cpu0

total 0
drwxr-xr-x  7 root root    0 juil. 30 18:32 cache
lrwxrwxrwx  1 root root    0 juil. 30 17:11 cpufreq -> ../cpufreq/policy0
drwxr-xr-x 11 root root    0 juil. 30 17:11 cpuidle
-r--------  1 root root 4096 juil. 30 18:32 crash_notes
-r--------  1 root root 4096 juil. 30 18:32 crash_notes_size
lrwxrwxrwx  1 root root    0 juil. 30 18:32 driver -> ../../../../bus/cpu/drivers/processor
lrwxrwxrwx  1 root root    0 juil. 30 18:32 firmware_node -> ../../../LNXSYSTM:00/LNXCPU:00
drwxr-xr-x  2 root root    0 juil. 30 18:32 hotplug
drwxr-xr-x  2 root root    0 juil. 30 18:32 microcode
lrwxrwxrwx  1 root root    0 juil. 30 18:32 node0 -> ../../node/node0
drwxr-xr-x  2 root root    0 juil. 30 18:32 power
lrwxrwxrwx  1 root root    0 juil. 30 17:11 subsystem -> ../../../../bus/cpu
drwxr-xr-x  2 root root    0 juil. 30 18:32 thermal_throttle
drwxr-xr-x  2 root root    0 juil. 30 17:11 topology
-rw-r--r--  1 root root 4096 juil. 30 17:11 uevent

~ ⌚ 18:32:18
$ 
```

**Comment by konkor** [comment]
Nice give me all :)
```
find /sys/devices/system/cpu -type f -print -exec cat {} \; | gzip > cpufreq_debug.gz
```
and attach `cpufreq_debug.gz`

**Comment by mrsinham** [comment]
Here is the file, thx :)
[cpufreq_debug.gz](https://github.com/konkor/cpufreq/files/1185852/cpufreq_debug.gz)

**Comment by konkor** [comment]
@mrsinham I can't see any special difference in your configuration but
1. The extension doesn't use 'sudo cpufreq-set' it's changing all settings directly for `intel_pstate` mode to the /sys/devices/system/cpu/intel_pstate/min_perf_pct and max_perf_pct when you are changing frequency sliders.
2. In your case It's looking like changing of min_perf_pct/max_perf_pct affect only 1 core. Maybe It's feature of Linux kernel 4.12 and all configuration fully moved to /cpufreq/policy0...3. But why the extension is working for @RicardoEPRodrigues with kernel 4.12 and intel_pstate mode too??? So maybe it's a bug or some specific configuration (software/hardware) I don't know yet... I have to test it on my own first when the 4.12 kernel will be available public...
3. I'm pretty sure You could switch to the acpi driver on 4.12 like a temporary solution. To do that add to grub boot cmdline parameter `intel_pstate=disable`. You could do it permanently by https://github.com/konkor/cpufreq#how-to-disable--intel-pstate-driver how-to...

**Comment by konkor** [comment]
@mrsinham I made a custom distro with Linux kernel 4.12 https://susestudio.com/a/s4HyQu/konkor-linux-gnome-desktop. Download ISO and write to DVD/CD or USB drive and test how the extension works. There is the extension preinstalled but not enabled  to enable it run gnome-shell-extension-prefs or gnome-tweak-tool and turn it on.
user: tux
passwords: linux

**Comment by mrsinham** [comment]
I have issues to boot on the usb device... I cant see it (uefi problem ?)  sorry it takes time..

**Comment by konkor** [comment]
@mrsinham yeah it's take about 1 minute to log into Gnome Shell... I didn't find out what takes so long time... So it's working for your configuration?
