### ISSUE TITLE
Support for TLP?

### ISSUE THREAD

**Issue by waltervargas** [konkor/cpufreq#38]
Do you have support for TLP?

[1] http://linrunner.de/tlp

**Comment by konkor** [comment]
Here is a support for CPU kernel power/performance managing features only. The extension is not depend on any other package it has own driver to handle all supporting features and to support a big range of kernel versions and distributions.
But maybe some features of it I could make in the future. Other features related to power manager you could ask from Gnome developers like a feature request.
So this tool TLP doesn't work with the extension?
Thanks for your interest.

**Comment by RicardoEPRodrigues** [comment]
TLP doesn't interfere with the extension, or at least it shouldn't. I've used both for a long time without a problem.

TLP does allow for battery life improvements. @waltervargas how would this extension support TLP?
