### ISSUE TITLE
Add option to modify periodic frequency query time in seconds

### ISSUE THREAD

**Issue by terencode** [konkor/cpufreq#43]

**Comment by konkor** [comment]
Is a slider from 0 (disabled) to 100 seconds? :)

**Comment by terencode** [comment]
I think a spin button would be better ^^

**Comment by konkor** [comment]
@terencode spin button even easier at least for gtk...

**Comment by terencode** [comment]
Let's go for it then!

**Comment by konkor** [comment]
Done in the service branch
