### ISSUE TITLE
Unable to detect missing turbo boost on intel cpu

### ISSUE THREAD

**Issue by terencode** [konkor/cpufreq#45]
This could be fixed with #44

**Comment by konkor** [comment]
Here is the extension is trying to detect TB support (and this method is working for my core i3 laptop without TB) but it read 1st TB and if it's enabled it doesn't try to disable it to understand if it work or not.
https://github.com/konkor/cpufreq/blob/b38e422090d1f93d052a714c752ce4a9b0272d94/extension.js#L216

What CPU do you have and governor driver (acpi or intel_pstate)?
Can you disable/enable it from terminal?

```
cpufreqctl boost ## read state
cpufreqctl boost 1|0 ## set
```
for intel_pstate but here is inverted values for no_turbo (0-enabled, 1-disabled)
```
cpufreqctl turbo ## read state
cpufreqctl turbo 0|1 ## set
```

**Comment by terencode** [comment]
intel core i3-2375M
intel_pstate
`cpufreqctl turbo
1
cpufreqctl turbo 0
 kernel: intel_pstate: Turbo disabled by BIOS or unavailable on processor`

**Comment by konkor** [comment]
Fixed in the service branch
