### ISSUE TITLE
Installing on Fedora 27 causes instant lockup in gnome

### ISSUE THREAD

**Issue by rstrube** [konkor/cpufreq#47]
Hello,

I'm running a fresh install of Fedora 27, fully updated.

As soon as I attempt to install the cpufreq extension (from https://extensions.gnome.org/), I get an instant lockup.  After rebooting (systemctl reboot) and attempting to login again, I get a black screen with a mouse cursor.

The only way to restore login to gnome was to manually disable the extension:

`gnome-shell-extension-tool -d cpufreq@konkor`

I then deleted the extension from:

`/.local/share/gnome-shell/extensions/`

So I wouldn't accidentally enable it again.

Are there some additional dependencies that Fedora 27 requires?  I installed the kernel-tools package per the documentation.

Thanks!

**Comment by konkor** [comment]
Eh, I have tested on Fedora and found and fixed the issue. It just stacks at https://github.com/konkor/cpufreq/blob/f043ef2a8cfdd1313d73c23a45446f4d54f2a103/extension.js#L1431 when policy and cpufreqctl is not installed. Actually, It should ask admin password or just throw something to stderr...
So I pushed the fixed extension to gnome but it can take a few weeks to release. If you want to install it manually, you have to:
1. Download install script https://github.com/konkor/cpufreq/raw/master/install.sh
2. Fix permissions chmod +x install.sh
3. Run it as user $ ./install
4. Relog/restart gnome-shell
5. Finish installation inside the extension by pressing 'Install...' at bottom side of the menu

Thank you for the report!

**Comment by rstrube** [comment]
Hi,
I have confirmed that things are working great now on Fedora 27.  Thanks for the quick turn around, your extension is a must-have so I was feeling weird not having it available.

Quick question, gnome shell is claiming cpufreq can be updated, should I do this, or would this actually "downgrade" to the latest version on extensions.gnome.org?

Thanks again!

**Comment by konkor** [comment]
Hi, @rstrube 
About the gnome-shell updating, you can fix it in the 'metadata.json' file by adding the version number (  "version": 22). It should look like this:
```
{
...
  "name": "cpufreq", 
  "settings-schema": "org.gnome.shell.extensions.cpufreq", 
  "shell-version": [
    "3.14", 
    "3.16", 
    "3.18", 
    "3.20", 
    "3.22", 
    "3.24", 
    "3.26"
  ], 
  "url": "https://github.com/konkor/cpufreq", 
  "uuid": "cpufreq@konkor", 
  "version": 22
}
```
Or you can download the pre-release zip package (https://extensions.gnome.org/review/download/7681.shell-extension.zip), extract files and replace all in the .local/share/gnome-shell/extensions/cpufreq@konkor folder.

So I will keep this issue opened until the next release. It could help others to find out...

Thank you for the confirmation so :)

**Comment by konkor** [comment]
thanks to @maweki for the quick review.
the latest stable version is active in the gnome repo now!
