### ISSUE TITLE
Getting ready to gnome 4 or any other

### ISSUE THREAD

**Issue by konkor** [konkor/cpufreq#49]
We all heard about the next gnome-shell version where is all gnome-extensions should be rewritten in GTK because St library looks like ending its life cycle together with Gnome 3...
After discussion with @terencode I decided to make GTK version of the gnome extension and started migrate all code to a dedicated gtk application.
Another benefit is ability to run it on any desktop environment with GTK 3.14+.
So I would like to discuss here about upcoming design, mockups, features...
![screenshot from 2017-11-24 18-52-24](https://user-images.githubusercontent.com/1944781/33219168-911dc6cc-d149-11e7-8be1-b67faad5bc6b.png)

**Comment by RicardoEPRodrigues** [comment]
Maybe there can be a tooltip notification for Single Core Thread Warning.

**Comment by konkor** [comment]
The tooltip would be not noticable. But anyway I m wondering about new info widget on the left or right side. So we could move and this warn move there...
I don't have any special mock-up for this application just a few ideas around... But we have a plenty of time ;)

**Comment by konkor** [comment]
![screenshot from 2017-11-27 20-52-42](https://user-images.githubusercontent.com/1944781/41199138-cad19398-6c95-11e8-9cca-4b9770ee2420.png)
