### ISSUE TITLE
Refresh makes the system freeze

### ISSUE THREAD

**Issue by terencode** [konkor/cpufreq#5]
Hi, 
I really like the extension but it seems that each time it refreshes the frequency indicator, it makes the whole system freeze for 0.5 second...
Anyway to make it asynchroneous?

Thanks.

_4.7.2-1-ARCH
Gnome 3.20.2
Nvidia 370.23 proprietary drivers_

**Comment by konkor** [comment]
The extension is refreshing every 2 seconds and read only 1 parameter - the current frequency. Do you have freezes every 2 seconds?!
PS: Maybe the problem somewhere else like nvidia drivers. Some Nvidia drivers have the problem with refreshing display buffer and can be fixed in 'xorg.conf' with option 
Section "Device"
	Driver "nvidia"
	Option      "InitialPixmapPlacement"     "2"
EndSection
There are values can be 0, 1 or 2.
Or something other?

**Comment by terencode** [comment]
Yes it's every 2 seconds I'm getting the freeze.
I've tried to look for similar problems with nvidia and display buffer but only found things about screen tearing and problems during scrolling or fluidity, which I don't have.

**Comment by terencode** [comment]
Indeed,  gnome shell freezes every two seconds. 
I had a look other your suggestion but only found things about screen tearing which is not an issue I'm having.

**Comment by 38github** [comment]
I'd love this tool if it worked ok for me BUT I am having the same issue as terencode. I am using Ubuntu 16.10 Gnome Edition without any proprietary drivers. My computer is an ASUS K53SV. Is there any info you would like from us/me that can help you diagnose the problem?

**Comment by terencode** [comment]
Yes please see my pull request: it has some memory issues but it will give you a good preview of what was the problem and how it should be fixed. Maybe you can then tell me what's wrong with it ;)

**Comment by 38github** [comment]
Terencode, I wish I had knowledge in programming but I don't so I can't try it. If it is easily explained then I can do my best to try out a fixed that I can manage to apply.

**Comment by terencode** [comment]
Issue is now fixed with v4.1.
