### ISSUE TITLE
Constant disk IO due to dconf

### ISSUE THREAD

**Issue by phw** [konkor/cpufreq#51]
This extension is causing endless disk IO by writing to dconf. Running `dconf watch /` yields:

```
/org/gnome/shell/extensions/cpufreq/title
  '0  ㎒'

/org/gnome/shell/extensions/cpufreq/title
  '2.87 ㎓'

/org/gnome/shell/extensions/cpufreq/title
  '2.61 ㎓'

/org/gnome/shell/extensions/cpufreq/title
  '1.45 ㎓'
```
and so on and on.

See https://www.reddit.com/r/archlinux/comments/7gjvf8/constant_disk_io_from_dconfservice/

The issues seems to be that this extension misuses dconf for inter process communication between cpufreq-service and the extension itself. You should consider usiing DBus for this, as it was built for this use case. E.g. my extension at https://github.com/phw/webcam-access-monitor does this for a similar use case.

**Comment by konkor** [comment]
@phw Thank you very much :) I expected this so.
Yeah, cpufreq-service is using GSettings to the communication.
1. 1st it's very new feature and it was the fastest, lightest and lag free decision to me.
2. I didn't have tested dbus server - proxy binding on the low timings but pretty sure dbus will be not the lightest solution...
3. Isn't GSettings cached to the memory?
4. You can reduce frequency pooling interval to reduce IO usage or completely disable it by 0 timeout in the preferences window.
5. I don't think any monitoring is free option.

**Comment by TingPing** [comment]
DConf literally goes over dbus so a solution without the abstraction and disk io is only more efficient

**Comment by phw** [comment]
> I don't think any monitoring is free option.

@konkor There is definitely some truth to this. But the point here is that the dconf solution causes very frequent disk IO for no reason. dconf is meant to store configuration, and as thus it has to persist the data to disk. But for how you use (or misuse) it now as a message bus this writing to disk has no benefit and only ads unnecessary load.

And as TinPing said gsettings / dconf itself is communicating via dbus. And dbus comminication is fast enough for this use case ;)

**Comment by RicardoEPRodrigues** [comment]
Maybe this improvement could be halted until #49 is done? Two birds with one stone?

**Comment by konkor** [comment]
@RicardoEPRodrigues #49 is a long term feature. And DBUS server is already registered and running in the cpufreq-service, so we have to implement dbus interface for current frequency and proxy in the extension only...

**Comment by RicardoEPRodrigues** [comment]
Have you tough of creating a 'Trello' like project in Github and show what are the priorities/what is being done?

**Comment by konkor** [comment]
@RicardoEPRodrigues do you recommend Trello or do you mean the GitHub Project cards? I can try it...

**Comment by RicardoEPRodrigues** [comment]
GitHub Project cards. All in one place.

Trello is better, but lets not start splitting things about.

**Comment by konkor** [comment]
DBUS integration is ready for testing in the master branch

**Comment by konkor** [comment]
@RicardoEPRodrigues I made https://github.com/konkor/cpufreq/projects/1 I'll try to use it ;)

**Comment by konkor** [comment]
Already released and fixed

**Comment by phw** [comment]
Thanks a lot for the quick fix :)
