### ISSUE TITLE
High Memory usage

### ISSUE THREAD

**Issue by snkiz** [konkor/cpufreq#52]
I found that after being logged in for a while my memory was creeping up. System monitor said cpufreq-service was using 6gb last time I killed it. If any logs or anything are required let me know. :)

**Comment by konkor** [comment]
@snkiz Hm... Give please some info about your distro and hardware. So what timeout interval are you using 500 ms or lower? Do you have enabled Blank Screen option in the Power Saving Menu?
I'm running the extension like 24/24 and don't make even shutdown every day on problematic old gjs version (Debian Jessie) with timeout 200ms to example now i have uptime 21:23 and cpufreq-service is 28MB...
Especially, if your screen/display is going to off it's stopping/killing the service and restarting after tuning it on again...

Maybe you have to low frequency interval? Find the optimal update interval for your system, don't go too low values like a few milliseconds only.
Open terminal and run `sudo journalctl -f` and change the frequency interval. You should not see any GLib warnings like canceled...
