### ISSUE TITLE
Symbolic Icons for the governors

### ISSUE THREAD

**Issue by konkor** [konkor/cpufreq#53]
I think we need a set of the governors icons. They could be helpful in the many cases:
1. Someone could use them together with frequency indicator to show which governor active.
2. Now when disabled frequency monitor the applet doesn't show anything. It's good to show the active governor at least.
3. Use them in the notifications and so...
If we would make just TEXT Labels it'll take too large piece of the system status area.
Now I'm going to do abbreviations:
Powersave - POW/PSV/SAV???
Performance - PER/PRF?
Ondemand - OND/DMD/DEM?
Conservative - CON/CSV?
Schedutil - SCH/STL?
Interactive - INT/ITR?
Userspace - USR?
Eh, even this is not easy.

Ideas for icons:
Powersave - 1-2 leafs???
Performance - Rocket/Fire?
Ondemand - Stopwatches?
Conservative - Man Suit?
Schedutil - Calendar/Planer?
Interactive - Some game/media icon?
Userspace - Classic user's silhouette?

_Desired format is SVG. I'm going to do a folder for this staff_

**Comment by balsoft** [comment]
Maybe we could stick with Unicode?
Performance - 🚀 (U+1F680)
Powersave - 🔋 (U+1F50B)
Conservative - 🤵 (U+1F935)
Ondemand - 🙏 (U+1F64F)
Schedutil - 📆 (U+1F4C6)
Interactive - 🎮 (U+1F3AE)
Userspace - 🧔 (U+1F9D4)
Now we just need to find a font that would contain all of these...

**Comment by konkor** [comment]
@balsoft We have a lot of issues with all symbols (MHz, GHz...) like missing fonts or looking weird - too big/small or colorful.
Here is 2 ways to fix it:
1) Create custom font with all symbols (maybe require installation)
2) Replace all with SVG icons
BTW This is not high priority task anyway. I'm just looking forward to standalone app (https://github.com/konkor/cpufreq/issues/49)
Thanks.

**Comment by RicardoEPRodrigues** [comment]
I believe a lot of distros are starting to come with Emojis. Can we use the system's font and use a custom font for MHz and GHz?

(Maybe allow one to force usage of custom font, if they find a problem)

**Comment by balsoft** [comment]
Actually, Google Noto Emoji seems to be free, available in most distro's, and contain all the needed emojis.

**Comment by konkor** [comment]
I have started cpufreq.ttf font to close all issues about symbols...

![cpufreq_font](https://user-images.githubusercontent.com/1944781/44628051-a5893080-a941-11e8-817a-24588b1bb7aa.png)


[cpufreq.ttf.zip](https://github.com/konkor/cpufreq/files/2321489/cpufreq.ttf.zip)

**Comment by konkor** [comment]
Finally, I pushed that font to Master branch. It has 10+ symbols for MHz/GHz and governors mostly. It was a bit tricky to make it. I think I will write a small blog about it on cpufreq io page.

So I'm going to replace all symbols in the extension to put a bold end to it...
