### ISSUE TITLE
Usage description

### ISSUE THREAD

**Issue by jwermuth** [konkor/cpufreq#55]
Hi. Nice plugin. I am missing a description of what the various options do:
* minumum ?
* maximum, is this cpu slice, or throttling, or ...
* boost - I guess this allows for a temporary increase in CPU usage above "Maximum".
* Performance and Powersave modes - what do they do

...
It would be nice with a short description in the readme file.

**Comment by RicardoEPRodrigues** [comment]
Although I agree a better description should exist, yet the minimum and maximum is kinda self explanatory.

* Min is the minimum speed **percentage** `cpufreq` will allow the CPU to go down to.
* Max is the maximum speed **percentage** `cpufreq` will allow the CPU to go up to.
* Turbo Boost is only available on certain CPUs and allow overclocking. When active the 100% Max is increased to the maximum overclocking speed.
* Power modes control how the CPU schedules the clock speed. For example Performance will try to have the CPU always run on Max Speed.

I think this sums up what you asked for. Right?

**Comment by konkor** [comment]
@jwermuth You are right. It can be difficult to understand what is about if you don't understand how to modern CPU works. It's why commercial OSes have some default profiles like powersave/balanced/performance without any technical details.
Maybe it's time to start writing some documentation with application features, ui elements descriptions and how-to... I will try to find some time to write some skeleton of the documentation with some basic description.
@RicardoEPRodrigues Thank you :)

**Comment by konkor** [comment]
I have started http://konkor.github.io/cpufreq/ and any contributions and ideas welcome :)

**Comment by RicardoEPRodrigues** [comment]
@konkor I saw the page.

Why not have the same menu structure, but put all the different install instructions in the same page.

The links then could be something like `http://konkor.github.io/cpufreq/install/#git` instead of `http://konkor.github.io/cpufreq/install/git/`. What do you think?

**Comment by konkor** [comment]
@RicardoEPRodrigues Why? Actually, I'm a new to this framework and don't know how to make it.
Those links is generating auto from https://github.com/konkor/cpufreq/tree/master/docs/_installation md files...

**Comment by RicardoEPRodrigues** [comment]
Given that each section is so small it would make sense to have it all in one page.

Maybe the change it, we have to mess with https://github.com/konkor/cpufreq/blob/master/docs/_config.yml

**Comment by konkor** [comment]
@RicardoEPRodrigues Okay. I think you are right, no any sense to divide it at least now. I'm just playing around. I never used Jekyll before

**Comment by konkor** [comment]
I'm trying to figure this issue out there:
http://konkor.github.io/cpufreq/frontend/
the text is there https://github.com/konkor/cpufreq/blob/master/docs/frontend.md
About the framework you can look here https://github.com/konkor/cpufreq/blob/master/docs/README.md

I think I'm not so good writer... eh

**Comment by konkor** [comment]
I think we can close it. I have collected a lot of information here http://konkor.github.io/cpufreq/
The website's using Jekyll framework and editing of the contend is just editing markdown texts. Every page has a small editing button pointing to github's source page.

**Feel free to contribute some fixes, useful info or a tutorial!**

If you want to test changes before pull requests you can do so:
1. Test it locally (https://github.com/konkor/cpufreq/blob/master/docs/README.md)
 * install Jekyll on your machine (see https://jekyllrb.com/docs/quickstart/)
 * clone/copy the GitHub repo https://github.com/konkor/cpufreq
 * run jekyll inside cpufreq/docs folder
```
bundle exec jekyll serve
# and browse changes at http://localhost:4000/cpufreq/
```

2. Make a fork of the repo, enable GitHub pages in the fork settings, and go to the http://YOURNAME.github.io/cpufreq/ to browse it.

Good luck!
