### ISSUE TITLE
Missing icons (or symbols MHz/ GHz)

### ISSUE THREAD

**Issue by d0tfile** [konkor/cpufreq#57]
Hello, i wrote about this in gnome extensions website. I have strange issue: missing icons in only this extension. I have same setup on PC and laptop, but on laptop i don't face this problem.

- **OS**: Arch Linux (4.14.15-1-ARCH x86_64)
- **DE**: Gnome (gnome-shell 3.26.2)
- **Themes**: Arc (for applications and shell) and Papirus (for icons)
- **Fonts**: Default (Cantarell Bold and Regular)

What did i try:
- Create another user (same, problem is system-wide)
- Compare installed packages (almost same, difference in video drivers)
- Check installed packages integrity
- Reinstall Gnome group
- Check changed system files via pacman (found some, after fixing - no difference)
- Also tried other fonts and themes

Screenshot:
![image](https://user-images.githubusercontent.com/4760202/35849507-e1bd4238-0b32-11e8-83b6-85431acfb335.png)

**Comment by konkor** [comment]
@d0tfile okay. if you select default gnome-shell theme, do you have the same issue?
I still think it's the theme or theme font issue. Arc uses font-family: Futura Bk bt, Cantarell, Sans-Serif; I don't know nothing about Futura Bk bt font and it's 1st...

**Comment by d0tfile** [comment]
@konkor yes, with default theme same issue.

**Comment by terencode** [comment]
@d0tfile I'm using ArchLinux and it is fine for me. Maybe it's a conflict with other extensions so I would suggest you try to disable all the other extensions and restart shell (reboot under wayland) and tell us if it does anything.

**Comment by d0tfile** [comment]
@terencode as i said, i have same setup on PC and laptop, but this issue only on PC :) That's strange, still investigating. I will remove few packages, maybe one of them makes conflict somehow.

**Comment by konkor** [comment]
@d0tfile actually, @terencode is right. Extensions can have `stylesheet.css` it can override any gnome-shell class like StLabel or .popup-menu-item with some exotic font with missing special symbols for whole system.
It's good idea to disable all gnome-shell extensions except this one, restart gnome-shell and see the result. It could help a lot to detect where is the problem.
So if it helps you could enable extension again one by one and find the source of the issue.

**Comment by d0tfile** [comment]
Fixed by installing `ttf-droid`. Can't find in logs any info about removing this package, can't understand how did it work week ago. 😃 
(this also fixes not displaying asian alphabets for me)

Thank you all for you time 👍

**Comment by konkor** [comment]
@d0tfile Oh glad to hear you found out the issue. Just interesting what a cause of using of ttf-droid font... Thank you for your time and the solution!

**Comment by SandPox** [comment]
after install ttf-droid on Arch, it does fix some missing symbol but some are still there 
![screenshot from 2018-03-22 09-08-36](https://user-images.githubusercontent.com/14113155/37747210-a219f3a6-2db0-11e8-87ab-b59e3a28941c.png)

any idea?

**Comment by konkor** [comment]
@SandPox I could be a locale configuration issue or missing fonts. 
You have missing ⚡ - u26A1 (HIGH VOLTAGE SIGN;thunder;lightning)
and some of those ◉◕◑◔◌
try to install ttf-freefont package... or other fonts (after installing it could be required restarting)

BTW Droid fixed other symbols like ㎒ - u3392 ㎓  - u3393

**Comment by konkor** [comment]
DejaVu fonts contain those symbols.

**Comment by SandPox** [comment]
oh yes, it works now, thanks!

probably put these required fonts in README so people can see it?

**Comment by konkor** [comment]
@SandPox I added a few words about it http://konkor.github.io/cpufreq/install/#troubleshooting
Thanks for the report!
