### ISSUE TITLE
cpufreq freezes system

### ISSUE THREAD

**Issue by arvind-d** [konkor/cpufreq#58]
When gnome-shell starts and loads the extension, the gnome-shell locks up. After investigation I found out that the command "pkexec /usr/sbin/cpufreqctl irqbalance" is running. After logging into another terminal I manage to kill the process and everything continues loading. The extension loads up but everything freezes again when trying to change governor or boost from the extension. After killing the stuck pkexec the system unfreezes. 

Polkit policy is present in /usr/share/polkit-1/actions/konkor.cpufreq.policy
I have also added the following polkit rule:

`
polkit.addRule(function(action, subject) {
    if (action.id == "konkor.cpufreq.setcpufreq" && subject.isInGroup("power")) {
        return polkit.Result.YES;
    }
});
`

I made sure that I was in the power group:
`
[arvind@valkyrja ~]$ groups
sys lp wheel network video optical storage scanner power vboxusers plugdev arvind
`

If I try executing the following command manually I get the authorization prompt to enter my password (happens each time I run the command)
`
pkexec /usr/sbin/cpufreqctl gov performance
`

**Comment by konkor** [comment]
@arvind-d  looks like some policy issue.
So default extension policy has permissions to all operations in the _cpufreqctl_ helper and some operations require not just power permissions. Actually, new versions of the extension don't use cpupower/cpufreq tools at all and doing all operations directly through the cpufreqctl script for root operations or extension's modules.
I suggest you to reinstall extension to restore default policy and update policy file and script helper manually.
try to run this command once after reinstalling and restart gnome-shell session
```
sudo ~/.local/share/gnome-shell/extensions/cpufreq@konkor/cpufreqctl install
```
This command is available in the extension menu on the 1st boot or an updating ('Install/Update Extension') but if you modified it without changing the version number the extension does not detect it.
Can you tell me what the distribution do you use?
Thank you for the report.

**Comment by konkor** [comment]
@arvind-d I noticed you copied cpufreqctl to wrong directory ("pkexec **/usr/sbin/**cpufreqctl irqbalance")
It should be **/usr/bin** not **/usr/sbin**!!! You have to remove it from _/usr/sbin_ folder!

**Comment by arvind-d** [comment]
I'm currently running Manjaro (Arch) and my `/usr/sbin` is a symlink to `/usr/bin`, therefore `cpufreqctl` is indeed stored in /usr/bin. 
If I run `which cpufreqctl` however I get `/usr/sbin/cpufreqctl`! The extension also tries to call `/usr/sbin/cpufreqctl` instead of `/usr/bin/cpufreqctl`. I guess the distribution is sending the wrong path somehow. 
For the time being I fixed it by modifying the konkor.cpufreq.policy file and specified `sbin` instead of `bin` in there while I figure out why my distro is running like that. I'm very new to polkit and spent a few hours tonight learning about how it works. 

Anyways, thanks a lot for your kind help, much appreciated!

**Comment by konkor** [comment]
@arvind-d PolicyKit is for user space apps to up some permissions. It doesn't work with root apps directly. You have to delete this symlink and restore policy.
Regards.

**Comment by arvind-d** [comment]
I cannot delete this symlink, as the entire directory is symlinked and is by default. On Arch, the /bin, /sbin and /usr/sbin folders are all symlinked to /usr/bin.

```
$ ls -al /usr/sbin
lrwxrwxrwx 1 root root 3 Nov 27 22:29 /usr/sbin -> bin
```
```
$ ls -al /
...
lrwxrwxrwx   1 root root     7 Nov 27 22:29 bin -> usr/bin
lrwxrwxrwx   1 root root     7 Nov 27 22:29 sbin -> usr/bin
...
```

I found out that my `PATH` environment variable is set to look in the following path order: `/usr/sbin:/sbin:/bin:/usr/games:/usr/local/sbin:/usr/local/bin:/usr/bin`

If I remove `/usr/sbin:/sbin:/bin` from my path and then running `which cpufreqctl` it returns the correct path to `/usr/bin/cpufreqctl`! My path looks like it had been modified by some other application. I'll need to fix that and restore the policy file.

**Comment by konkor** [comment]
@arvind-d I am glad you found out. Actually, the extension works well on Arch I have the Arch user/contributor @terencode (see https://github.com/konkor/cpufreq/issues/57#issuecomment-363766515). So there is even aur repo for the extension but i don't know the maintainer.

**Comment by arvind-d** [comment]
@konkor Yes, the extension works excellent and I love it! Thanks for all your hard work on that! I am currently using the aur repo extension and it is fairly well up to date actually.
