### ISSUE TITLE
Settings don't stick on Fedora 27 / GS 3.26.2

### ISSUE THREAD

**Issue by xalius** [konkor/cpufreq#63]
Hi, first of all thanks for building this nice extension ;-)

Currently my settings seem only to stick for a couple of minutes before they revert back to some defaults, e.g. I set 4 cores and 50%, TB disabled... and after 2 minutes roughly the settings bounce back to 8 cores/100%/TB enabled. I tried creating a custom profile too...

Is this some other service running in the background - I checked and at least cpupower is not running...

**Comment by konkor** [comment]
@xalius Did you find the issue?
Sure, It's really possible you have other Power Management tool/package installed like TLP or laptop-mode tools. Some distros detect laptops and install/suggest such tools.
So if you want to use the extension for cpu management **You have to disable the cpu_power management in the tools**.
For Laptop Mode Tools - You have to set "0" to CONTROL_CPU_FREQUENCY variable inside  `/etc/laptop-mode/conf.d/cpufreq.conf`:
```sh
#
# Should laptop mode tools control the CPU frequency settings?
#
# Set to 0 to disable
CONTROL_CPU_FREQUENCY="0"
```

**Comment by konkor** [comment]
Lack of info
