### ISSUE TITLE
"MHz" and "GHz" doesn't render properly

### ISSUE THREAD

**Issue by PapiCZ** [konkor/cpufreq#64]
I see white square instead of text "GHz" or "MHz".
![image](https://user-images.githubusercontent.com/17556501/38460096-9b19dfca-3ab3-11e8-97df-b0798c746ad8.png)
I tried to modify code of this extension, but nothing helped.

PS: I use Arch Linux and Gnome shell 3.28.0-1.

**Comment by konkor** [comment]
http://konkor.github.io/cpufreq/install/#troubleshooting

**Comment by konkor** [comment]
https://github.com/konkor/cpufreq/issues/57

**Comment by bkdogan** [comment]
While we are on the topic of fonts, why is the font condensed like in your screenshots konkor? Is this deliberate or simply a limitation of GNOME shell? Can we fix this font problem?

**Comment by konkor** [comment]
@bkdogan you are just missing some fonts (see #57). You have to install any fonts which contain this symbols. See http://konkor.github.io/cpufreq/install/#troubleshooting section so.

**Comment by konkor** [comment]
Finally, I pushed that font to Master branch. It has 10+ symbols for MHz/GHz and governors mostly. It was a bit tricky to make it. I think I will write a small blog about it on cpufreq io page.

So I'm going to replace all symbols in the extension to put a bold end to it...

**Comment by digiberk** [comment]
That's awesome, I hope the revised symbols solve all the font issues. Looking forward to reading your blog post. Thanks for your hard work!

**Comment by konkor** [comment]
@digiberk https://konkor.github.io/cpufreq/cpufreq/howto/blog/fonts/2018/12/03/fonts.html :)

**Comment by konkor** [comment]
It's done and ready for testing in the Master branch. So I will try to release next version after couple days testing.
