### ISSUE TITLE
Cpufreq not working on fedora 28 gnome 3.28 (may be an issue on the OS end)

### ISSUE THREAD

**Issue by Overc1ocker** [konkor/cpufreq#66]
Cpufreq doesn't work well on fedora 28. I'm using a computer with a quite old intel E6400, but it works amazing, so I still use it. The issue is according to CpuFreq, my 2.13 GHZ cpu can only go to 800 MHZ, when according to the readout, my cpu is clocked anywhere from 1.59, to 2.13.

**Comment by konkor** [comment]
Hi. The extension has a low io priority for loading frequency values. So it's possible the extension can miss some values when system too busy.
Try to make a bigger interval for monitor 500ms+.
If you have intel_pstate driver mode try to disable it in the grub default config.

**Comment by konkor** [comment]
Can't reproduce the issue...
