### ISSUE TITLE
Not currently working on Gnome 3.22.

### ISSUE THREAD

**Issue by RicardoEPRodrigues** [konkor/cpufreq#7]

**Comment by bugdanov** [comment]
:+1:

**Comment by RicardoEPRodrigues** [comment]
I'm closing this issue as soon has #8 is merged into master.

Until then, for everyone having this problem, just download the branch from the pull request.

**Comment by konkor** [comment]
done w8 update for 7-10 days... sry

**Comment by RicardoEPRodrigues** [comment]
When you have the time, please update the extension in the gnome website 😄
