### ISSUE TITLE
Manager smiley icons inconsistent?

### ISSUE THREAD

**Issue by nathaneltitane** [konkor/cpufreq#74]
I'm currently running Fedora 27 and noticed a minor annoyance witht he smileys: only the green one matches your scheme, the other two are of a different theme/set entirely: they seem to refer to the system variant currently implemented in Gnome.

See attched.

![screenshot from 2018-08-19 12-16-59](https://user-images.githubusercontent.com/5674757/44310764-db5e7000-a3a9-11e8-88da-18d662963e45.png)

![screenshot from 2018-08-19 12-14-09](https://user-images.githubusercontent.com/5674757/44310748-799e0600-a3a9-11e8-8c69-228a8ac7ed7a.png)

**Comment by konkor** [comment]
@nathaneltitane Thank you for the issue. I'm working on it. I'm collecting all app symbols in the small custom font to close all related issues (#53, #57, #64 ...)
![cpufreq_font](https://user-images.githubusercontent.com/1944781/44628028-54793c80-a941-11e8-90f6-0125ce2741ab.png)

**Comment by konkor** [comment]
I made a lot updates in the Master branch including cpufreq font and other things. It would be nice if you could test it before release.

**Comment by konkor** [comment]
Done
