### ISSUE TITLE
[Question] CPU Frequency won't go up while Laptop is Discharging. Governor 'performance' Won't Change That.

### ISSUE THREAD

**Issue by rdlf4** [konkor/cpufreq#77]
I've bought a 2018 Acer Aspire 5 laptop with two AMD GPUs. Processor is an AMD A12 APU @2.7Ghz [Max Speed, TurboCore boost to 3.6Ghz]
Thanks to CPU Frequency Scaling, I can set it to powersave (downclocks it to 1.4Ghz), ondemand (floats between 1.8 to 2.7Ghz), performance (sits on 2.7 Ghz, sometimes jumps to 3.0x Ghz) and everything works well...if my laptop is charging.
When it discharges/runs on battery, this becomes a problem. See, I'd like to game on it, even when my laptop's running on battery. But I just can't make the performance governor to do anything. Only powersave (sits on 1.4Ghz) and ondemand (floats between 1.4 to 1.8Ghz and won't go any higher) do work and I find that annoying. It's my decision to use my computer the way I want until it discharges. It goes without saying my games won't run at a decent framerate while the laptop discharges and that's annoying.

Outputs:
This is what CPUFreq-info outputs:
```
    analyzing CPU 0:
      driver: acpi-cpufreq
      CPUs which run at the same hardware frequency: 0
      CPUs which need to have their frequency coordinated by software: 0
      maximum transition latency: 4.0 us.
      hardware limits: 1.40 GHz - 2.70 GHz
      available frequency steps: 2.70 GHz, 2.30 GHz, 1.80 GHz, 1.40 GHz
      available cpufreq governors: conservative, ondemand, userspace, powersave, performance, schedutil
      current policy: frequency should be within 1.40 GHz and 1.80 GHz.
                      The governor "ondemand" may decide which speed to use
                      within this range.
      current CPU frequency is 1.79 GHz.
      cpufreq stats: 2.70 GHz:77,19%, 2.30 GHz:0,00%, 1.80 GHz:20,43%, 1.40 GHz:2,38%  (891)
    analyzing CPU 1:
      driver: acpi-cpufreq
      CPUs which run at the same hardware frequency: 1
      CPUs which need to have their frequency coordinated by software: 1
      maximum transition latency: 4.0 us.
      hardware limits: 1.40 GHz - 2.70 GHz
      available frequency steps: 2.70 GHz, 2.30 GHz, 1.80 GHz, 1.40 GHz
      available cpufreq governors: conservative, ondemand, userspace, powersave, performance, schedutil
      current policy: frequency should be within 1.40 GHz and 1.80 GHz.
                      The governor "ondemand" may decide which speed to use
                      within this range.
      current CPU frequency is 1.79 GHz.
      cpufreq stats: 2.70 GHz:77,19%, 2.30 GHz:0,00%, 1.80 GHz:20,33%, 1.40 GHz:2,49%  (789)
    analyzing CPU 2:
      driver: acpi-cpufreq
      CPUs which run at the same hardware frequency: 2
      CPUs which need to have their frequency coordinated by software: 2
      maximum transition latency: 4.0 us.
      hardware limits: 1.40 GHz - 2.70 GHz
      available frequency steps: 2.70 GHz, 2.30 GHz, 1.80 GHz, 1.40 GHz
      available cpufreq governors: conservative, ondemand, userspace, powersave, performance, schedutil
      current policy: frequency should be within 1.40 GHz and 1.80 GHz.
                      The governor "ondemand" may decide which speed to use
                      within this range.
      current CPU frequency is 1.78 GHz.
      cpufreq stats: 2.70 GHz:77,19%, 2.30 GHz:0,00%, 1.80 GHz:20,31%, 1.40 GHz:2,51%  (845)
    analyzing CPU 3:
      driver: acpi-cpufreq
      CPUs which run at the same hardware frequency: 3
      CPUs which need to have their frequency coordinated by software: 3
      maximum transition latency: 4.0 us.
      hardware limits: 1.40 GHz - 2.70 GHz
      available frequency steps: 2.70 GHz, 2.30 GHz, 1.80 GHz, 1.40 GHz
      available cpufreq governors: conservative, ondemand, userspace, powersave, performance, schedutil
      current policy: frequency should be within 1.40 GHz and 1.80 GHz.
                      The governor "ondemand" may decide which speed to use
                      within this range.
      current CPU frequency is 1.78 GHz.
      cpufreq stats: 2.70 GHz:77,18%, 2.30 GHz:0,00%, 1.80 GHz:20,43%, 1.40 GHz:2,39%  (1033)
```
CPU Power-frequency output:
```
    rodolfo@rodolfo-Aspire-A515-41G:~$ cpupower frequency-info
    analyzing CPU 0:
      driver: acpi-cpufreq
      CPUs which run at the same hardware frequency: 0
      CPUs which need to have their frequency coordinated by software: 0
      maximum transition latency: 4.0 us
      hardware limits: 1.40 GHz - 2.70 GHz
      available frequency steps:  2.70 GHz, 2.30 GHz, 1.80 GHz, 1.40 GHz
      available cpufreq governors: conservative ondemand userspace powersave performance schedutil
      current policy: frequency should be within 1.40 GHz and 1.80 GHz.
                      The governor "ondemand" may decide which speed to use
                      within this range.
      current CPU frequency: Unable to call hardware
      current CPU frequency: 1.56 GHz (asserted by call to kernel)
      boost state support:
        Supported: yes
        Active: yes
```
CPUFreq drivers:
```
    rodolfo@rodolfo-Aspire-A515-41G:~$ ls -1 /lib/modules/`uname -r`/kernel/drivers/cpufreq/
    amd_freq_sensitivity.ko
    p4-clockmod.ko
    speedstep-lib.ko
```

Questions:
 A) How can I edit a governor's minimum and maximum frequency? I tried to nano /sys/devices/system/cpu/cpu0/cpufreq/"scaling_min_frequency" but it won't let me edit as root.

B) What is really keeping my CPU Frequency from going all the way up to 2.7Ghz even when my laptop is on battery for an AMD CPU?
_Note: I cannot tell whether BIOS functions or restrictions are at play in this context because my BIOS has no such options._

C) Can I set a governor arguments as a parameter for a launcher? The idea behind this is that whenever a game is launched, the application would set the governor itself, so I could have this as a Steam game launcher parameter:

_DRI_PRIME=1 %command% cpupower frequency-set -f 2700000_
(That would be the equivalent to right-clicking a game icon and choosing to launch it with dGPU and all settings maxed out)

Again: my laptop has no problem whatsoever scaling my cpu frequency up to 2.7Ghz if I choose performance governor, and back down if I go with ondemand (1.8Ghz) or powersave (1.4Ghz) but that's when it's charging. I just want that convenience when it's running on battery! That is it. Why can't it be that easy?

**Comment by konkor** [comment]
@rdlf4 I think you have installed some other powersaving utility and/or OS system utility. Usually, many distros installing laptop-mode-tools or TLP when installer detects a laptop, they could include such utilities.
You have to detect it in your package manager and remove them. You can always revert it.
You can find more info [here](https://wiki.archlinux.org/index.php/Category:Power_management)

**Comment by konkor** [comment]
No more info
