### ISSUE TITLE
Feature Request: An option to get only an icon in the top bar

### ISSUE THREAD

**Issue by toverux** [konkor/cpufreq#78]
Hi,

First, thanks for your work, this is a very nice extension.

The extension indicator in the top bar represents the CPU speed followed by the MHz/GHz suffix. While it's nice and beautiful and geek and all, I personally prefer to keep that bar mostly pure and empty. I hate moving things in it, and I especially like GNOME for being a desktop environment that doesn't bother and distracts you (exactly _not_ like Windows).

Would it be possible to add an option that only displays some symbolic icon for the processor?
Thanks a lot ![image](https://user-images.githubusercontent.com/1343250/48439946-d41be800-e787-11e8-879d-f53ec108369d.png)

**Comment by konkor** [comment]
@toverux thanks for your warm feedback!
Actually, you can disable CPU frequency monitoring by setting it to 0. But it will show _... GHz_ now. I could fix it to just _GHz_ symbol. Would it be enough for you? I don't want to use icons...

Optionally, I could make a setting to show current CPU government so.

**Comment by konkor** [comment]
@toverux BTW Do you have any design/sketch of such icon? I could include it to cpufreq font.

**Comment by konkor** [comment]
@toverux you can try master branch now. I have added some things including Custom label. You could even make empty label or one symbol or a word...
