### ISSUE TITLE
Ubuntu 18.04: the extension stops working after reboot!

### ISSUE THREAD

**Issue by konkor** [konkor/cpufreq#82]
I have reply on [extensions.gnome.org](https://extensions.gnome.org/extension/1082/cpufreq/):

```
SlvnLnzl

It works well until I reboot or shutdown my computer (Ubuntu 18.04), is there a workaround to
prevent me from removing and installing the extension everytime I log in ? Thanks.
```

Can somebody proof it? @RicardoEPRodrigues are you still using Ubuntu?

Thanks!

**Comment by RicardoEPRodrigues** [comment]
Hi,

Yes, I still use Ubuntu, but since the last release I don't have problems with the extension. Neither AMD or Intel.

Do you want me to do some tests?

**Comment by isgursoy** [comment]
Yes, does not work. 18.04, 7700hq.

**Comment by konkor** [comment]
Can't reproduce it with released versions. Master - dev branch, so quick reports could fix it faster.
