### ISSUE TITLE
Fixed width applet

### ISSUE THREAD

**Issue by oliwarner** [konkor/cpufreq#83]
My CPU steps between 800MHz and 4.8GHz. When it goes below 1GHz, it gets thinner. Everything else aligned against the applet moves. This also includes a 100% width task bar. It's very distracting when everything on the bottom of the screen changes slightly.

![peek 2018-12-20 15-43](https://user-images.githubusercontent.com/113778/50294579-1d89e200-046e-11e9-9abc-e4647cb81b1a.gif)

Hopefully that goes some way to illustrate my problem. Would it be possible to fix the width to (eg) the widest it could be on that system?

**Comment by konkor** [comment]
I have added extra space for MHz to replace dot symbol. It should fix the issue at least for monospace fonts. Also it could fixed by adding numbers and dot symbol to cpufreq font. One more option is to make delayed widget loading to be the last loaded extension. But I will leave just a extra space for now it should fix the issue in most cases.

![fixed_width](https://user-images.githubusercontent.com/1944781/50820952-a477ff00-1336-11e9-9856-32628c9e4999.gif)

**Comment by mcoyle1960** [comment]
Hello! Love this extension, but I'm still seeing this glitch. I believe I'm running version 17. Here's a video.
https://drive.google.com/open?id=1wcOvubRDsup-8Es2LQsFvIpz3dnUIGJv

**Comment by konkor** [comment]
@mcoyle1960 Sorry for delay! The fixed version is available on GitHub at Master branch. I just wanted to be sure here is no critical issues. Actually, it's not this issue but #85 is a bit huge.
Today I released the version 31 and published on Gnome site. It will be available very soon now.
Thanks for the report.

**Comment by mcoyle1960** [comment]
DLed it and you're correct! Problem fixed. Not sure where I got that old version number from, but that's for the quick reply.

**Comment by duvh93** [comment]
Hello! I still can see this issue even with the last version from extension.gnome.org...

"One more option is to make delayed widget loading to be the last loaded extension", is it something I can do easily?

Thanks for this nice applet

**Comment by konkor** [comment]
@duvh93 Looks like the last reviewer of extensions.gnome.org has been quit this year. So extensions.gnome.org without maintainer 2+ months. Nobody wants do it for free. Also it's a huge amount of work and responsibility.

You can take the latest [cpufreq@konkor.zip](https://github.com/konkor/cpufreq/releases/download/v32.0/cpufreq@konkor.zip) extension zip package from [Releases page](https://github.com/konkor/cpufreq/releases) and install/update it manually.
