### ISSUE TITLE
[Feature Request] Show current frequency in menu

### ISSUE THREAD

**Issue by mpdeimos** [konkor/cpufreq#84]
I've disabled showing the frequency in the indicator icon (just show the governor) to reduce distraction.

Now from time to time I still want to see the CPU frequency. For me the best place would be the popup menu, maybe next to system load average or in between the Min / Max sliders as disabled slider.

I messed with the extension code on my own, but stopped at the point where I saw that the frequency is delivered from the service as full string (including icons) to the extension. When turning off the frequency in the title, this string will also not hold the frequency information I need. I could hack in access to frequency info from `/etc/cpufreq` or `/sys/devices/system/cpu/cpu*/cpufreq/cpuinfo_cur_freq`, but decided to open an issue first to get your thoughts as well.

**Comment by konkor** [comment]
@mpdeimos  Thanks for this. What distraction are you talking about? If it's about the consistent width for MHz - GHz symbols, I think I fixed it in master... Or you could increase monitor interval to 1000-5000 ms.

**Comment by mpdeimos** [comment]
I just do not want to add additional clutter to the always visible UI that's frequently changing. that's all ;)

**Comment by konkor** [comment]
done
