### ISSUE TITLE
how to reset to all default 

### ISSUE THREAD

**Issue by swi2012** [konkor/cpufreq#88]
Hello. I've installed cpufreq today. In bottom of menu there was sign by clicking on which i was asked for my password to do execute cpufreqctl with root rights. How can i revert cpufreq so that cpufreq extension again show me a /!\ sign at the bottom of menu? Like 'totaly revert all changes' ?

**Comment by konkor** [comment]
@swi2012 You have to remove a couple files to revert all system changes:

```sh
su
rm /usr/share/polkit-1/actions/konkor.cpufreq.policy
rm /usr/bin/cpufreqctl
rm /usr/share/fonts/truetype/cpufreq/cpufreq.ttf
```

I'll add the uninstall option to cpufreqctl helper.
Thanks.

BTW This files don't affect any system settings or privacy. So no worries about it.

**Comment by swi2012** [comment]
Yep, i find them by run cpufreqctl in non root mode :)
It's no worries, i just messed a little with extension and want to reset all :)
Thanks for reply!
