### ISSUE TITLE
Sometimes, the extension fails to resume from standby/hibernate states.

### ISSUE THREAD

**Issue by konkor** [konkor/cpufreq#89]
"cpufreq" has received an error report from `parysto`:

What&#39;s wrong?

When screen is locked (i.e. after resuming from standby), the extension often fails to reactivate after unlocking the screen.
Locking and unlocking the screen brings back the extension sometimes. However, it is then visible on the lock screen as well.

What have you tried?

 * Lock and unlock the screen again.
 * Restart (Alt-F2 and r) Gnome.

Automatically detected errors (after bringing the extension back with locking and unlocking again):

  [boxed instance proxy GIName:GLib.Error jsobj@0x7f7422752af0 native@0x55b3d0792730]

================
  TypeError: freqMenu is null

================

Version information:

    Shell version: 3.30.1
    Extension version: 30
    Ubuntu 18.10

**Comment by parysto** [comment]
The failure was cause by the version of "paradoxxxzero/gnome-shell-system-monitor-applet" found at extensions.gnome.org at that time. After switching to latest gnome-shell-system-monitor-applet cloned from their GitGub-repo, CpuFreq stops crashing after unlocking the screen.

**Comment by konkor** [comment]
@parysto Thanks for the reply. I'm glad you have found the issue out. So I can close the issue here :)
