### ISSUE TITLE
Intel i7 8565U max frequency not being detected

### ISSUE THREAD

**Issue by marcemira** [konkor/cpufreq#90]
Hello there! First of all, thank you a lot for this amazing piece of software.

I'm on a Asus UX533FD, whit this processor: https://ark.intel.com/products/149091/Intel-Core-i7-8565U-Processor-8M-Cache-up-to-4-60-GHz-

Now, I'm having some issues with the max and min frequency. When I first boot Ubuntu (19.04 daily, kernel 4.19.0-12-generic) I can see the indicator going from 800Mhz to 4400~4600Mhz on boost. On the menu I can see a min of 400Mhz and a max of 2001Mhz, which is odd... and if I change the governor to any other than performance (the initial for some reason) and or the max to 2001Mhz(can't go any higher), it'll set and lock my max processor speed to that... won't be able to get higher freqs until I do a reboot. Do you have any idea why does this happen? I have uninstalled irqbalance but didn't seem to help. Thanks a lot!

**Comment by RicardoEPRodrigues** [comment]
Hello @marcemira 

This problem can arise from several places, and not necessarily from the extension. If you have Turbo turn on, then you'd expect it to go as high as 4600Mhz, but I noticed the CPU is for Ultrabooks (I have one myself) which tend to suffer from throttling, meaning it won't go as high has announced due to overheating. 

But regarding the locking, do you have the `Remember Settings` on? Try disabling them, reboot, and tweak around a bit. If it is off, try turning it on, put the governor on Powersave and reboot, what happens?

**Comment by konkor** [comment]
@marcemira As mentioned at  the specification of CPU https://ark.intel.com/products/149091/Intel-Core-i7-8565U-Processor-8M-Cache-up-to-4-60-GHz-
```
Configurable TDP-up Frequency 2.00 GHz
Configurable TDP-up 25 W
Configurable TDP-down Frequency 800 MHz
Configurable TDP-down 10 W 
```
That mean the real frequency range is between 800 MHz and 2.00 GHz.

**4.60 GHz** is just a marketing thing, people want to see higher and higher specifications with lower TDP. It's Turbo Boost max possible frequency for a single core at some moment.

So it's not issue at all it's how work Intel processors.

**Comment by marcemira** [comment]
Thanks @konkor, that actually explains a lot. @RicardoEPRodrigues I'll try to tweak a bit more, bit as @konkor said, for some reason it gets stuck on the real frequency ranges instead of the boost ones. It also throttles a lot... so yeah, I'd love to have a awesome Ryzen cpu instead, but manufacturers aren't making pretty laptops with AMD yet, sadly.

**Comment by RicardoEPRodrigues** [comment]
Lenovo already sells AMD CPU/GPU laptops: https://www.lenovo.com/us/en/laptops/ideapad/ideapad-700-series/Ideapad-720S-13-AMD/p/88IP70S0929

**Comment by konkor** [comment]
@marcemira I'm glad my and @RicardoEPRodrigues comments helped you a bit :)

Actually, thermal throttle is an important issue. You could check this #50 thread for it. So you could find some useful info on project's pages http://konkor.github.io/cpufreq/start/
