### ISSUE TITLE
Doesnt work in GNOME 3.32

### ISSUE THREAD

**Issue by Haxk20** [konkor/cpufreq#91]
I just started trying GNOME 3.32 beta and it doesnt work with this extension.
Im happy to provide logs just tell me how since idk how to grab logs of extensions.

**Comment by RicardoEPRodrigues** [comment]
I believe it doesn't work because the GNOME version is not set in the metadata.json

Edit your locale file [metadata.json](https://github.com/konkor/cpufreq/blob/master/metadata.json) and on the `shell-version` an a line with `"3.32"`. Does it work?

**Comment by konkor** [comment]
@Haxk20 Hi. I just tried it on live-CD and git version from master branch is working fine even without changing the version in metadata.json. There is an issue with Live-CD it's outdated iso yet and I made update in the live session to current version (it's 31.90 version). How did you install the extension via extensions.gnome.org? I think I'll test it again a bit later after ISO updating.

BTW. Gnome Shell is looking very nice and promising to be an excellent desktop for next months.

Thanks for report!

**Comment by Haxk20** [comment]
> I believe it doesn't work because the GNOME version is not set in the metadata.json
> 
> Edit your locale file [metadata.json](https://github.com/konkor/cpufreq/blob/master/metadata.json) and on the `shell-version` an a line with `"3.32"`. Does it work?

No sadly it doesnt fix it.

**Comment by Haxk20** [comment]
I discovered ALT+F2 and "lg". After looking at the error it says TypeError: this._construct is not a function. The same error is one other extension i have. I looked at every file in repo and there isnt a mention of this._construct.

**Comment by Haxk20** [comment]
> @Haxk20 Hi. I just tried it on live-CD and git version from master branch is working fine even without changing the version in metadata.json. There is an issue with Live-CD it's outdated iso yet and I made update in the live session to current version (it's 31.90 version). How did you install the extension via extensions.gnome.org? I think I'll test it again a bit later after ISO updating.
> 
> BTW. Gnome Shell is looking very nice and promising to be an excellent desktop for next months.
> 
> Thanks for report!

I have master version of this extension. First time installed trough the site but after that updated manually to master.

**Comment by konkor** [comment]
@Haxk20 Okay. Here is some [instruction for debugging](http://konkor.github.io/cpufreq/install/#troubleshooting)

## Gathering information for reports

Provide more information about your hardware and system like:

 * Intel or AMD CPU
 * intel_pstate or acpi_cpufreq CPU driver
 * Kernel version
 * IRQ Balance enabled or disabled
 * Are you using CPU powering off/on in your profiles
 * Include system journal log's messages or just related parts. See more about logs below.

Report to [issues](https://github.com/konkor/cpufreq/issues) with included system information like distributions, CPU, acpi-cpufreq/intel_pstate mode, system journal errors and description of the issue.

## Debugging

1. First thing to do is check your clean desktop environment to do so you should disable all Gnome shell extensions including this one. Some distributions including pre-installed many extensions and they could conflict with new updates or each other. If all looking fine you can go to the next step.

2. Enable only this extension to test it and easy check system messages.
You can check the system journal messages in a terminal.

3. Run the command `sudo journalctl -f` in a terminal to see `real-time` system messages monitoring and restart Gnome Shell (_X11 only_): <kbd>Alt</kbd>+<kbd>F2</kbd> and enter <kbd>r</kbd> command.

```sh
sudo journalctl -f
```
 * Do not close the monitor in a terminal. Open the extension menu and try to change
 profiles and/or other settings. You could see maybe some warnings, errors or
 when it locks. Copy/paste related messages to text file and include it in your report.

 * Alternatively, you can just _grep_ all messages and check for errors and other warnings.

```sh
# For cpufreq messages
sudo journalctl |grep cpufreq

# For all gnome-session messages
sudo journalctl |grep gnome-session
```

**Comment by Haxk20** [comment]
AMD ryzen 5 2500U
acpi_cpufreq
5.0-rc8
Arch linux
journactl -f [pastebin](https://pastebin.com/UYpJgaQQ)

**Comment by Haxk20** [comment]
from what i see it isnt extension fault but something wrong with my gnome build.
Due to this: JS WARNING: [resource:///org/gnome/gjs/modules/_legacy.js 67]: reference to undefined property "_construct"

**Comment by konkor** [comment]
@Haxk20 Eh, it's why I don't use rolling releases any more sometime it breaks things - any things. And you should wait maybe hours, days, weeks, maybe months before it will be fixed.

BTW: What is your version of Gnome Shell and GJS? (3.32 is not released yet) I'll ask about that _construct function. So I see even some standard extensions supported by gnome failed too.

```sh
#to see gjs version
gjs --version
```

**Comment by Haxk20** [comment]
> @Haxk20 Eh, it's why I don't use rolling releases any more sometime it breaks things - any things. And you should wait maybe hours, days, weeks, maybe months before it will be fixed.
> 
> BTW: What is your version of Gnome Shell and GJS? (3.32 is not released yet) I'll ask about that _construct function. So I see even some standard extensions supported by gnome failed too.
> 
> ```shell
> #to see gjs version
> gjs --version
> ```

indeed. updating gnome-shell to git with all dependencies. gjs is up to date with latest git commit.

**Comment by konkor** [comment]
Eh. If they are removed Lang module in newest gjs it is a big issue!

**Comment by yohanboniface** [comment]
Same here:

```
mars 16 09:24:02 leonardo gnome-shell[7372]: Extension "cpufreq@konkor" had error: TypeError: this._construct is not a function
```

**Comment by konkor** [comment]
@yohanboniface What distro are you using? Actually, it's related to GJS version not Gnome Shell.

Looks like latest GJS dropped supporting for basic Lang module early. It means I have to drop supporting for a bunch of stable/old distros. Also I have to rewrite all class objects inside my projects.

But now, I'm in the middle of something. I'm doing migrating to Gtk framework. Last month I made about 100 commits and continue that migration to something new. If I'll port it now I should replace main development environment and distro too.

Well I have a huge amount of work to do : / 

BTW: @Haxk20 Somehow fixed it for Master branch. @Haxk20 Did you downgraded GJS version???

**Comment by konkor** [comment]
I'm trying to do my best.

Actually, there are 2 ways to fix it:
* Backport Lang module (just include source inside my projects)
* Migrate all to the new class object and drop support to older versions.

Anyway that needs time and testing. Eh

**Comment by konkor** [comment]
@yohanboniface I found that GJS just moved Lang module to _legacy. Gnome Shell v32 dropped support for it. So there are some shell properties/objects have changed their interfaces and we should just fix that.

There is one problem, I couldn't do that in virtual environment for this extension. I will try to fix it soon.

Thanks for report.

BTW: You should provide a full error message for report next time. It would be more useful.

**Comment by yohanboniface** [comment]
> What distro are you using? Actually, it's related to GJS version not Gnome Shell.

Arch Linux
```
leonardo:~ gjs --version
gjs 1.56.0
```

> BTW: You should provide a full error message for report next time. It would be more useful.

OK, sorry for that. I thought that the comment pointing to the dash-to-dock issue was already giving all the info. My bad.

Thanks for your work! Tell me if I can help.

**Comment by konkor** [comment]
@yohanboniface Looks like the Master branch should be working well on Shell 32 bcs it's not bound to it too much now. One thing it's not stable yet.

**Comment by konkor** [comment]
For installing and testing the Master branch you can use [install script](https://github.com/konkor/cpufreq/raw/master/install.sh) after running it you have to finish installation manually now:

```sh
sudo ~/.local/share/gnome-shell/extensions/cpufreq@konkor/cpufreqctl install
## to finish installation, restart gnome session and enable the extension in the
gnome-shell-extension-prefs
```

**Comment by konkor** [comment]
Also you can clone git and make it:

```sh
make
make install

sudo ~/.local/share/gnome-shell/extensions/cpufreq@konkor/cpufreqctl install

## to finish installation, restart gnome session and enable the extension in the
gnome-shell-extension-prefs
```

**Comment by rockorequin** [comment]
Thanks, the version from git works beautifully in ubuntu 19.04 now.

**Comment by konkor** [comment]
UPDATE: You don't have to run manually `sudo ~/.local/share/gnome-shell/extensions/cpufreq@konkor/cpufreqctl install` command any more. The app does it well now.
Thanks for patience.

**Comment by shrimpster00** [comment]
Thanks for the quick fix. Out of curiosity, when will these changes be reflected on extensions.gnome.org?

**Comment by konkor** [comment]
@shrimpster00: 1. There is no maintainers from beginning of the year on extensions.gnome.org. Nobody wants to do it for free.
2. I haven't finished it yet.

**Comment by blazessdd** [comment]
> @shrimpster00: 1. There is no maintainers from beginning of the year on extensions.gnome.org. Nobody wants to do it for free.
> 2. I haven't finished it yet.

willing to learn i can do for free when i have time i ca code a little but dont know what to do : (

**Comment by Haxk20** [comment]
As this isnt an issue anymore on master we can close this one.
@konkor I can most likely mantain it on extension.gnone.org but i cant do it this month. Too much work in school at this point.
