### ISSUE TITLE
Gtk port is almost here.

### ISSUE THREAD

**Issue by konkor** [konkor/cpufreq#92]
I think I'm about to finish Gtk porting of the Gnome extension (Stlib) to standalone Gtk application to replace the extension menu (you could read [about it here](https://konkor.github.io/cpufreq/cpufreq/blog/news/2019/02/24/news.html))

**I have some question about that:**

1. Actually, I have to port `Profiles` only to get ready for 1st release. What do you think is it good idea to save the same behaviour and looking for it?

2. `Re-branding:` I think we should rename the application. **cpufreq** was a simple and familiar to many name for a Gnome extension but not for standalone package because it's Linux kernel module. We have to create a short `Package name`, full `Application name` and some brief description to it. Also logo...
_I have some crazy ideas but I want to know your thoughts first :)_

3. `Rebuilding` of project infrastructure. Should I reorganize the project folders like any other classic projects with `src`, `gnome-extension` folders etc? It could break ability to just clone/download project and replace/run it without package building... Thoughts?
_I think I could manage it later?_

_Yeah, I know it's looking a bit as weird Gtk Application. What do you think?_

![screenshot from 2019-03-01 19-30-14](https://user-images.githubusercontent.com/1944781/53656573-5a3b3c00-3c5c-11e9-89c3-4e96d57282a4.png)

**Comment by RicardoEPRodrigues** [comment]
Hey!

> * Actually, I have to port `Profiles` only to get ready for 1st release. What do you think is it good idea to save the same behaviour and looking for it?

I think that for those using the current indicator the same bahaviour is advised. Yet I've been using an System76 power extension that also modifies screen brightness and whatnot, maybe we can think of something easier to use and with more functionality. I like the way Windows deals with power profiles, where you have 3 clear options - powersaver, balanced and performance - and then you can open advanced options if you wish.

> * `Re-branding:` I think we should rename the application. **cpufreq** was a simple and familiar to many name for a Gnome extension but not for standalone package because it's Linux kernel module. We have to create a short `Package name`, full `Application name' and some brief description to it. Also logo...

For a simple Application name I'd choose something like **CPU Frequency Config**, it tells everyone what it does just by its name.

If you want something fancier we could use a single name with no clear meaning, like Edapi, made up name derived from EDP a Portuguese power company. Newer apps have chosen this course, like Eddy or Etcher.
 
> * `Rebuilding` of project infrastructure. Should I reorganize the project folders like any other classic projects with `src`, `gnome-extension` folders etc? It could break ability to just clone/download project and replace/run it without package building... Thoughts?

I agree with reorganizing the code. Although it breaks some agility, it provides consistency to all that look at GTK apps.

**Comment by konkor** [comment]
Hi, @RicardoEPRodrigues! First thanks for fast replay! You know you are the number one ;)

I want to make an attention main window of the future application should replace the extension menu and have to load fast at least for an extension mode.

> I think that for those using the current indicator the same bahaviour is advised. Yet I've been using an System76 power extension that also modifies screen brightness and whatnot, maybe we can think of something easier to use and with more functionality. I like the way Windows deals with power profiles, where you have 3 clear options - powersaver, balanced and performance - and then you can open advanced options if you wish.

1. Yeah, we can use current behaviour because it's familiar to all current users at least for now (for first iterations). Creating and removing are very simply and intuitive. I just want to modify Editing slightly - I think it could load a selected profile before editing (not just replacing with current values and renaming). Also It's nice to have an profile manager for importing/exporting, ordering, renaming. I think it should be a tab in preferences window.

2. I wanted to try Pop!OS profiles but I had some installation issues on my old Dell laptop before I lost its. There were many issues LVM, Bluetooth, Wi-Fi etc. So I don't know how it good or bad. **Actually, I thought Gnome Shell could manage Brightness on battery?**

3. Predefined profiles generated on first boot based on user's hardware is nice idea. We can do it.

4. I think to try integrate TLP on some level in future versions too.

> For a simple Application name I'd choose something like CPU Frequency Config, it tells everyone what it does just by its name.

Actually, I'm using something similar in docs like **CPUFreq Manager**. And single word package name would be nice to have too. Maybe something greek? I tired to think about it. Eh.

> I agree with reorganizing the code. Although it breaks some agility, it provides consistency to all that look at GTK apps.

Actually, I could do it later after some building tool integration like autotools or meson.

_I just want to finish this porting quickly. I'm a bit tired of it. I'm asking myself a lot questions. eh_

**Comment by RicardoEPRodrigues** [comment]
New name **Poder** (from the Portuguese of Power, the greek is not that charming) or even **Ponder** :smile: 

> I just want to finish this porting quickly. I'm a bit tired of it. I'm asking myself a lot questions. eh

You can do it! We're here with you! :smile: 

> Actually, I thought Gnome Shell could manage Brightness on battery?

The System76 power extension, on the powersaving preset lowers the screen brightness, I don't know how.

**Comment by konkor** [comment]
Oh, nice option :)

I think brightness control is done over dbus UPower interface, the same way we listen battery levels.

**Comment by konkor** [comment]
BTW Greek variants of power:
Exusia (exus)
Dinami
Energia

**Comment by RicardoEPRodrigues** [comment]
Exus is a cool name. Energia is the same as in Portuguese and dinami is not that cool.

**Comment by konkor** [comment]
I think the remember option is deprecated since we're using profiles. I will rework the project's scheme and create current_profile for almost all separated options. That will make possible to use all profile's features likes online cores count, individual governors (mixed governors), frequencies. I should make it now while porting. Eh.

**Comment by konkor** [comment]
I tried the app on KDE today. It's first alien DE :)
All work as expected, just some theming issues, eh

![Screenshot_20190308_200837](https://user-images.githubusercontent.com/1944781/54053739-e6b3a480-41f0-11e9-83a8-db682c931829.png)

**Comment by konkor** [comment]
@RicardoEPRodrigues I have researched a bit System76 power profiles and I found next:

1. They have a vendor locking on Intel processors (intel_pstate driver and amd64 arch only) and Intel-NVidia switch-able graphics cards. So they don't have any support for AMD, ARM, ACPI driver (even modern Intel processors but with disabled intel_pstate kernel) or any other architectures.
2. They have a vendor locking on own brand (system76-power - analogy to our cpufreqctl with own profiles supporting). Also the gnome extension is not available in gnome extensions repo.
3. So there is less functionality and customization and zero monitoring abilities.

Actually, they have some goodies which we were talking about like predefined profiles to an example.

Well. I don't want to support vender-locked solution. So We should create own **system-power** or **open-system-power** or **open-power** :)

**Comment by RicardoEPRodrigues** [comment]
They, System76, as a company that makes Intel only laptops should focus on Intel only processors, which I understand. I just want you to have a look at what they are doing in architecture and design. I agree with a **open-power** utility to help manage these things.

I also follow the development of **GameMode** (https://github.com/FeralInteractive/gamemode) which is focused on boosting CPU/GPU performance when running games, and returning to the previous state when in common work. Maybe it should be interesting to explore what they are doing.

**Comment by konkor** [comment]
@RicardoEPRodrigues Okay. I don't care about System76 decisions too much. Thanks for the link. Sure, Linux has a lot performance abilities and IO schedulers, priorities, controls over PCI/USB devices etc.

Actually, I removed a lot of code from extension and made a calling of that cpufreq-application. So I'm planning next task for the next realease:

1. I have to add a couple CLI options for the app to restoring saved settings and loading profiles by GUID.
2. I want to make some additional work around `extension mode` of the app.
3. `DEB packaging`: desktop shortcuts, symbolic man.
4. `SystemD units` for restoring saved settings on startups at least now (it should be useful for non-Gnome DEs)
5. I think I should add those predefined profiles ('battery', 'balanced' and 'performance') in addition to existing `default` and user profiles.
6. I can create that power profiles widget to the system menu like:
 * Power Profiles =>
  * battery
  * balanced
  * performance
  * system default
  * user profile (for last selected user settings)
7. I think it's the best time for rebranding I like **system-power** (like an analogy to `system76-power`) and **open-power**. Also we could even create an organisation if this solution will be succeed like `Open System Power Initiative (OSPI)` LOL or any combination of similar context thing.
8. Do quick update of documentation, testing, make code more readable...

Next versions:
1. Move functionality of monitoring power states to that new core module (**system-power**) and full profiles support.
2. Create an analogy to our gnome-extension for other DE (I think about AppIndicator. It's supported almost everywhere somehow).
...

`Looks like I just wanted to order my thoughts here. LOL`

**Comment by konkor** [comment]
@RicardoEPRodrigues @terencode Well, What do you think about organization/domain/group names for _Open System Power Initiative_ like:
1. **ospi** you could pronounce it like OS Pie :)
2. **ospower** OS Power :)

???

Also OS is like Open System and same time Open Source ;)

_BTW: Just **osp** is busy and not so fancy anyway._

**Comment by RicardoEPRodrigues** [comment]
Hey!

**OS** could also be taken as Operative System, where **ospower** would be very intuitive! 😄 

I vote on **OSPower**!

**Comment by konkor** [comment]
Also I want to try gitlab, so gitlab.com or gitlab.gnome.org? :) Gnome is a bit complicated for contributors.

**Comment by RicardoEPRodrigues** [comment]
Complicated? In what way?

I'd prefer gitlab.gnome.org where the app would be at home, but if it is too much trouble then just choose other one.

**Comment by konkor** [comment]
Registration for users to able send pull request. Also I don't really understand terms of usage.

Actually, I will keep this repository as a mirror anyway or vice versa.

I have already accounts everywhere. LoL

**Comment by CommanderStrax** [comment]
Gnome 3 user here. Why did you change this? This thing now is slow, big and ugly (even by my standards)
![nope](https://user-images.githubusercontent.com/46234045/54869663-476be100-4d9c-11e9-8a54-d70c4b9e3808.gif)

oh and it clips over to my second screen, that has no gnome shell bar on it so this looks really weird. 

This is on Arch Linux (so Gnome 3.32) and AMD CPU and GPU if that matters.

**Comment by konkor** [comment]
@CommanderStrax Thank you for your reply!
1. I think It's not so slow for standalone application. Actually, It's doing almost same think as the extension. It doesn't have major extra features but some more optimisation. So benefits of that:
 * It doesn't keep whole thing in memory all time.
 * It doesn't take startup time of GNOME Shell. Actually, it's all async and almost transparent to users if their don't try to open the old extension immediately after screen unlock.
 * It's freeing GNOME Shell resources itself. You know All extensions and Shell itself are running in single thread.
 * It's already standalone application and running well on all kinds of desktops now.
Yeah I'm sure here is a lot things and optimisations to do.

2. I'm going to make savings of window's position and geometry on exit. So it's should cover almost all needs. Also I see that new MB Vendor and Model could be really long and should be fixed thanks for that screen.

Actually, keep all in memory after 1st loading. But do you really often opening it in real life?

BTW. I have just started on binary power daemon to work with it. It should bring a lot of benefits to it.

**Comment by CommanderStrax** [comment]
waaait, Isn't this supposed to be an extension? I may have installed the wrong thing then...

**Comment by konkor** [comment]
@CommanderStrax there is no the old-style extension for Gnome Shell 32. It would be the thing...

I've just pushed a small fix to LONG vendor name and model. _make && make install_

**Comment by konkor** [comment]
Okay. I think there is could be some compromise. I could make small menu for quick profiles switching there and button to open main application. I will try to make some optimizations and profiling so

**Comment by konkor** [comment]
@CommanderStrax Can you check lastest from master? I done some optimizations. In my case Startup Time reduced from 1500-2000ms to <500ms. It's about 3x faster now!

**Comment by CommanderStrax** [comment]
I removed the version I had installed, restarted gnome, then executed the install script again and then restarted gnome again (Alt+F2 r). Now no menu is appearing at all.

Also I don't understand what you meant with

> there is no the old-style extension for Gnome Shell 32. It would be the thing...

Did Gnome change something that made the previous way of showing the menu difficult/impossible?

**Comment by konkor** [comment]
@CommanderStrax Ooops. Try to open the app from console and give me the output:

```sh
~/.local/share/gnome-shell/extensions/cpufreq@konkor/cpufreq-application
```

**Comment by konkor** [comment]
BTW Yes. GNOME Shell breaks old gjs API and supports 3.28+ only. It's like I have to support 2 versions of the extension. It's okay for very stable extensions without any new features for years. Also GTK port was already planned long time ago to cover more DE not just GNOME. You know GNOME Shell had good as bad times. So that API doesn't supported by any stable distros like Debian, Red Hat, CentOS...

**Comment by konkor** [comment]
@CommanderStrax okay. If you didn't fixed it yet, try master now. I want to know your opinion.

**Comment by CommanderStrax** [comment]
okay, just tried it again - works better now. The first two times I left-click the 'label' it still takes some time to appear but after that it is fine. Thanks. Also the UI itself reacts much better now and it aligns with the border of the primary screen.

The only thing that is still bothering me now is the bright red background colour. Compared to how it was before it takes some getting used to.

Thanks for your efforts! Also thank you for explaining the reason for the change. Very much appreciated.

**Comment by konkor** [comment]
@CommanderStrax Thanks for your opinion. I'm really appreciate it!

There is the _Dark theme_ option in the _Preferences window_. Also it's not final design but some people likes it.

About 1st double clicks: I thought it bug too but it couldn't open GUI bcs it's already running in background to check/restore settings on startup.

**Comment by konkor** [comment]
Just pushed saving window's size and position. @CommanderStrax you can place it anywhere now.

**Comment by CommanderStrax** [comment]
selecting the dark theme still leaves the left panel (the one showing the current values and system information) red. Would be nice if we could configure that.

**Comment by konkor** [comment]
Like this?
![Screenshot 2019-03-24 22-34-38](https://user-images.githubusercontent.com/1944781/54885521-b5400780-4e85-11e9-9e26-ea2a9da76a44.png)

**Comment by CommanderStrax** [comment]
For me at least that would be quite okay. Maybe slap a border around it that has its colour adjusted based upon the system status?

Also: I just updated the extension on my end and it now increases in size a bit everytime I close and open it. If I resize it to its minimum size and put it in the center of my left/primary screen and close it, and then open/close it 10 times it will be full sized on my right screen (for some reason).

**Comment by konkor** [comment]
@CommanderStrax Oh. Thanks for ideas and that sizing bug I will try to debug it.

**Comment by konkor** [comment]
@CommanderStrax Well. I have fixed the geometry bug. I think :)

**Comment by CommanderStrax** [comment]
well, it is not changing its size anymore which was really annoying, but now it is wandering up every time I open and close it.

**Comment by konkor** [comment]
@CommanderStrax thanks for feedback. Are you on Wayland?

**Comment by konkor** [comment]
Actually, I should detect Gtk versions and apply different methods to it.

BTW: I'm playing with UI now. I called it statebar. It should change color depending on the system status states. I think It will be last thing before freezing, testing, fixing and transitional release to get more feedback and test results. LoL

![Screenshot from 2019-03-25 20-55-43](https://user-images.githubusercontent.com/1944781/54947570-504ae700-4f43-11e9-821f-e0b68ffa5308.png)

**Comment by CommanderStrax** [comment]
Hey, nope I'm using X.  Also that screenshot looks awesome. Maybe thin the bar on the left a bit?

**Comment by CommanderStrax** [comment]
uhm, just got myself the latest version. Don't know if I didn't see that the first time but after it moved up to the bar, it then moves to the left when continuing to open and close.

**Comment by konkor** [comment]
I found the issue with moving. I will push it later.

I think about that color bar will be transparent or like foreground color for normal state. So for warning states it okay a bit large. I think...

Eh. Looks like I could play with UI weeks...

**Comment by konkor** [comment]
You can test it. But state bar not finished yet. I made it thinner a bit and added shades.

**Comment by CommanderStrax** [comment]
Something must have gone wrong as I'm still having the moving issue and the background of the system details/information panel is still red while the bar isn't colored at all.

![grafik](https://user-images.githubusercontent.com/46234045/55026011-5f449e80-5002-11e9-90e3-e247ca856025.png)

**Comment by konkor** [comment]
Thanks for this picture. I forget about and class. Now I'm working on CSS in time.

I don't know how to fix that moving or why it's happening to you. Like temporary solution I can disable restoring position in the extension mod. So It will be appear near cursor like it was before. But size will be keeping.

**Comment by konkor** [comment]
@CommanderStrax I want you to ask a couple questions about moving bug:
1. Are you using that experimental Fractal scalping or any?
2. How you are configure your dual monitors setup?
3. What video drivers are you using?

**Comment by konkor** [comment]
Eh. Maybe it's nice idea to use headerbar for color states...

![Screenshot from 2019-03-27 18-29-46](https://user-images.githubusercontent.com/1944781/55104165-87033780-50d2-11e9-959b-99833479d17f.png)

**Comment by konkor** [comment]
![Screenshot from 2019-03-27 18-30-21](https://user-images.githubusercontent.com/1944781/55104332-e6614780-50d2-11e9-9279-c49050ed7f86.png)

**Comment by konkor** [comment]
![Screenshot from 2019-03-27 16-33-02](https://user-images.githubusercontent.com/1944781/55104784-bcf4eb80-50d3-11e9-954c-892e8dd58991.png)

**Comment by konkor** [comment]
I'm going to release version 33 _OMG! version_ soon. It would be release for Shell only because:
1. I want to test it more widely.
2. Next version I would like to see by new brand **OS Power Manager** for this application. Also there is planed just **OS Power** - compatible command line daemon, launcher, power profiler, possible, written on Vala to be binary light fast analogy. I think I will be duplicate functionality in the GUI version until it would be ready.
3. I want to rework profiles to be more general use for other hardware, software like displays disk, video etc.
4. I want to enhance events too. Like Loading, System Status, Thermal Throttle, Memory, Swap events etc. So It would be possible to apply Power Profiles on such events too not just Battery. It would be possible to create some dynamic sequence of power profiles based on System Loading like Loading: 0% - Super low profile, Loading 50% - Normal, Loading 100% - High Performance.

So more I'm working on it more work I see. Even this port is endless. :/

BTW I have stopped on default theme like this to make it more classic.

![screen](https://i.imgur.com/RQ2Eiqr.png)

@RicardoEPRodrigues I know you always wanted it. Power profiles on top :)

**Comment by RicardoEPRodrigues** [comment]
YEY! Finally! 🎉🎉🎉

Congratulations, this release is great! When I have time I'll test it out! 😊

**Comment by CommanderStrax** [comment]
Sorry, got busy with other stuff...anyway.

> @CommanderStrax I want you to ask a couple questions about moving bug:
> 
>     1. Are you using that experimental Fractal scalping or any?
> 
nope. No scaling. Or scalping for that matter ;)

>     2. How you are configure your dual monitors setup?
> 
I used the gnome display setting screen. Primary has a resolution of 2560x1440, secondary is 1920x1080. Setting is 'Join displays'. Scaling is set to 100% for both of them.
>     3. What video drivers are you using?
Kernel: amdgpu
Userspace: mesa/radeonsi

**Comment by konkor** [comment]
Thanks for feedback. I asked about it and it's rare thing when positioning is working like my configuration. Wayland doesn't support it at all.
Looks like I will disable that feature or make it like a hidden option in the settings.
