### ISSUE TITLE
Extension incorrectly reporting max frequncy on max freq slider.

### ISSUE THREAD

**Issue by Haxk20** [konkor/cpufreq#94]
Even tho extension now works on GNOME 3.32 there is an issue that when my laptop is plugged in into AC the extension reports as usual max 2Ghz but really its going up to 3.6Ghz due to AMD turbo boost.
But when i move the slider there is a bug that i cannot move the slider back to 2Ghz so that CPU can boost all the way to 3.6Ghz but the slider maxs out at 1.7Ghz. This wasnt an issue before GTK port.

**Comment by konkor** [comment]
@Haxk20 Oh, man. I see I was wrong to move the Gtk branch to master. Actually, it's development branch for pretty long time but this Gtk branch is very unstable yet. I just wanted to make focus on it and pick some attention to it to know some thoughts to get some early tests reports etc.

I thought it will be pretty faster to get stable enough Gtk branch but I can't see the end yet. The extension functionality was growing fast, it's supporting 3.14 - 3.30 Gnome versions, almost all Linux distros and architectures at least now. So many enhancements, features, workarounds and bug fixes did a mess with code. Now I'm a bit stuck with unfixed GJS bug for 10 years and so on. I will try to work on it harder to make it useful now but we're just people.

So you can pick latest released `classic version` 32 now on [Releases page](https://github.com/konkor/cpufreq/releases) on clone and use [extension branch](https://github.com/konkor/cpufreq/tree/extension). I'll switch to that branch back.

Thanks!

**Comment by Haxk20** [comment]
@konkor Yes Turbo boost cannot be disabled on AMD. Well it can if you set max frequency to <2.0Ghz which is what  happens here as im not able to get the slider past 1.7Ghz. Slider reaches end but only 1.7Ghz.
Dont be so harsh on yourself. The GTK port is amazing. This is the only issue i have with it. Other the this bug. Good work. I love the red backgroud when the CPU is from AMD. Attention to details !

**Comment by Haxk20** [comment]
Also cant switch to old branch as that one doesnt support GNOME 3.32.

**Comment by konkor** [comment]
@Haxk20 Thanks for the reply.

1. I fixed that max frequency issue in the master.
2. I thought Turbo Boost could be switched on AMD at least early (I have no AMD hw now)

I'd like to have some testing hardware on my savings but I would be complete insane in my life situation. So I'm following kernel docs and your tests now.

**Comment by Haxk20** [comment]
Will test right away. @konkor

**Comment by Haxk20** [comment]
Yes @konkor fixed. But one issue is that max freq slider cannot be set to 1.8 or 1.9Ghz. It goes 1.6Ghz which is base to 1.7Ghz and then 2.0Ghz. I mean for me this isnt an issue since i dont want to limit my CPU for more powersaving. But other users may find this annoying.
Also should i open another issue for new bug cause i mean after this last update oh boy.
Nah i will just do a list here:
1. No close button on the GTK window (But i guess clicking on the extestion in gnome top bar could also make it close. This would be a nice feature as i dont really want to click on the extension and then click that close button)
2. The GTK window is too tall. It fits entire screen which isnt needed at all since all the info fits in like 1/4 of the vertical size of the window.
This is so far all of the issues i saw so far.

**Comment by konkor** [comment]
@Haxk20 Nice. But I can't clearly understand what's going on with your frequencies. Can you provide me out put of
```sh
cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_available_frequencies
```
to better understand you. Thanks

**Comment by konkor** [comment]
@Haxk20 About other issues:

1. Yeah it's nice idea to closing on second click. Now it's closing auto on focus-out event in the extension mode.
2. I made it for testing and developing purposes. Actually, I made it even before scroll window. So I will reconsider it when it goes to release closer. Sure on big monitors it could look weird.
