### ISSUE TITLE
what happend to old menu

### ISSUE THREAD

**Issue by mortezaPRK** [konkor/cpufreq#97]
i updated ext. today, and saw the change you made to UI. can you add option to use old implementation? please

**Comment by konkor** [comment]
Hi, @mortezaPRK I want to know What're your concerns?

It's not just UI changes it's a standalone application written on Gtk framework. Actually, it's not complete changes yet and for the GNOME Extension part planned some extra elements for switching Power Profiles in the System Aggregate Menu to not call the main manager application all the time.

This transformation was planned 2 years ago. I have mentioned that not once. To example in that [blog post](https://konkor.github.io/cpufreq/cpufreq/blog/news/2019/02/24/news.html), in the [issue thread](https://github.com/konkor/cpufreq/issues/92#issuecomment-475894515) and more.

I wanted to write post about this release, its benefits and concerns. But I'm tired and want to update other projects too.

In two words it is freeing up system resources (it doesn't running all the time). So there is more opportunities to grow to add more functionality for monitoring and power management etc.

Thanks.

**Comment by mortezaPRK** [comment]
Ok. But old implementation was a good one and i use to it. May be we can write a wrapper for gnome?
I'm open to contribute to this repo if you want.

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by konkor** [comment]
@mortezaPRK Oh. Thank you for your proposal! Let me now a bit later after next release. I want to finish that transformation first and release it for all other DEs. I expected such "negative" response from old GNOME Shell users and I should explain it a bit more.

BTW: If you are using early versions than GNOME Shell 3.32 you could install v32 of the extension from [releases pages](https://github.com/konkor/cpufreq/releases) manually and just fix version number in metadata.json file to ex: _101_ to avoid updating. Also I saw someone made a fork of extension and updated it to ES6 syntax. 

**I would worry about such moving there are much more benefits then concerns.** You can get used to it in few days! Believe me ;)

Now I don't want to support several versions of the application with equivalent functionality.

**Comment by konkor** [comment]
@mortezaPRK BTW You can select the _dark theme mode_ option in the preferences window now to make look more familiar to the old fashioned extension.
Sorry for inconvenience.

![Screenshot from 2019-04-01 10-16-16](https://user-images.githubusercontent.com/1944781/55671153-c5dc7e80-5884-11e9-86e4-e170793360d1.png)

**Comment by eding42** [comment]
@konkor I did select the dark mode option in preferences, but the menu still stays in light mode for some reason.

**Comment by konkor** [comment]
I have noticed Ubuntu 18.04 default theme has that issue.

**Comment by konkor** [comment]
@eding42 To able to use that feature your theme should support Dark variant. Ubuntu's Radiannt and Ambience don't support it. Just switch to Ubuntu community theme _Yaru_ or native Gtk _Adwaita_ or any other based on Adwaita.

Even Ubuntu dropped shipping with it and uses Yaru in 18.10+
