### ISSUE TITLE
Extension is asking for root permission when trying to open the menu

### ISSUE THREAD

**Issue by CommanderStrax** [konkor/cpufreq#99]
...and that is not okay. The message doesn't say why root permissions are required. An extension should - at least in my opinion - never ask for root permission. If something is required to be done the extension should tell the user what to do and why.

**Comment by konkor** [comment]
@CommanderStrax Actually, there is a small info in the description: _It needs root permission to able changing governors._ Also it's asking in the message: _Install required system components?_ :) Now it's Policy to able user call backend, cpufreqctl backend and cpufreq.ttf font with required symbols. But here could be more components soon. So there is no stable API for backend and I could point to install/update it very often.

Without that one time permission users couldn't be able change, or some time get some system info. It was almost the same behaviour always at least for this app.

What I should to place there?

**Comment by CommanderStrax** [comment]
What exactly are you changing on the system? It was just irritating for me to see such a message from an extension.

Maybe just have a 'details' type of textbox that shows what you are going to do (install a font, copy a file...)

**Comment by konkor** [comment]
Usually it updates cpuhelperctl... I don't know exactly how it would be looking tomorrow yet. Also people's crying about already long booting. Eh.

BTW even apt-get doesn't give you such info :)

**Comment by konkor** [comment]
So you can always press Cancel and go to extension's folder and run manually:
```sh
sudo ./cpufreqctl install
```
And see messages ;)

**Comment by konkor** [comment]
There is no methods in Gnome Shell Extensions packages to install some system wide components!

**Comment by oliwarner** [comment]
> So you can always press Cancel and go to extension's folder and run manually...

It should advertise that option.  
I agree with OP. An extension asking for root is sketchy-af.
